import { AppParams } from "~/types";

const app = {
  id: "1password",
  name: "1Password",
  icon: "/app-icons/1password.png",
  homepage: "https://1password.com",
  description: "1Password is a password manager that keeps you safe online.",
  globals: {
    "shift+cmdorctrl+space": "show quick access",
    "cmdorctrl+shift+l": "lock 1password",
    "cmdorctrl+\\": "autofill",
  },
  shortcuts: {
    "cmd+/": "view keyboard shortcuts",
    "ctrl+shift+/": "view keyboard shortcuts (windows)",
    "cmdorctrl+,": "open preferences",
    "cmdorctrl+f": "search for items",
    "alt+cmdorctrl+f": "find items in the current list",
    "shift+cmdorctrl+f":
      "open the website for the selected login in your browser and fill your username and password",
    "ctrl+enter":
      "open the website for the selected login in a new tab and fill your username and password (windows)",
    esc: "clear the search field",
    "cmdorctrl+1": "switch to all accounts",
    "cmdorctrl+2": "switch accounts and collections",
    "cmdorctrl+3": "switch accounts and collections",
    "cmdorctrl+4": "switch accounts and collections",
    "cmdorctrl+5": "switch accounts and collections",
    "cmdorctrl+6": "switch accounts and collections",
    "cmdorctrl+7": "switch accounts and collections",
    "cmdorctrl+8": "switch accounts and collections",
    "cmdorctrl+9": "switch accounts and collections",
    "cmd+[": "go back",
    "cmd+]": "go forward",
    "alt+left": "go back",
    "alt+right": "go forward",
    down: "focus next row (mac)",
    up: "focus previous row (mac)",
    right: "focus right section (mac)",
    left: "focus left section (mac)",
    enter:
      "activate focused element (mac) / copy the selected detail. perform the default action for the selected (windows)",
    space: "activate focused element / expand item overview banners (mac)",
    "cmdorctrl+c": "copy the username or primary field of the selected",
    "shift+cmdorctrl+c": "copy the password of the selected",
    "alt+cmdorctrl+c": "copy the one-time password of the selected",
    "cmdorctrl+o": "open the selected in a new window",
    "cmdorctrl+n": "create a new item",
    "cmdorctrl+e": "edit the selected",
    "cmdorctrl+s": "save changes to an item",
    "cmdorctrl+r": "reveal or conceal secure fields in the selected",
    alt: "temporarily reveal all secure fields in the selected (mac)",
    "ctrl+alt": "temporarily reveal all secure fields in the selected",
    delete: "move the selected(s) to the archive (mac)",
    "cmdorctrl+delete": "delete the selected(s)",
    "shift+cmdorctrl+d": "collapse or expand the sidebar",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+0": "revert to actual size",
    "cmd+m": "minimize the app to the dock (mac)",
    "cmd+w": "close the current window (mac)",
    "shift+cmdorctrl+x":
      "open or close the 1password pop-up in chrome, edge, brave, or safari",
    "cmd+.": "open or close the 1password pop-up in firefox (mac)",
    "cmdorctrl+d": "show the list of vaults",
    "cmdorctrl+down": "open or close the category menu (mac)",
    "cmd+enter":
      "copy the selected detail.perform the default action for the selected (mac)",
    "ctrl+shift+cmdorctrl+c": "copy the one-time password of the selected",
    "cmdorctrl+i": "create a new item",
    "cmdorctrl+g": "show the password generator",
  },
} as AppParams;

export default app;
