const app = {
  id: "acreom",
  name: "acreom",
  icon: "/app-icons/acreom.png",
  homepage: "https://acreom.com",
  description:
    "acreom is the integrated markdown knowledge base with tasks. A personal daily driver for dev workflows.",
  globals: {
    "cmdOrCtrl+shift+space": "open quick capture",
  },
  shortcuts: {
    "cmdOrCtrl+shift+a": "open my day tab",
    "cmdOrCtrl+shift+s": "open all pages tab",
    "cmdOrCtrl+shift+d": "open tasks tab",
    "cmdOrCtrl+shift+f": "open calendar tab",
    "cmdOrCtrl+shift+j": "open jira tab",
    "cmdOrCtrl+k": "open search",
    "cmdOrCtrl+shift+k": "open full search",
    "cmdOrCtrl+shift+l": "open xray",
    "cmdOrCtrl+,": "open settings",
    "cmdOrCtrl+/": "toggle sidebar",
    "alt+[": "back",
    "alt+]": "forward",
    "cmdOrCtrl+t": "new tab",
    "cmdOrCtrl+w": "close tab",
    "cmdOrCtrl+shift+]": "focus next tab",
    "ctrl+tab": "focus next tab",
    "cmdOrCtrl+shift+[": "focus previous tab",
    "ctrl+shift+tab": "focus previous tab",
    "CmdOrCtrl+1": "activate tab 1",
    "CmdOrCtrl+2": "activate tab 2",
    "CmdOrCtrl+3": "activate tab 3",
    "CmdOrCtrl+4": "activate tab 4",
    "CmdOrCtrl+5": "activate tab 5",
    "CmdOrCtrl+6": "activate tab 6",
    "CmdOrCtrl+7": "activate tab 7",
    "CmdOrCtrl+8": "activate tab 8",
    "CmdOrCtrl+9": "activate tab 9",
    "CmdOrCtrl+0": "activate tab 10",
    "alt+tab": "focus next tab group",
    "alt+shift+tab": "focus previous tab group",
    "CmdOrCtrl+N": "new page",
    "CmdOrCtrl+shift+N": "new folder",
    "alt+e": "new event",
    "alt+N": "new task",
    "shift+enter": "notification accept task",
    e: "edit task",
    x: "complete task",
    t: "schedule task for today",
    r: "schedule task for tomorrow",
    m: "schedule task for start of next week",
    d: "delete task",
    f: "focus task in context",
    "CmdOrCtrl+F": "find in page",
    "CmdOrCtrl+shift+I": "page info",
    "CmdOrCtrl+P": "share page",
    "alt+D": "convert selected text to document",
    "alt+T": "convert selected text to task",
  },
};

export { app };
