import { AppParams } from "~/types";

const app = {
  id: "acreom",
  name: "acreom",
  icon: "/app-icons/acreom.png",
  homepage: "https://acreom.com",
  description:
    "acreom is the personal knowledge base for developers. Capture notes, break down issues, track progress, and manage PRs in one lightweight interface.",
  globals: {
    "cmdOrCtrl+shift+space": "open quick capture",
  },
  shortcuts: {
    "cmdorctrl+alt+1": "activate view 1",
    "cmdorctrl+alt+2": "activate view 2",
    "cmdorctrl+alt+3": "activate view 3",
    "cmdorctrl+alt+4": "activate view 4",
    "cmdorctrl+alt+5": "activate view 5",
    "cmdorctrl+alt+6": "activate view 6",
    "cmdorctrl+alt+7": "activate view 7",
    "cmdorctrl+alt+8": "activate view 8",
    "cmdorctrl+alt+9": "activate view 9",
    "cmdorctrl+alt+0": "activate view 10",
    "cmdOrCtrl+shift+j": "open jira tab",
    "cmdOrCtrl+shift+g": "open github tab",
    "cmdOrCtrl+k": "open search",
    "cmdOrCtrl+shift+k": "open full search",
    "cmdOrCtrl+shift+l": "open xray",
    "cmdOrCtrl+,": "open settings",
    "cmdOrCtrl+/": "toggle sidebar",
    "alt+[": "back",
    "alt+]": "forward",
    "CmdOrCtrl+N": "new page",
    "CmdOrCtrl+shift+N": "new folder",
    "shift+enter": "notification accept",
    enter: "focus editor / navigate to task",
    escape: "unfocus editor",
    "CmdOrCtrl+F": "find in page",
    "CmdOrCtrl+shift+I": "page info",
    "CmdOrCtrl+P": "share page",
    "alt+D": "convert selected text to document",
    "alt+T": "convert selected text to task",
    t: "my day today / schedule task for today",
    "cmdorctrl+shift+i": "my day toggle timeline",
    right: "my day next day",
    left: "my day previous day",
    "cmdorctrl+shift+o": "my day toggle overdue",
    "cmdOrCtrl+t": "new tab",
    "cmdOrCtrl+w": "close tab",
    "cmdOrCtrl+shift+]": "focus next tab",
    "ctrl+tab": "focus next tab",
    "cmdOrCtrl+shift+[": "focus previous tab",
    "ctrl+shift+tab": "focus previous tab",
    "CmdOrCtrl+1": "activate tab 1",
    "CmdOrCtrl+2": "activate tab 2",
    "CmdOrCtrl+3": "activate tab 3",
    "CmdOrCtrl+4": "activate tab 4",
    "CmdOrCtrl+5": "activate tab 5",
    "CmdOrCtrl+6": "activate tab 6",
    "CmdOrCtrl+7": "activate tab 7",
    "CmdOrCtrl+8": "activate tab 8",
    "CmdOrCtrl+9": "activate tab 9",
    "CmdOrCtrl+0": "activate tab 10",
    "alt+tab": "focus next tab group",
    "alt+shift+tab": "focus previous tab group",
    e: "edit task",
    x: "complete task",
    r: "schedule task for tomorrow",
    m: "schedule task for start of next week",
    d: "delete task",
    f: "focus task in context",
  },
} as AppParams;

export default app;
