const app = {
  id: "adobe-lightroom",
  name: "Adobe Lightroom",
  icon: "/app-icons/adobe-lightroom.png",
  homepage: "https://www.mozilla.org/firefox",
  description:
    "Adobe Lightroom is a tool for editing photos. Its primary uses include importing, saving, viewing, organizing, tagging, editing, and sharing large numbers of digital images.",
  globals: {},
  shortcuts: {
    tab: "show/hide side panels",
    "shift+tab": "show/hide all panels",
    t: "show/hide toolbar",
    f5: "show/hide module picker",
    f6: "show/hide filmstrip",
    f7: "show/hide left panels",
    f8: "show/hide right panels",
    "cmdorctrl+shift+0": "open/close left panels, top to bottom",
    "cmdorctrl+shift+1": "open/close left panels, top to bottom",
    "cmdorctrl+shift+2": "open/close left panels, top to bottom",
    "cmdorctrl+shift+3": "open/close left panels, top to bottom",
    "cmdorctrl+shift+4": "open/close left panels, top to bottom",
    "cmdorctrl+shift+5": "open/close left panels, top to bottom",
    "cmdorctrl+0":
      "open/close right panels, library and develop modules, top to bottom",
    "cmdorctrl+1":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+2":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+3":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+4":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+5":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+6":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+7":
      "open/close right panels, library and develop modules, top to bottom / slideshow, print, and web modules, top to bottom",
    "cmdorctrl+8":
      "open/close right panels, library and develop modules, top to bottom",
    "cmdorctrl+9":
      "open/close right panels, library and develop modules, top to bottom",
    "cmdorctrl+alt+1": "go to library module",
    "cmdorctrl+alt+2": "go to develop module",
    "cmdorctrl+alt+3": "go to slideshow module",
    "cmdorctrl+alt+4": "go to print module",
    "cmdorctrl+alt+5": "go to web module",
    "cmdorctrl+alt+left": "go back",
    "cmdorctrl+alt+right": "go forward",
    "cmdorctrl+alt+up": "go back to previous module",
    f11: "open secondary window",
    "shift+g": "enter grid view",
    "shift+e": "enter normal loupe view",
    "cmdorctrl+shift+enter": "enter locked loupe view",
    "shift+c": "enter compare view",
    "shift+n": "enter survey view",
    "cmdorctrl+alt+shift+enter": "enter slideshow view",
    "shift+f11": "enter full-screen mode (requires second monitor)",
    "shift+\\": "show/hide filter bar",
    "cmdorctrl+shift+plus": "zoom in",
    "cmdorctrl+shift+minus": "zoom out",
    v: "convert to grayscale",
    "cmdorctrl+u": "auto tone",
    "cmdorctrl+shift+u": "auto white balance / show/hide dimensions",
    "cmdorctrl+e": "edit in photoshop / edit in photoshop",
    "cmdorctrl+shift+c": "copy develop settings",
    "cmdorctrl+shift+v": "paste develop settings",
    "cmdorctrl+alt+v": "paste settings from previous photo",
    "cmdorctrl+alt+shift+left": "copy after settings to before",
    "cmdorctrl+alt+shift+right": "copy before settings to after",
    "cmdorctrl+alt+shift+up": "swap before and after settings",
    up: "increase selected slider in small increments / make next photos select and candidate in compare view",
    down: "decrease selected slider in small increments / swap select and candidate photos in compare view",
    "shift+up": "increase selected slider in larger increments",
    "shift+down": "decrease selected slider in larger increments",
    ".": "cycle through basic panel settings (forward/backward)",
    ",": "cycle through basic panel settings (forward/backward)",
    "cmdorctrl+shift+r": "reset all settings",
    "cmdorctrl+shift+s": "sync settings",
    "cmdorctrl+alt+s":
      "sync settings bypassing synchronize settings dialog box",
    "cmdorctrl+alt+shift+a": "enable auto sync",
    "cmdorctrl+alt+shift+m": "match total exposures",
    w: "select white balance tool (from any module)",
    r: "select the crop tool (from any module)",
    a: "contrain aspect ratio when crop tool is selected",
    "shift+a": "crop to same aspect ratio as previous crop",
    o: "cycle crop grid overlay / show/hide local adjustment mask overlay",
    "shift+o":
      "cycle crop grid overlay orientation / cycle local adjustment mask overlay colors",
    x: "switch crop between portrait and landscape orientation / flag photo as a reject",
    "cmdorctrl+alt+r": "reset crop / refine photos",
    "shift+t":
      "select the guided upright tool / toggle brush between clone and heal modes when spot removal tool is selected / toggle mask between edit and brush modes when the graduated/radial filter is selected",
    q: "select the spot removal tool",
    k: "select the adjustment brush tool (from any module)",
    m: "select the graduated filter tool",
    "]": "increase brush size / increase rating by one star",
    "[": "decrease brush size / decrease rating by one star",
    "shift+]": "increase brush feathering / move down in stack",
    "shift+[": "decrease brush feathering / move up in stack",
    "/": "switch between local adjustment brush a and b / deselect active photo",
    h: "show/hide local adjustment pin",
    "cmdorctrl+alt+shift+t":
      "select targeted adjustment tool to apply a tone curve adjustment",
    "cmdorctrl+alt+shift+h":
      "select targeted adjustment tool to apply a hue adjustment / show/hide badges",
    "cmdorctrl+alt+shift+s":
      "select targeted adjustment tool to apply a saturation adjustment",
    "cmdorctrl+alt+shift+l":
      "select targeted adjustment tool to apply a luminance adjustment",
    "cmdorctrl+alt+shift+g":
      "select targeted adjustment tool to apply a grayscale mix adjustment",
    "cmdorctrl+alt+shift+n": "deselect targeted adjustment tool",
    j: "show clipping / cycle grid views",
    "cmdorctrl+]": "rotate photo right (clockwise)",
    "cmdorctrl+[": "rotate photo left (counterclockwise)",
    space:
      "switch from grid to loupe view / pause slide show / toggle between loupe and 1:1 zoom preview",
    z: "toggle between loupe and 1:1 zoom preview / toggle zoom view",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+enter":
      "play impromptu slide show / play impromptu slide show / play impromptu slide show",
    y: "view before and after left/right",
    "alt+y": "view before and after top/bottom",
    "shift+y": "view before and after in a split screen",
    "\\": "view before only / show/hide library filter bar",
    "cmdorctrl+n":
      "create a new snapshot / create a new collection in the library module / create a new slide show template / create a new print template / create a new web gallery template",
    "cmdorctrl+shift+n":
      "create a new preset / create a new folder in the library module / create a new slide show template folder / create a new print template folder / create a new web gallery template folder",
    "cmdorctrl+alt+n": "create a new preset folder",
    "cmdorctrl+j":
      "open develop view options / open library view options / export pdf slide show / export web gallery",
    e: "enter library loupe view / switch to loupe view",
    g: "enter library grid view / switch to grid view",
    c: "enter library compare view / switch to compare view",
    n: "enter library survey view / switch to survey view",
    d: "open selected photo in the develop module",
    l: "cycle forward through lights out modes",
    "shift+l":
      "cycle backward through lights out modes / toggle filters on/off",
    "cmdorctrl+shift+l": "toggle lights dim mode",
    f: "cycle screen modes",
    "cmdorctrl+shift+f": "switch between normal and full-screen, hide panels",
    "cmdorctrl+alt+f": "go to normal screen mode",
    i: "cycle info overlay",
    "cmdorctrl+i": "show/hide info overlay",
    "cmdorctrl+shift+i": "import photos from disk",
    "cmdorctrl+o": "open catalog",
    "cmdorctrl+,": "open preferences",
    "cmdorctrl+alt+,": "open catalog settings",
    "cmdorctrl+shift+t": "create new subfolder (segmented tethered capture)",
    "cmdorctrl+t": "hide/show tether capture bar",
    "cmdorctrl+'": "create virtual copy (library and develop module only)",
    "cmdorctrl+r":
      "show in explorer/finder (library and develop module only) / show/hide rulers / reload web gallery",
    right: "go to next photo in the filmstrip / go to next slide",
    left: "go to previous photo in the filmstrip / go to previous slide",
    f2: "rename photo (in library module)",
    delete: "delete selected photo(s)",
    "alt+backspace": "remove selected photo(s) from catalog",
    "cmdorctrl+alt+shift+backspace":
      "delete selected photo(s) and move to trash",
    "cmdorctrl+backspace": "delete rejected photo(s)",
    "cmdorctrl+alt+e": "open in other editor",
    "cmdorctrl+shift+e": "export selected photo(s)",
    "cmdorctrl+alt+shift+e": "export with previous settings",
    "cmdorctrl+alt+shift+,": "open plug-in manager",
    "cmdorctrl+p": "print selected photo / print",
    "cmdorctrl+shift+p": "open page setup dialog box",
    enter: "switch to loupe view / play slide show",
    esc: "switch to grid view / end slide show",
    pgup: "scroll up zoomed photo in loupe view / scroll up grid thumbnails",
    pgdown:
      "scroll down zoomed photo in loupe view / scroll down grid thumbnails",
    home: "go to beginning of grid view",
    end: "go to end of grid view",
    "=": "increase grid thumbnail size",
    "-": "decreate grid thumbnail size",
    "cmdorctrl+shift+h": "toggle cell extras / show/hide guides",
    "cmdorctrl+a": "select all photos",
    "cmdorctrl+d": "deselect all photos",
    "cmdorctrl+shift+d": "select only active photo",
    "shift+left": "add previous photo to selection",
    "shift+right": "add next photo to selection",
    "cmdorctrl+alt+a": "select flagged photos",
    "cmdorctrl+alt+shift+d": "deselect unflagged photos",
    "cmdorctrl+g": "group into stack",
    "cmdorctrl+shift+g": "unstack",
    s: "toggle stack",
    "shift+s": "move to top of stack",
    "1": "set star rating",
    "2": "set star rating",
    "3": "set star rating",
    "4": "set star rating",
    "5": "set star rating",
    "shift+1": "set star rating and go to next photo",
    "shift+2": "set star rating and go to next photo",
    "shift+3": "set star rating and go to next photo",
    "shift+4": "set star rating and go to next photo",
    "shift+5": "set star rating and go to next photo",
    "0": "remove star rating",
    "shift+0": "remove star rating and go to next photo",
    "6": "assign a red label",
    "7": "assign a yellow label",
    "8": "assign a green label",
    "9": "assign a blue label",
    "shift+6": "assign a color label and go to next photo",
    "shift+7": "assign a color label and go to next photo",
    "shift+8": "assign a color label and go to next photo",
    "shift+9": "assign a color label and go to next photo",
    p: "flag photo as a pick",
    "shift+p": "flag photo as a pick and go to next photo",
    "shift+x": "flag photo as a reject and go to next photo",
    u: "unflag photo",
    "shift+u": "unflag photo and go to next photo",
    "cmdorctrl+up": "increase flag status",
    "cmdorctrl+down": "decrease flag status",
    "`": "cycle flag settings",
    "cmdorctrl+f": "find photo in the library module",
    b: "add to quick collection",
    "shift+b": "add to quick collection and go to next photo",
    "cmdorctrl+b": "show quick collection",
    "cmdorctrl+alt+b": "save quick collection",
    "cmdorctrl+shift+b": "clear quick collection",
    "cmdorctrl+alt+shift+b": "set as target collection",
    "cmdorctrl+k": "add keywords",
    "cmdorctrl+shift+k": "edit keywords / show/hide image cells",
    "cmdorctrl+alt+shift+k": "set a keyword shortcut",
    "shift+k": "add/remove keyword shortcut from selected photo",
    "cmdorctrl+alt+k": "enable painting",
    "alt+1": "add a keyword from a keyword set to selected photo",
    "alt+2": "add a keyword from a keyword set to selected photo",
    "alt+3": "add a keyword from a keyword set to selected photo",
    "alt+4": "add a keyword from a keyword set to selected photo",
    "alt+5": "add a keyword from a keyword set to selected photo",
    "alt+6": "add a keyword from a keyword set to selected photo",
    "alt+7": "add a keyword from a keyword set to selected photo",
    "alt+8": "add a keyword from a keyword set to selected photo",
    "alt+9": "add a keyword from a keyword set to selected photo",
    "alt+0": "cycle forward through keyword sets",
    "alt+shift+0": "cycle backward through keyword sets",
    "cmdorctrl+alt+shift+c": "copy metadata",
    "cmdorctrl+alt+shift+v": "paste metadata",
    "cmdorctrl+s":
      "save metadata to file / save slide show settings / save print settings / save web gallery settings",
    "alt+enter": "preview slide show",
    "cmdorctrl+shift+j": "export jpeg slide show / show/hide page bleed",
    "cmdorctrl+alt+j": "export video slide show",
    "cmdorctrl+alt+p": "print one copy / preview in browser",
    "cmdorctrl+alt+shift+p": "open print settings dialog box",
    "cmdorctrl+shift+left": "go to first page",
    "cmdorctrl+shift+right": "go to last page",
    "cmdorctrl+left": "go to previous page",
    "cmdorctrl+right": "go to next page",
    "cmdorctrl+shift+m": "show/hide margins and gutters",
    "cmdorctrl+/": "display current module shortcuts",
    "cmdorctrl+alt+/": "go to current module help",
    f1: "open community help",
  },
};

export default app;
