import { AppParams } from "~/types";

const app = {
  id: "affinity-designer",
  name: "Affinity Designer",
  icon: "/app-icons/affinity-designer.png",
  homepage: "https://affinity.serif.com/en-us/designer/",
  description: "Affinity Designer is a vector graphics editor.",
  globals: {},
  shortcuts: {
    esc: "cancel operation",
    f1: "help",
    "0": "change opacity",
    "1": "change opacity",
    "2": "change opacity",
    "3": "change opacity",
    "4": "change opacity",
    "5": "change opacity",
    "6": "change opacity",
    "7": "change opacity",
    "8": "change opacity",
    "9": "change opacity",
    tab: "toggle UI",
    t: "cycle text tools",
    y: "transparency tool",
    i: "color picker tool",
    p: "pen tool",
    "[": "decrease brush size",
    "]": "increase brush size",
    a: "node tool",
    f: "point transform tool",
    g: "fill tool",
    h: "view tool",
    ";": "toggle snapping",
    "\\": "clip to canvas",
    z: "zoom tool",
    x: "toggle active selector",
    c: "corner tool",
    v: "move tool",
    b: "vector brush tool / cycle brush or pixel tools (pixel persona)",
    n: "pencil tool",
    m: "cycle shape tool / cycle marquees (pixel persona)",
    ",": "cycle split view",
    ".": "reset selection box",
    "/": "set fill or stroke to none",
    "cmdorctrl+1": "zoom to 100%",
    "cmdorctrl+2": "zoom to 200%",
    "cmdorctrl+3": "zoom to 400%",
    "cmdorctrl+4": "zoom to 800%",
    "cmdorctrl+8": "zoom to actual size",
    "cmdorctrl+9": "zoom to pixel size",
    "cmdorctrl+0": "zoom to fit",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+tab": "switch view",
    "cmdorctrl+w": "close",
    "cmdorctrl+r": "rulers",
    "cmdorctrl+t": "character / character panel (advanced text)",
    "cmdorctrl+y": "redo",
    "cmdorctrl+o": "open",
    "cmdorctrl+p": "print",
    "cmdorctrl+[": "back one",
    "cmdorctrl+]": "forward one",
    "cmdorctrl+enter": "convert to curves",
    "cmdorctrl+a": "select all",
    "cmdorctrl+s": "save",
    "cmdorctrl+g": "group",
    "cmdorctrl+j": "duplicate",
    "cmdorctrl+l": "lock",
    "cmdorctrl+;": "show guides",
    "cmdorctrl+'": "show grid",
    "cmdorctrl+z": "undo",
    "cmdorctrl+x": "cut",
    "cmdorctrl+c": "copy",
    "cmdorctrl+v": "paste",
    "cmdorctrl+n": "new",
    "cmdorctrl+m": "curves",
    "cmdorctrl+,": "preferences",
    space: "hold for view tool",
    w: "selection brush (pixel persona)",
    e: "erase brush (pixel persona)",
    o: "cycle dodge or burn brushes (pixel persona)",
    l: "freehand selection tool (pixel persona)",
    "cmdorctrl+shift+t": "typography dialog (advanced text)",
    "cmdorctrl+b": "bold (advanced text)",
    "cmdorctrl+i": "italic (advanced text)",
    "cmdorctrl+u": "underline (advanced text)",
    "cmdorctrl+alt+l": "align left (advanced text)",
    "cmdorctrl+alt+c": "align center (advanced text)",
    "cmdorctrl+alt+r": "align right (advanced text)",
    "alt+shift+left": "tighten spacing more (advanced text)",
    "alt+shift+right": "loosen spacing more (advanced text)",
    "cmdorctrl+alt+shift+up": "precise raise baseline (advanced text)",
    "cmdorctrl+alt+shift+down": "precise lower baseline (advanced text)",
    "cmdorctrl+alt+down": "precise increase leading (advanced text)",
    "cmdorctrl+alt+up": "precise decrease leading (advanced text)",
  },
} as AppParams;

export default app;
