const app = {
  id: "androidstudio",
  name: "Android Studio",
  icon: "/app-icons/android-studio.png",
  homepage: "https://developer.android.com/studio",
  description:
    "Android Studio is the official integrated development environment for Google's Android operating system, built on JetBrains' IntelliJ IDEA software and designed specifically for Android development.",
  globals: {},
  shortcuts: {
    "cmdorctrl+s": "save all",
    "cmdorctrl+alt+y": "synchronize",
    "cmdorctrl+shift+f12": "minimize or maximize the editor",
    "alt+shift+f": "add to favorites",
    "alt+shift+i": "inspect the current file with the current profile",
    "cmdorctrl+`": "quick switch the scheme",
    "cmdorctrl+alt+s": "open the settings dialogue",
    "cmdorctrl+alt+shift+s": "open the project structure dialogue",
    "cmdorctrl+tab": "switch between the tabs and tool window",
    "shift+shift": "search everything, including code and menus",
    "cmdorctrl+f": "find",
    f3: "find next",
    "shift+f3": "find previous",
    "cmdorctrl+r": "replace",
    "cmdorctrl+shift+a": "find action",
    "cmdorctrl+alt+shift+n": "search by a symbol name",
    "cmdorctrl+n": "find class",
    "cmdorctrl+shift+n": "find file, instead of class",
    "cmdorctrl+shift+f": "find in path",
    "cmdorctrl+f12": "open file structure pop-up",
    "alt+right": "navigate between open editor tabs",
    "alt+left": "navigate between open editor tabs",
    "cmdorctrl+enter": "jump to source / smart line split",
    "shift+f4": "open the current editor tab in a new window",
    "cmdorctrl+e": "recently opened files pop-up",
    "cmdorctrl+shift+e": "recently edited files pop-up",
    "cmdorctrl+shift+backspace": "go to last edit location",
    "cmdorctrl+f4": "close active editor tab",
    esc: "return to editor window from a tool window",
    "shift+esc": "hide active or last active tool window",
    "cmdorctrl+g": "go to line / group into a nested graph",
    "cmdorctrl+h": "open type hierarchy",
    "cmdorctrl+shift+h": "open method hierarchy",
    "cmdorctrl+alt+h": "open call hierarchy",
    "alt+ins": "generate code, e.g. getters, setters, constructors, new class",
    "cmdorctrl+o": "override methods",
    "cmdorctrl+i": "implement methods",
    "cmdorctrl+alt+t": "surround with if...else, try...catch, etc",
    "cmdorctrl+y": "delete line at caret",
    "cmdorctrl+minus": "collapse the current code block / zoom out",
    "cmdorctrl+plus": "expand the current code block / zoom in",
    "cmdorctrl+shift+minus": "collapse all code blocks",
    "cmdorctrl+shift+plus": "expand all code blocks",
    "cmdorctrl+d": "duplicate the current line or selection",
    "cmdorctrl+space": "basic code completion",
    "cmdorctrl+shift+space":
      "smart code completion, filters the list of methods and variables by expected type",
    "cmdorctrl+shift+enter": "complete statement",
    "cmdorctrl+q": "quick documentation lookup",
    "cmdorctrl+p": "show parameters for selected method",
    "cmdorctrl+b": "go to declaration, directly / go to xml",
    "cmdorctrl+alt+b": "go to implementations",
    "cmdorctrl+u": "go to super-method or super-class",
    "cmdorctrl+shift+i": "open quick definition lookup",
    "alt+1": "toggle project tool window visibility",
    f11: "toggle bookmark",
    "cmdorctrl+f11": "toggle bookmark with mnemonic",
    "cmdorctrl+/": "comment or uncomment with line comment",
    "cmdorctrl+shift+/": "comment or uncomment with block comment",
    "cmdorctrl+w": "select successively increasing code blocks",
    "cmdorctrl+shift+w": "decrease current selection to previous state",
    "cmdorctrl+[": "move to code block start",
    "cmdorctrl+]": "move to code block end",
    "cmdorctrl+shift+[": "select to the code block start",
    "cmdorctrl+shift+]": "select to the code block end",
    "cmdorctrl+delete": "delete to the end of a word",
    "cmdorctrl+backspace": "delete to the start of a word",
    "cmdorctrl+alt+o": "optimize imports",
    "alt+enter": "project quick fix, show intention actions and quick fixes",
    "cmdorctrl+alt+l": "reformat code",
    "cmdorctrl+alt+i": "auto-indent lines",
    tab: "indent lines / cycle through destinations",
    "shift+tab": "unindent lines",
    "cmdorctrl+shift+j": "smart line join",
    "shift+enter": "start new line",
    f2: "next highlighted error",
    "shift+f2": "previous highlighted error",
    "cmdorctrl+0": "fit to screen",
    "cmdorctrl+shift+1": "actual size",
    b: "toggle between design and blueprint modes",
    o: "toggle between portrait and landscape modes",
    d: "toggle devices",
    r: "force refresh",
    e: "toggle render errors panel",
    delete: "delete constraints",
    "cmdorctrl+a": "select all components / select all destinations",
    "cmdorctrl+f9": "build",
    "shift+f10": "build and run",
    "cmdorctrl+f10": "apply changes and restart activity",
    "cmdorctrl+alt+f10": "apply code changes",
    "shift+f9": "debug",
    f8: "step over",
    f7: "step into",
    "shift+f7": "smart step into",
    "shift+f8": "step out",
    "alt+f9": "run to cursor",
    "alt+f8": "evaluate expression",
    f9: "resume program",
    "cmdorctrl+f8": "toggle breakpoint",
    "cmdorctrl+shift+f8": "view breakpoints",
    f5: "copy",
    f6: "move",
    "alt+delete": "safe delete",
    "shift+f6": "rename",
    "cmdorctrl+f6": "change signature",
    "cmdorctrl+alt+n": "inline",
    "cmdorctrl+alt+m": "extract method",
    "cmdorctrl+alt+v": "extract variable",
    "cmdorctrl+alt+f": "extract field",
    "cmdorctrl+alt+c": "extract constant",
    "cmdorctrl+alt+p": "extract parameter",
    "cmdorctrl+k": "commit project to vcs",
    "cmdorctrl+t": "update project from vcs",
    "alt+shift+c": "view recent changes",
    "alt+`": "open vcs pop-up",
  },
};

export default app;
