const app = {
  id: "apple-music",
  name: "Apple Music",
  icon: "/app-icons/apple-music.png",
  homepage: "https://www.apple.com/apple-music/",
  description:
    "Apple Music is a music, audio and video streaming service developed by Apple.",
  globals: {},
  shortcuts: {
    space: "start playing or pause the selected song",
    enter: "play the currently selected song from the beginning",
    "cmdorctrl+alt+right": "move forward within a song",
    "cmdorctrl+alt+left": "move backward within a song",
    "cmdorctrl+.": "stop playing the selected song",
    right: "when a song is playing, play the next song in a list",
    left: "when a song is playing, play the previous song in a list",
    "cmdorctrl+l": "show the currently playing song in the list",
    "cmdorctrl+alt+u": "show the Playing Next queue",
    "alt+right": "listen to the next album in a list",
    "alt+left": "listen to the previous album in a list",
    "cmdorctrl+up": "increase the volume",
    "cmdorctrl+down": "decrease the volume",
    "cmdorctrl+alt+e": "open the equalizer",
    "cmdorctrl+shift+right": "go to the next chapter, if available",
    "cmdorctrl+shift+left": "go to the previous chapter, if available",
    "cmdorctrl+u": "stream audio file at a specific URL to Music",
    "cmdorctrl+n": "create a new playlist",
    "cmdorctrl+shift+n": "create a playlist from a selection of songs",
    "cmdorctrl+alt+n": "create a new Smart Playlist",
    "alt+space": "start the Genius Shuffle",
    "cmdorctrl+r": "refresh a Genius Playlist, when the playlist is selected",
    "cmdorctrl+delete": "delete the selected playlist without confirmation",
    "alt+delete":
      "delete the selected playlist and all songs it contains from your library",
    "cmdorctrl+shift+m": "open the MiniPlayer",
    "cmdorctrl+shift+f": "open the Full Screen Player",
    "cmdorctrl+ctrl+f": "toggle full-screen view",
    "cmdorctrl+/": "show or hide the status bar",
    "cmdorctrl+i": "open the info window for the selected song",
    "cmdorctrl+p": "in the info window, see information for the previous song",
    "cmdorctrl+shift+[": "go to the previous pane in the info window",
    "cmdorctrl+shift+]": "go to the next pane in the info window",
    "cmdorctrl+j": "open the View Options window for the selected source",
    "cmdorctrl+t": "turn the visualizer on or off",
    "?": "see more options when a visual effect is showing",
    "cmdorctrl+0": "open the Music window",
    "cmdorctrl+w": "close the Music window",
    "cmdorctrl+m": "put the Music window in the Dock",
    "cmdorctrl+h": "hide the Music window",
    "cmdorctrl+alt+h": "hide all other applications",
    "cmdorctrl+o": "add a file to your library",
    "cmdorctrl+shift+r": "show where a song file is located",
    "cmdorctrl+f": "select the search field",
    "cmdorctrl+z": "undo your last typing change while editing an item",
    "cmdorctrl+x": "cut the selected song's information or artwork",
    "cmdorctrl+c": "copy the selected song's information or artwork",
    "cmdorctrl+v": "paste the selected song's information or artwork",
    "cmdorctrl+a": "select all the songs in the list",
    "cmdorctrl+b": "show or hide the column browser",
    "cmdorctrl+shift+a": "de-select all the songs in the list",
    "alt+enter": "initiate a search in the iTunes Store",
    "cmdorctrl+]": "go to the next page in the iTunes Store",
    "cmdorctrl+[": "go to the previous page in the iTunes Store",
    "cmdorctrl+,": "open Music Preferences",
    "cmdorctrl+q": "quit the Music app",
    "cmdorctrl+e": "eject a CD",
    "cmdorctrl+?": "open the Music Help menu",
    "cmdorctrl+alt": "open a different music library, while opening Music",
  },
};

export default app;
