const app = {
  id: "audacity",
  name: "Audacity",
  icon: "/app-icons/audacity.png",
  homepage: "https://www.audacityteam.org/",
  description:
    "Audacity is a free and open-source digital audio editor and recording application software, licensed under GPL-2.0-or-later.",
  globals: {},
  shortcuts: {
    "cmdorctrl+n": "new",
    "cmdorctrl+o": "open",
    "cmdorctrl+w": "close",
    "cmdorctrl+q": "exit",
    "cmdorctrl+s": "save project",
    "cmdorctrl+shift+e": "export audio",
    "cmdorctrl+shift+l": "export multiple",
    "cmdorctrl+shift+i": "import audio",
    "cmdorctrl+z": "undo",
    "cmdorctrl+y": "redo",
    "cmdorctrl+x": "cut",
    "cmdorctrl+k": "delete",
    "cmdorctrl+c": "copy",
    "cmdorctrl+v": "paste",
    "cmdorctrl+d": "duplicate",
    "cmdorctrl+p": "preferences",
    "cmdorctrl+alt+x": "split cut",
    "cmdorctrl+alt+k": "split delete",
    "cmdorctrl+l": "silence audio",
    "cmdorctrl+t": "trim audio",
    "cmdorctrl+alt+i": "split new",
    "cmdorctrl+j": "join",
    "cmdorctrl+shift+j": "detach at silences",
    "cmdorctrl+b": "add label at selection",
    "cmdorctrl+m": "add label at playback position",
    "cmdorctrl+alt+v": "paste text to new label",
    "alt+x": "cut labeled audio",
    "alt+k": "delete labeled audio",
    "alt+shift+x": "split cut labeled audio",
    "alt+shift+k": "split delete labeled audio",
    "alt+l": "silence labeled audio",
    "alt+shift+c": "copy labeled audio",
    "alt+i": "split labeled audio",
    "alt+j": "join labeled audio",
    "alt+shift+j": "detach labeled audio at silences",
    f11: "toggle full screen",
    "1": "play one second",
    b: "play to selection",
    "shift+f5": "play before selection start",
    "shift+f6": "play after selection start",
    "shift+f7": "play before selection end",
    "shift+f8": "play after selection end",
    "cmdorctrl+shift+f5": "play before and after selection start",
    "cmdorctrl+shift+f7": "play before and after selection end",
    c: "play cut preview",
    f1: "selection tool",
    f2: "envelope tool",
    f3: "draw tool",
    f4: "zoom tool",
    f5: "time shift tool",
    f6: "multi tool",
    a: "previous tool",
    d: "next tool",
    backspace: "delete",
    "alt+left": "move to previous label",
    "alt+right": "move to next label",
    left: "cursor left / short seek left during playback",
    right: "cursor right / short seek right during playback",
    "shift+left": "selection extend left / long seek left during playback",
    "shift+right": "selection extend right / long seek right during playback",
    "shift+i": "change recording device",
    "shift+o": "change playback device",
    "shift+h": "change audio host",
    "shift+n": "change recording channels",
    "shift+home": "selection to start",
    "shift+end": "selection to end",
    "cmdorctrl+shift+right": "selection contract left",
    "cmdorctrl+shift+left": "selection contract right",
    "cmdorctrl+shift+f6": "move backwards from toolbars to tracks",
    "cmdorctrl+f6": "move forward from toolbars to tracks",
    up: "move focus to previous track",
    down: "move focus to next track",
    "cmdorctrl+home": "move focus to first track",
    "cmdorctrl+end": "move focus to last track",
    "shift+up": "move focus to previous and select",
    "shift+down": "move focus to next and select",
    enter: "toggle focused track",
    ",": "cursor short jump left",
    ".": "cursor short jump right",
    "shift+,": "cursor long jump left",
    "shift+.": "cursor long jump right",
    "shift+p": "change pan on focused track",
    "alt+shift+left": "pan left on focused track",
    "alt+shift+right": "pan right on focused track",
    "shift+g": "change gain on focused track",
    "alt+shift+up": "increase gain on focused track",
    "alt+shift+down": "decrease gain on focused track",
    "shift+u": "mute or unmute focused track",
    "shift+s": "solo or unsolo focused track",
    "shift+c": "close focused track",
    "cmdorctrl+a": "select all",
    "cmdorctrl+shift+a": "select none",
    z: "select at zero crossings",
    "cmdorctrl+shift+k": "select in all tracks",
    "cmdorctrl+shift+y": "select in all sync-locked tracks",
    "[": "left at playback position",
    "]": "right at playback position",
    "shift+j": "track start to cursor",
    "shift+k": "cursor to track end",
    q: "toggle spectral selection",
    "cmdorctrl+alt+p": "previous clip",
    "cmdorctrl+alt+n": "next clip",
    "cmdorctrl+1": "zoom in",
    "cmdorctrl+2": "zoom normal",
    "cmdorctrl+3": "zoom out",
    "cmdorctrl+e": "zoom to selection",
    "shift+z": "zoom toggle",
    "cmdorctrl+f": "fit to width",
    "cmdorctrl+shift+f": "fit to height",
    "cmdorctrl+shift+c": "collapse all tracks",
    "cmdorctrl+shift+x": "expand collapsed tracks",
    "cmdorctrl+[": "skip to selection start",
    "cmdorctrl+]": "skip to selection end",
    space: "play or stop",
    x: "play or stop and set cursor",
    "shift+space": "loop play",
    p: "pause",
    r: "record",
    "shift+r": "record new track",
    "shift+t": "timer record",
    "shift+d": "punch and roll record",
    j: "cursor to track start",
    k: "cursor to track end",
    home: "cursor to project start",
    end: "cursor to project end",
    "cmdorctrl+shift+n": "add new mono track",
    "cmdorctrl+shift+m": "mix and render to new track",
    "cmdorctrl+u": "mute all tracks",
    "cmdorctrl+shift+u": "unmute all tracks",
    "cmdorctrl+r": "repeat last effect",
  },
};

export default app;
