import { AppParams } from "~/types";

const app = {
  id: "bitbucket",
  name: "Bitbucket",
  icon: "/app-icons/bitbucket.png",
  homepage: "https://bitbucket.org/",
  description:
    "Bitbucket Cloud is a Git based code hosting and collaboration tool.",
  globals: {},
  shortcuts: {
    "?": "display keyboard shortcuts",
    "[": "expand and collapse left navigation",
    "/": "focus the site search",
    ".": "open the omnibar",
    j: "select next item",
    k: "select previous item",
    enter: "view selected item",
    "g+d": "go to your work dashboard",
    "g+a": "go to your personal settings",
    esc: "dismiss dialog or remove focus",
    u: "go back",
    "c+r": "create a repository",
    "i+r": "import a repository",
    "r+s": "open repository source",
    "r+c": "open repository commits",
    "r+b": "open repository branches",
    "r+p": "open repository pull requests",
    "r+i": "open repository issues",
    "r+w": "open repository wiki",
    "r+d": "open repository downloads",
    "r+a": "open repository settings",
    f: "search for file / focus the file filter",
    "x+f": "fork repository",
    "x+b": "create branch",
    "x+c": "compare branches or tags",
    "x+p": "create pull request",
    "x+i": "create issue",
    "cmdorctrl+enter": "submit a comment",
    "t+c": "toggle display of inline comments",
    "p+d": "switch to the pull request diff tab",
    "p+c": "switch to the pull request commits tab",
    "p+a": "switch to the pull request activity tab",
    "shift+t": "show the list of tasks",
    "]": "expand and collapse right sidebar",
  },
} as AppParams;

export default app;
