const app = {
  id: "brave",
  name: "Brave",
  icon: "/app-icons/brave.png",
  homepage: "https://brave.com/",
  description:
    "Brave is a free and open-source web browser based on the Chromium web browser and its Blink engine.",
  globals: {},
  shortcuts: {
    "cmdorctrl+n": "open a new window",
    "cmdorctrl+shift+n": "open a new window in private mode",
    "cmdorctrl+t": "open a new tab, and jump to it",
    "cmdorctrl+shift+t": "reopen the last closed tab, and jump to it",
    "cmdorctrl+tab": "jump to the next open tab",
    "cmdorctrl+shift+tab": "jump to the previous open tab",
    "cmdorctrl+1": "jump to tab 1",
    "cmdorctrl+2": "jump to tab 2",
    "cmdorctrl+3": "jump to tab 3",
    "cmdorctrl+4": "jump to tab 4",
    "cmdorctrl+5": "jump to tab 5",
    "cmdorctrl+6": "jump to tab 6",
    "cmdorctrl+7": "jump to tab 7",
    "cmdorctrl+8": "jump to tab 8",
    "cmdorctrl+9": "jump to the last tab",
    "alt+home": "open your home page in the current tab",
    "cmdorctrl+left":
      "open the previous page from your browsing history in the current tab",
    "alt+right":
      "open the next page from your browsing history in the current tab",
    "cmdorctrl+w": "close the current tab",
    "cmdorctrl+shift+w": "close the current window",
    "alt+space+n": "minimize the current window",
    "alt+space+x": "maximize the current window",
    "alt+f4": "close the current window",
    "cmdorctrl+shift+q": "quit brave",
    "alt+f": "open the main menu",
    "cmdorctrl+shift+b": "show or hide the bookmarks bar",
    "cmdorctrl+h": "open the history page in a new tab",
    "cmdorctrl+j": "open the downloads page in a new tab",
    "shift+esc": "open the brave task manager",
    "shift+alt+t": "set focus on the first item in the toolbar",
    f10: "set focus on the last item in the toolbar",
    f6: "switch focus to unfocused dialog, if showing",
    "cmdorctrl+f": "open the find bar to search the current page",
    "cmdorctrl+g": "jump to the next match in your find bar search",
    "cmdorctrl+shift+g": "jump to the previous match in your find bar search",
    "cmdorctrl+shift+j": "open developer tools",
    "cmdorctrl+shift+delete": "open the clear browser data options",
    f1: "open the brave help center in a new tab",
    "cmdorctrl+shift+m": "open profile menu",
    enter: "search with your default search engine (after typing)",
    tab: "search using a different search engine (after typing) / browse clickable items moving forward",
    "cmdorctrl+enter":
      "add www. and .com to a site name, and open it in the current tab (after typing)",
    "alt+enter": "open a new tab and perform a search (after typing)",
    "cmdorctrl+l": "jump to the address bar",
    "cmdorctrl+k": "search from anywhere on the page",
    "shift+delete":
      "remove predictions from your address bar (after highlighting them)",
    "cmdorctrl+p": "open options to print the current page",
    "cmdorctrl+s": "open options to save the current page",
    "cmdorctrl+r": "reload the current page",
    "cmdorctrl+shift+r": "reload the current page, ignoring cached content",
    esc: "stop the page loading",
    "shift+tab": "browse clickable items moving backwards",
    "cmdorctrl+o": "open a file from your computer in brave",
    "cmdorctrl+u": "display non-editable html source code for the current page",
    "cmdorctrl+d": "save your current webpage as a bookmark",
    "cmdorctrl+shift+d": "save all open tabs as bookmarks in a new folder",
    f11: "turn full-screen mode on or off",
    "cmdorctrl+plus": "make everything on the page bigger",
    "cmdorctrl+minus": "make everything on the page smaller",
    "cmdorctrl+0": "return everything on the page to default size",
    space: "scroll down a webpage, a screen at a time",
    "shift+space": "scroll up a webpage, a screen at a time",
    home: "go to the top of the page",
    end: "go to the bottom of the page",
    "alt+left":
      "move your cursor to the front of the previous word in a text field",
    "cmdorctrl+right":
      "move your cursor to the back of the next word in a text field",
  },
} as AppParams;

export default app;
