import { AppParams } from "~/types";

const app = {
  id: "discord",
  name: "Discord",
  icon: "/app-icons/discord.png",
  homepage: "https://discord.com/",
  description:
    'Discord is an instant messaging and VoIP social platform which allows communication through voice calls, video calls, text messaging, and media and files. Communication can be private or take place in virtual communities called "servers".',
  globals: {},
  shortcuts: {
    "cmdorctrl+/": "view all discord keyboard shortcuts",
    "cmdorctrl+k": "search for servers, channels, or dms",
    "cmdorctrl+shift+n": "create or join a server",
    "cmdorctrl+f": "search within servers, channels, or dms",
    "cmdorctrl+shift+h": "open help",
    "cmdorctrl+shift+u": "upload a file",
    pgup: "scroll chat up",
    pgdown: "scroll chat down",
    "shift+pgup": "go to the oldest unread message",
    "cmdorctrl+alt+up": "jump between servers",
    "cmdorctrl+alt+down": "jump between servers",
    "alt+up": "jump between channels",
    "alt+down": "jump between channels",
    "cmdorctrl+b": "go back to the previous text channel",
    "cmdorctrl+alt+a": "go back to the active audio channel",
    "alt+left": "go to the next/previous screen",
    "alt+right": "go to the next/previous screen",
    "alt+shift+up": "jump between unread channels",
    "alt+shift+down": "jump between unread channels",
    "cmdorctrl+shift+alt+up": "jump between unread channels with mentions",
    "cmdorctrl+shift+alt+down": "jump between unread channels with mentions",
    "cmdorctrl+shift+alt+v": "go to an ongoing current call",
    "cmdorctrl+alt+right": "switch between the last server and dms",
    e: "edit a message",
    backspace: "delete a message",
    r: "reply to a message",
    p: "pin a message",
    plus: "react to a message",
    "cmdorctrl+c": "copy a message",
    "alt+enter": "mark a message as unread",
    "shift+esc": "mark server as read",
    tab: "focus text area",
    "cmdorctrl+shift+e": "mark top inbox channel as read",
    esc: "mark a channel as read / decline an incoming call",
    "cmdorctrl+u": "view channel members list",
    "cmdorctrl+e": "open emojis",
    "cmdorctrl+shift+t": "make a private group",
    "cmdorctrl+i": "open inbox",
    "cmdorctrl+p": "view pinned messages",
    "cmdorctrl+g": "open gifs",
    "cmdorctrl+shift+m": "mute",
    "cmdorctrl+shift+d": "deafen",
    "cmdorctrl+'": "create a new call",
    "cmdorctrl+enter": "answer incoming call",
  },
} as AppParams;

export default app;
