import { AppParams } from "~/types";

const app = {
  id: "figma",
  name: "Figma",
  icon: "/app-icons/figma.png",
  homepage: "https://www.figma.com/",
  description:
    "Figma is a vector graphics editor and prototyping tool which is primarily web-based, with additional offline features enabled by desktop applications.",
  globals: {},
  shortcuts: {
    "cmdorctrl+\\": "show/hide ui",
    "cmdorctrl+c": "pick color / copy",
    "cmdorctrl+/": "search menu",
    v: "move tool",
    f: "frame tool",
    p: "pen tool",
    "shift+p": "pencil tool",
    t: "text tool",
    r: "rectangle tool",
    o: "ellipse tool",
    l: "line tool",
    "shift+l": "arrow tool",
    c: "add/show comments",
    s: "slice tool",
    "shift+r": "toggle rulers",
    "cmdorctrl+y": "show outlines",
    "cmdorctrl+p": "pixel preview",
    "cmdorctrl+g": "layout grids / group selection",
    "cmdorctrl+'": "pixel grid",
    "cmdorctrl+alt+\\": "show multiplayer cursors",
    "alt+1": "show layers",
    "alt+2": "show components",
    "alt+3": "show team library",
    plus: "zoom in",
    minus: "zoom out",
    "shift+0": "zoom to 100%",
    "shift+1": "zoom to fit",
    "shift+2": "zoom to selection",
    "shift+n": "zoom to previous frame",
    n: "zoom to next frame",
    pgup: "previous page",
    pgdown: "next page",
    home: "find previous frame",
    end: "find next frame",
    "cmdorctrl+b": "bold",
    "cmdorctrl+i": "italic",
    "cmdorctrl+u": "underline",
    "cmdorctrl+shift+v": "paste and match style / paste over selection",
    "cmdorctrl+alt+l": "text alight left",
    "cmdorctrl+alt+t": "text align center / tidy up",
    "cmdorctrl+alt+r": "text align right",
    "cmdorctrl+alt+j": "text align justified",
    "cmdorctrl+shift+</>": "adjust font size",
    "alt+,": "adjust letter spacing",
    "alt+.": "adjust letter spacing",
    "alt+shift+>": "adjust line height",
    "alt+shift+<": "adjust line height",
    b: "paint bucket (while editing shape)",
    "alt+/": "remove fill",
    "/": "remove stroke",
    "shift+x": "swap fill and stroke",
    "cmdorctrl+shift+o": "outline stroke / team library",
    "cmdorctrl+e": "flatten selection",
    "cmdorctrl+j": "join selection (after selecting points)",
    "cmdorctrl+shift+j": "smooth join selection (after selecting points)",
    "shift+backspace": "delete and heal selection (after selecting points)",
    "cmdorctrl+a": "select all",
    "cmdorctrl+shift+a": "select inverse",
    esc: "select none",
    enter: "select child / edit shape or image",
    "shift+enter": "select parents",
    tab: "select next sibling",
    "shift+tab": "select previous sibling",
    "cmdorctrl+shift+g": "ungroup selection",
    "cmdorctrl+alt+g": "frame selection",
    "cmdorctrl+shift+h": "show/hide selection",
    "cmdorctrl+shift+l": "lock/unlock selection",
    alt: "measure to selection / duplicate selection (while pointing) / resize from center (while resizing) / swap component instance (while dragging from assets)",
    cmdorctrl:
      "bend tool (while editing shape) / deep select / select layer menu (while clicking) / ignore constraints (frames only)",
    shift: "resize proportionally (while resizing)",
    space: "move while resizing",
    "cmdorctrl+x": "cut",
    "cmdorctrl+v": "paste",
    "cmdorctrl+d": "duplicate selection in place",
    "cmdorctrl+r": "rename selection",
    "cmdorctrl+shift+e": "export",
    "cmdorctrl+alt+c": "copy properties",
    "cmdorctrl+alt+v": "paste properties / distribute vertical spacing",
    "shift+h": "flip horizontal",
    "shift+v": "flip vertical",
    "cmdorctrl+m": "use as mask",
    "cmdorctrl+shift+k": "place image / create component",
    "1": "set opacity to 10%",
    "5": "set opacity to 50%",
    "0": "set opacity to 100%",
    "cmdorctrl+]": "bring forward",
    "cmdorctrl+[": "send backward",
    "cmdorctrl+alt+]": "bring to front",
    "cmdorctrl+alt+[": "send to back",
    "alt+a": "align left",
    "alt+d": "align right",
    "alt+w": "align top",
    "alt+s": "align bottom",
    "alt+h": "align horizontal centers",
    "alt+v": "align vertical centers",
    "cmdorctrl+alt+h": "distribute horizontal spacing",
    "cmdorctrl+shift+b": "detach instance",
  },
} as AppParams;

export default app;
