import { AppParams } from "~/types";

const app = {
  id: "firefox",
  name: "Firefox",
  icon: "/app-icons/firefox.png",
  homepage: "https://www.mozilla.org/firefox",
  description: "Mozilla Firefox is a free and open-source web browser.",
  globals: {},
  shortcuts: {
    "alt+left": "back",
    "alt+right": "forward",
    "alt+home": "home",
    "cmdorctrl+o": "open file",
    f5: "reload",
    "cmdorctrl+f5": "reload (override cache)",
    esc: "stop / close the find or quick find bar",
    tab: "focus next link or input field",
    "shift+tab": "focus previous link or input field",
    pgdn: "go down a screen",
    pgup: "go up a screen",
    space: "go down a screen / toggle play / pause in media",
    "shift+space": "go up a screen",
    end: "go to bottom of page / seek to the end in media",
    home: "go to top of page / seek to the beginning in media",
    f6: "move to next frame, pop-up / focus address bar",
    "shift+f6": "move to previous frame, pop-up",
    "cmdorctrl+p": "print",
    "alt+enter": "save focused link",
    "cmdorctrl+s": "save page as",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+0": "zoom reset",
    "cmdorctrl+c": "copy",
    "cmdorctrl+x": "cut",
    delete: "delete",
    "cmdorctrl+backspace": "delete word to the left",
    "cmdorctrl+delete": "delete word to the right",
    "cmdorctrl+left": "go one word to the left / seek back 10% in media",
    "cmdorctrl+right": "go one word to the right / seek forward 10% in media",
    "cmdorctrl+up": "go to beginning of line / unmute audio in media",
    "cmdorctrl+down": "go to end of line / mute audio in media",
    "cmdorctrl+home": "go to beginning of text",
    "cmdorctrl+end": "go to end of text",
    "cmdorctrl+v": "paste",
    "cmdorctrl+shift+v": "paste (as plain text)",
    "cmdorctrl+y": "redo",
    "cmdorctrl+a": "select all",
    "cmdorctrl+z": "undo",
    "cmdorctrl+f": "find in this page / focus search field in library",
    f3: "find again",
    "shift+f3": "find previous",
    "cmdorctrl+g": "find again",
    "cmdorctrl+shift+g": "find previous",
    "'": "quick find within link-text only",
    "/": "quick find",
    "alt+down": "switch search engine",
    "alt+up": "switch search engine",
    "cmdorctrl+k":
      "focus address bar for web search with default search engine",
    "cmdorctrl+e":
      "focus address bar for web search with default search engine",
    "cmdorctrl+j":
      "focus address bar for web search with default search engine / downloads",
    "cmdorctrl+shift+t": "undo close tab",
    "cmdorctrl+shift+n": "undo close window",
    "cmdorctrl+shift+x":
      "moves the url left or right (if cursor is in the address bar)",
    "cmdorctrl+h": "history sidebar",
    "cmdorctrl+shift+h": "library window (history)",
    "cmdorctrl+shift+delete": "clear recent history",
    "cmdorctrl+shift+d": "bookmark all tabs",
    "cmdorctrl+d": "bookmark this page",
    "cmdorctrl+b": "bookmarks sidebar",
    "cmdorctrl+shift+b": "show/hide the bookmarks toolbar",
    "cmdorctrl+shift+o": "show all bookmarks (library window)",
    "cmdorctrl+shift+a": "add-ons",
    f12: "toggle developer tools",
    "cmdorctrl+shift+i": "web console",
    "cmdorctrl+shift+k": "inspector",
    "cmdorctrl+shift+s": "take a screenshot",
    "shift+f7": "style editor",
    "shift+esc": "task manager",
    "shift+f5": "profiler",
    "cmdorctrl+shift+e": "network",
    "cmdorctrl+shift+m": "responsive design view",
    "cmdorctrl+u": "page source",
    "cmdorctrl+shift+j": "browser console",
    "cmdorctrl+i": "page info",
    n: "next page in pdf viewer",
    j: "next page in pdf viewer",
    right: "next page in pdf viewer / seek forward 15 seconds in media",
    p: "previous page in pdf viewer",
    k: "previous page in pdf viewer",
    left: "previous page in pdf viewer / seek back 15 seconds in media",
    r: "rotate the document clockwise in pdf viewer",
    "shift+r": "rotate counterclockwise in pdf viewer",
    "cmdorctrl+alt+p": "switch to presentation mode in pdf viewer",
    s: "choose text selection tool in pdf viewer",
    h: "choose hand tool in pdf viewer",
    "cmdorctrl+alt+g": "focus the page number input box in pdf viewer",
    "cmdorctrl+enter": "complete .com address",
    "shift+delete": "delete selected autocomplete entry",
    f11: "toggle full screen",
    alt: "toggle menu bar activation (showing it temporarily when hidden)",
    f10: "toggle menu bar activation (showing it temporarily when hidden)",
    "cmdorctrl+alt+r": "toggle reader mode",
    f9: "caret browsing",
    "alt+d": "focus address bar",
    "cmdorctrl+l": "focus address bar",
    down: "decrease volume in media",
    up: "increase volume in media",
  },
} as AppParams;

export default app;
