import { AppParams } from "~/types";

const app = {
  id: "gitlab",
  name: "GitLab",
  icon: "/app-icons/gitlab.png",
  homepage: "https://gitlab.com",
  description:
    "GitLab is a web-based DevOps lifecycle tool that provides a Git-repository manager providing wiki, issue-tracking and continuous integration/continuous deployment pipeline features, using an open-source license, developed by GitLab Inc.",
  globals: {},
  shortcuts: {
    "?": "show or hide the shortcut reference sheet",
    "shift+p": "go to your projects page",
    "shift+g": "go to your groups page",
    "shift+a": "go to your activity page",
    "shift+l": "go to your milestones page",
    "shift+s": "go to your snippets page",
    s: "put the cursor in the issues or merge requests search",
    "shift+i": "go to your issues page",
    "shift+t": "go to your merge requests page",
    "p+b": "show or hide the performance bar",
    up: "edit your last comment, you must be in a blank text field below a thread / move selection up / scroll up",
    "cmdorctrl+shift+p":
      "toggle markdown preview when editing text in a text field",
    "g+p": "go to the project home page",
    "g+v": "go to the project activity feed",
    "g+r": "go to the project releases list",
    "g+f": "go to the project files list",
    t: "go to the project file search page",
    "g+c": "go to the project commits list",
    "g+n": "go to the repository graph page",
    "g+d": "go to the repository charts",
    "g+i": "go to the project issues list",
    i: "go to the new issue page",
    "g+b": "go to the project issues boards list",
    "g+m": "go to the project merge requests list",
    "g+j": "go to the ci/cd jobs list",
    "g+l": "go to the project metrics",
    "g+e": "go to the project environments",
    "g+k": "go to the project kubernetes cluster integration page",
    "g+s": "go to the project snippets list",
    "g+w": "go to the project wiki, if enabled",
    e: "edit description / edit wiki page",
    a: "change assignee",
    m: "change milestone",
    l: "change label",
    r: "start writing a comment, if any text is selected it will be quoted",
    n: "move to next unresolved discussion, merge requests only",
    p: "move to previous unresolved discussion, merge requests only",
    "]": "move to next file, merge requests only",
    "[": "move to previous file, merge requests only",
    down: "move selection down / scroll down",
    enter: "open selection",
    esc: "go back to file list screen, only while searching for files",
    y: "go to file permalink, only while viewing a file",
    "cmdorctrl+p": "search for, and then open, another file for editing",
    "cmdorctrl+enter": "commit, when editing the commit message",
    left: "scroll left",
    right: "scroll right",
    "shift+up": "scroll to top",
    "shift+down": "scroll to bottom",
    "cmdorctrl+backspace": "clear entire search filter",
    "alt+backspace": "clear one token at a time",
  },
} as AppParams;

export default app;
