const app = {
  id: "gmail",
  name: "Gmail",
  icon: "/app-icons/gmail.png",
  homepage: "https://mail.google.com/",
  description:
    "Gmail is a free email service developed by Google. Users can access Gmail on the web and using third-party programs that synchronize email content through POP or IMAP protocols.",
  globals: {},
  shortcuts: {
    p: "previous message in an open conversation",
    n: "next message in an open conversation",
    "shift+esc": "focus main window",
    esc: "focus latest chat or compose",
    "cmdorctrl+.": "advance to the next chat or compose",
    "cmdorctrl+,": "advance to the previous chat or compose",
    "cmdorctrl+enter": "send",
    "cmdorctrl+shift+c": "add cc recipients",
    "cmdorctrl+shift+b": "add bcc recipients",
    "cmdorctrl+shift+f": "access custom from",
    "cmdorctrl+k": "insert a link",
    "cmd+;": "go to next misspelled word (mac only)",
    "cmdorctrl+m": "open spelling suggestions",
    "cmdorctrl+shift+5": "previous font",
    "cmdorctrl+shift+6": "next font",
    "cmdorctrl+shift+minus": "decrease font size",
    "cmdorctrl+shift+plus": "increase font size",
    "cmdorctrl+b": "bold",
    "cmdorctrl+i": "italics",
    "cmdorctrl+u": "underline",
    "cmdorctrl+shift+7": "numbered list",
    "cmdorctrl+shift+8": "bulleted list",
    "cmdorctrl+shift+9": "quote",
    "cmdorctrl+[": "indent less",
    "cmdorctrl+]": "indent more",
    "cmdorctrl+shift+l": "align left",
    "cmdorctrl+shift+e": "align center",
    "cmdorctrl+shift+r": "align right",
    "cmdorctrl+\\": "remove formatting",
    ",": "move focus to toolbar",
    x: "select conversation",
    s: "toggle star or rotate among superstars",
    e: "archive",
    m: "mute conversation",
    "shift+1": "report as spam",
    "shift+3": "delete",
    r: "reply",
    "shift+r": "reply in a new window",
    a: "reply all",
    "shift+a": "reply all in a new window",
    f: "forward",
    "shift+f": "forward in a new window",
    "shift+n": "update conversation",
    "]": "archive conversation and go to next",
    "[": "archive conversation and go to previous",
    z: "undo last action",
    "shift+i": "mark as read",
    "shift+u": "mark as unread",
    "shift+-": "mark unread from the selected message",
    "=": "mark as important",
    "-": "mark as not important",
    b: "snooze",
    ";": "expand entire conversation",
    "shift+;": "collapse entire conversation",
    "shift+t": "add conversation to tasks",
    "h+m": "show menu",
    "h+a": "show archived hangouts",
    "h+i": "show hangout requests",
    "h+c": "focus on the conversation list",
    "h+p": "open phone",
    "g+i": "go to inbox",
    "g+s": "go to starred conversations",
    "g+b": "go to snoozed conversations",
    "g+t": "go to sent messages",
    "s+d": "go to drafts",
    "g+a": "go to all mail",
    "cmdorctrl+alt+,":
      "switch between the calendar, keep, and tasks sidebar and your inbox",
    "cmdorctrl+alt+.":
      "switch between the calendar, keep, and tasks sidebar and your inbox",
    "g+k": "go to tasks",
    "g+l": "go to label",
    "shift+8+a": "select all conversations",
    "shift+8+n": "deselect all conversations",
    "shift+8+r": "select read conversations",
    "shift+8+u": "select unread conversations",
    "shift+8+s": "select starred conversations",
    "shift+8+t": "select unstarred conversations",
    "g+n": "go to next page",
    "g+p": "go to previous page",
    u: "back to threadlist",
    k: "newer conversation",
    j: "older conversation",
    enter: "open conversation",
    "`": "go to next inbox section",
    "shift+`": "go to previous inbox section",
    c: "compose",
    d: "compose in a new tab",
    "/": "search mail",
    g: "search chat contacts",
    ".": "open more actions menu",
    v: "open move to menu",
    l: "open label as menu",
    "?": "open keyboard shortcut help",
  },
} as AppParams;

export default app;
