const app = {
  id: "googleslides",
  name: "Google Slides",
  icon: "/app-icons/googleslides.png",
  homepage: "https://www.google.com/slides/about/",
  description: "Create and edit presentations.",
  globals: {},
  shortcuts: {
    "cmdorctrl+m": "generate a new slide",
    "cmdorctrl+c": "add selected information to the clipboard",
    "cmdorctrl+d": "duplicates slides highlighted on the filmstrip",
    "cmdorctrl+x": "cut selected information to the clipboard",
    "cmdorctrl+v": "paste copied content to a slide",
    "cmdorctrl+z": "reverse an action",
    "cmdorctrl+y": "repeat an operation",
    "cmdorctrl+s": "save slide content",
    "cmdorctrl+k": "insert or edit an external link",
    "cmdorctrl+p": "print slide presentations",
    "cmdorctrl+g": "find again",
    "cmdorctrl+/": "show shortcuts",
    "alt+enter": "open a link",
    "cmdorctrl+a": "select all",
    "cmdorctrl+o":
      "triggers a pop-up that helps you open files from a drive or computer",
    "cmdorctrl+f": "search and find text in your slide",
    "cmdorctrl+h": "find and replace distinct content from your presentation",
    "cmdorctrl+shift+f":
      "transition to compact mode, ideal for hiding the menu",
    "cmdorctrl+shift+c": "enables caption use",
    "cmdorctrl+shift+a": "select none",
    "cmdorctrl+b": "bold content",
    "cmdorctrl+i": "italicize selected text",
    "cmdorctrl+u": "underline selected information within a slide",
    "alt+shift+5": "apply strikethrough to text",
    "cmdorctrl+shift+j": "apply justification alignment to text",
    "cmdorctrl+alt+c": "duplicate the format of selected text",
    "cmdorctrl+alt+v": "paste text format",
    "cmdorctrl+\\": "delete text format",
    "cmdorctrl+shift+>": "increase font size",
    "cmdorctrl+shift+<": "decrease font size",
    "cmdorctrl+]": "increase paragraph indentation",
    "cmdorctrl+[": "decrease paragraph indentation",
    "cmdorctrl+shift+l": "apply left alignment to text",
    "cmdorctrl+shift+e": "center align content",
    "cmdorctrl+shift+r": "right align text",
    "cmdorctrl+shift+7": "insert numbered list in a slide",
    "cmdorctrl+shift+8": "add a bulleted list",
    "cmdorctrl+alt+shift+f": "shift focus to the filmstrip",
    "cmdorctrl+alt+shift+c": "move focus to the slide",
    up: "shift attention to the previous slide in a presentation",
    down: "shift attention to the next slide in a presentation",
    home: "move the slide in focus up",
    end: "move the slide in focus down",
    "cmdorctrl+shift+up":
      "adjusts the slide in focus by moving it to the beginning of the presentation",
    "cmdorctrl+shift+down":
      "adjusts the slide in focus by moving it to the end of the presentation",
    "shift+up": "extend the selection to the previous slide",
    "shift+down": "extend the selection to the next slide",
    "shift+home": "select the first slide",
    "shift+end": "select the last slide",
    "alt+f": "opens file menu",
    "alt+e": "access the edit menu",
    "alt+v": "view menu",
    "alt+i": "access the insert menu",
    "alt+o": "opens the format menu",
    "alt+t": "opens the tool menu",
    "alt+h": "access the help menu",
    "alt+a": "opens the accessibility menu",
    "ctrl+alt+f": "access the file menu on mac",
    "ctrl+alt+e": "open the edit menu on mac",
    "ctrl+alt+v": "view menu on mac",
    "ctrl+alt+i": "access the insert menu on mac",
    "ctrl+alt+o": "open the format menu on mac",
    "ctrl+alt+t": "tools menu on mac",
    "ctrl+alt+a": "opens the accessibility menu on mac",
    "cmd+alt+shift+k": "access the input tools menu on mac",
    "cmdorctrl+alt+m": "insert comment",
    "cmdorctrl+enter": "enter current comment",
    j: "next comment",
    k: "previous comment",
    r: "reply to comment",
    e: "resolve comment",
    "cmdorctrl+shift+alt+a": "open comment discussion thread",
    "cmdorctrl+alt+plus": "helps you zoom a slide inward",
    "cmdorctrl+alt+minus": "helps you zoom a slide outward",
    "cmdorctrl+alt+shift+s": "access the speaker notes panel",
    "cmdorctrl+shift+alt+p": "provides an html view of your presentation",
    "cmdorctrl+alt+shift+b": "opens a slide’s transition animation panel",
    "cmdorctrl+f5": "displays slides from the currently selected slide",
    "cmdorctrl+shift+f5": "displays slides from the first slide",
    right: "move to the next slide",
    left: "move to the previous slide",
    s: "access speaker notes",
    a: "open audience tools",
    l: "toggle the laser pointer",
    f11: "enable full screen",
    b: "display or return from a blank back slide",
    w: "show or return from a white blank slide",
  },
};

export default app;
