const app = {
  id: "google-chrome",
  name: "Google Chrome",
  icon: "/app-icons/chrome.png",
  homepage: "https://www.google.com/chrome",
  shortcuts: {
    "cmdOrCtrl+N": "Open a new window",
    "shift+cmdOrCtrl+N": "Open a new window in Incognito mode",
    "cmdOrCtrl+T": "Open a new tab, and jump to it",
    "shift+cmdOrCtrl+T": "Reopen the last closed tab, and jump to it",
    "cmdOrCtrl+Tab": "Jump to the next open tab",
    "cmdOrCtrl+PgDn": "Jump to the next open tab",
    "shift+cmdOrCtrl+Tab": "Jump to the previous open tab",
    "cmdOrCtrl+PgUp": "Jump to the previous open tab",
    "cmdOrCtrl+1-8": "Jump to a specific tab",
    "cmdOrCtrl+9": "Jump to the last tab",
    "alt+Home": "Open your home page in the current tab",
    "alt+arrowLeft":
      "Open the previous page from your browsing history in the current tab",
    "alt+arrowRight":
      "Open the next page from your browsing history in the current tab",
    "cmdOrCtrl+W": "Close the current tab",
    "shift+cmdOrCtrl+W": "Close all open tabs and the browser",
    "alt+F4": "Close the current window",
    "shift+cmdOrCtrl+Q": "Quit Google Chrome",
    "alt+F": "Open the Chrome menu",
    "shift+cmdOrCtrl+B": "Show or hide the Bookmarks bar",
    "shift+cmdOrCtrl+O": "Open the Bookmarks Manager",
    "cmdOrCtrl+H": "Open the History page in a new tab",
    "cmdOrCtrl+J": "Open the Downloads page in a new tab",
    "shift+Esc": "Open the Chrome Task Manager",
    "alt+shift+T": "Set focus on the first item in the Chrome toolbar",
    F6: "Switch focus forward between the Address bar, Bookmarks bar (if showing), and page content",
    "shift+F6":
      "Switch focus backward between the Address bar, Bookmarks bar (if showing), and page content",
    "cmdOrCtrl+F": "Open the Find Bar to search the current page",
    "cmdOrCtrl+g": "Jump to the next match to your Find Bar search",
    "shift+cmdOrCtrl+G": "Jump to the previous match to your Find Bar search",
    "shift+cmdOrCtrl+J or F12": "Open Developer Tools",
    "shift+cmdOrCtrl+Delete": "Open the Clear Browsing Data options",
    F1: "Open the Chrome Help Center in a new tab",
    "shift+cmdOrCtrl+M": "Log in a different user or browse as a Guest",
    "alt+shift+I": "Open a feedback form",
    Enter: "Search with your default search engine",
    "Alt+Enter": "while searching - Open a new tab and perform a Google search",
    "ctrlOrCmd+l": "Jump to the address bar",
    "Ctrl+k": "Search from anywhe re on the page",
    "cmdOrCtrl+P": "Open options to print the current page",
    "cmdOrCtrl+S": "Open options to save the current page",
    "cmdOrCtrl+alt+P": "Open the Page Setup dialog",
    "cmdOrCtrl+Shift+i": "Email your current page",
    "cmdOrCtrl+R": "Reload your current page",
    "cmdOrCtrl+Shift+R": "Reload your current page, ignoring cached content",
    Esc: "Stop the page loading",
    Tab: "Browse clickable items moving forward",
    "Shift+Tab": "Browse clickable items moving backward",
    "cmdOrCtrl+o+Select a file":
      "Open a file from your computer in Google Chrome",
    "cmdOrCtrl+alt+u":
      "Display non-editable HTML source code for the current page",
    "cmdOrCtrl+alt+j": "Open the JavaScript Console",
    "cmdOrCtrl+d": "Save your current webpage as a bookmark",
    "cmdOrCtrl+Shift+d": "Save all open tabs as bookmarks in a new folder",
    "cmdOrCtrl+Ctrl+f": "Turn full-screen mode on or off",
    "cmdOrCtrl++": "Make everything on the page bigger",
    "cmdOrCtrl+-": "Make everything on the page smaller",
    "cmdOrCtrl+0": "Return everything on the page to the default size",
    Space: "Scroll down a webpage, a screen at a time",
    "Shift+Space": "Scroll up a webpage, a screen at a time",
    "cmdOrCtrl+alt+f": "Search the web",
    "alt+Delete": "Delete the previous word in a text field",
    "shift+cmdOrCtrl+h": "Open your home page in the current tab",
  },
};

export { app };
