const app = {
  id: "googledocs",
  name: "Google Docs",
  icon: "/app-icons/googledocs.png",
  homepage: "https://www.google.com/docs/about/",
  description:
    "Google Docs let you create, edit, and collaborate on documents in real time.",
  globals: {},
  shortcuts: {
    "cmdorctrl+/": "show common keyboard shortcuts",
    "cmdorctrl+c": "copy",
    "cmdorctrl+x": "cut",
    "cmdorctrl+v": "paste",
    "cmdorctrl+shift+v": "paste without formatting",
    "cmdorctrl+z": "undo",
    "cmdorctrl+shift+z": "redo",
    "cmdorctrl+k": "insert or edit link",
    "alt+enter": "open link",
    "cmdorctrl+s": "save (changes automatically save in drive)",
    "cmdorctrl+p": "print",
    "cmdorctrl+o": "open",
    "cmdorctrl+f": "find",
    "cmdorctrl+h": "find and replace",
    "cmdorctrl+shift+f": "hide the menus (compact mode)",
    "cmdorctrl+enter": "insert page break",
    "alt+/": "search the menus (search docs menus/chrome menus)",
    "cmdorctrl+alt+shift+c": "switch to viewing",
    "cmdorctrl+alt+shift+x": "switch to suggesting",
    "cmdorctrl+alt+shift+z": "switch to editing",
    "cmdorctrl+b": "bold",
    "cmdorctrl+i": "italicize",
    "cmdorctrl+u": "underline",
    "cmdorctrl+shift+5": "strikethrough",
    "cmdorctrl+.": "superscript",
    "cmdorctrl+,": "subscript",
    "cmdorctrl+alt+c": "copy text formatting",
    "cmdorctrl+alt+v": "paste text formatting",
    "cmdorctrl+\\": "clear text formatting",
    "cmdorctrl+shift+.": "increase font size",
    "cmdorctrl+shift+,": "decrease font size",
    "cmdorctrl+]": "increase paragraph indentation",
    "cmdorctrl+[": "decrease paragraph indentation",
    "cmdorctrl+alt+0": "apply normal text style",
    "cmdorctrl+alt+1": "apply heading style 1",
    "cmdorctrl+alt+2": "apply heading style 2",
    "cmdorctrl+alt+3": "apply heading style 3",
    "cmdorctrl+alt+4": "apply heading style 4",
    "cmdorctrl+alt+5": "apply heading style 5",
    "cmdorctrl+alt+6": "apply heading style 6",
    "cmdorctrl+shift+l": "left align",
    "cmdorctrl+shift+e": "center align",
    "cmdorctrl+shift+r": "right align",
    "cmdorctrl+shift+7": "insert numbered list",
    "cmdorctrl+shift+8": "insert bulleted list",
    "cmdorctrl+shift+9": "inset checklist",
    "cmdorctrl+shift+up": "move paragraph up",
    "cmdorctrl+shift+down": "move paragraph down",
    "cmdorctrl+alt+y": "insert alt text",
    "cmdorctrl+alt+k": "resize larger",
    "cmdorctrl+alt+b": "resize larger horizontally",
    "cmdorctrl+alt+i": "resize larger vertically",
    "cmdorctrl+alt+j": "resize smaller",
    "cmdorctrl+alt+w": "resize smaller horizontally",
    "cmdorctrl+alt+q": "resize smaller vertically",
    "shift+esc": "close drawing editor",
    "cmdorctrl+a": "select all",
    "shift+left": "extend selection one character",
    "shift+right": "extend selection one character",
    "shift+up": "extend selection one line",
    "shift+down": "extend selection one line",
    "cmdorctrl+shift+left": "extend selection one word",
    "cmdorctrl+shift+right": "extend selection one word",
    "shift+home": "extend selection to the beginning of the line",
    "shift+end": "extend selection to the end of the line",
    "cmdorctrl+shift+home": "extend selection to the beginning of the document",
    "cmdorctrl+shift+end": "extend selection to the end of the document",
    "ctrl+alt+a+h": "show outline",
    "ctrl+alt+n+h": "move to next heading",
    "ctrl+alt+p+h": "move to previous heading",
    "ctrl+alt+n+1": "move to next heading 1",
    "ctrl+alt+n+2": "move to next heading 2",
    "ctrl+alt+n+3": "move to next heading 3",
    "ctrl+alt+n+4": "move to next heading 4",
    "ctrl+alt+n+5": "move to next heading 5",
    "ctrl+alt+n+6": "move to next heading 6",
    "ctrl+alt+p+1": "move to previous heading 1",
    "ctrl+alt+p+2": "move to previous heading 2",
    "ctrl+alt+p+3": "move to previous heading 3",
    "ctrl+alt+p+4": "move to previous heading 4",
    "ctrl+alt+p+5": "move to previous heading 5",
    "ctrl+alt+p+6": "move to previous heading 6",
    "ctrl+alt+n+g": "move to next graphic",
    "ctrl+alt+p+g": "move to previous graphic",
    "ctrl+alt+n+o": "move to next list",
    "ctrl+alt+p+o": "move to previous list",
    "ctrl+alt+n+w": "move to next formatting change",
    "ctrl+alt+p+w": "move to previous formatting change",
    "ctrl+alt+n+r": "move to next edit",
    "ctrl+alt+p+r": "move to previous edit",
    "ctrl+alt+shift+t+s": "move to the start of the table",
    "ctrl+alt+shift+t+d": "move to the end of the table",
    "ctrl+alt+shift+t+i": "move to the start of the table column",
    "ctrl+alt+shift+t+k": "move to the end of the table column",
    "ctrl+alt+shift+t+b": "move to the next table column",
    "ctrl+alt+shift+t+v": "move to the previous table column",
    "ctrl+alt+shift+t+j": "move to the start of the table row",
    "ctrl+alt+shift+t+l": "move to the end of the table row",
    "ctrl+alt+shift+t+m": "move to the next table row",
    "ctrl+alt+shift+t+g": "move to the previous table row",
    "ctrl+alt+shift+t+e": "exit table",
    "ctrl+alt+shift+n+t": "move to the next table",
    "ctrl+alt+shift+p+t": "move to the previous table",
    "ctrl+alt+x": "open spelling/grammar",
    f7: "open spelling/grammar on mac",
    "ctrl+shift+y": "open dictionary",
    "ctrl+shift+c": "word count",
    pageup: "page up",
    pagedown: "page down",
    "ctrl+alt+o+h": "insert or move to header",
    "ctrl+alt+o+f": "insert or move to footer",
  },
};

export default app;
