import { AppParams } from "~/types";

const app = {
  id: "intellijidea",
  name: "IntelliJ IDEA",
  icon: "/app-icons/intellijidea.png",
  homepage: "https://www.jetbrains.com/idea/",
  description:
    "IntelliJ IDEA is an integrated development environment written in Java for developing computer software. It is developed by JetBrains, and is available as an Apache 2 Licensed community edition, and in a proprietary commercial edition.",
  globals: {},
  shortcuts: {
    "cmdorctrl+space": "basic code completion",
    "cmdorctrl+shift+space": "smart code completion",
    "cmdorctrl+shift+enter": "complete statement",
    "cmdorctrl+p": "parameter info",
    "cmdorctrl+q": "quick documentation lookup",
    "shift+f1": "external doc",
    "cmdorctrl+f1": "error or warning at caret",
    "alt+ins": "generate code",
    "cmdorctrl+o": "override methods",
    "cmdorctrl+i": "implement methods",
    "cmdorctrl+alt+t": "surround with",
    "cmdorctrl+/": "comment or uncomment line",
    "cmdorctrl+shift+/": "comment or uncomment block",
    "cmdorctrl+w": "select successively increasing code blocks",
    "cmdorctrl+shift+w": "decrease current selection to previous state",
    "alt+q": "context info",
    "alt+enter": "show intention actions and quick-fixes",
    "cmdorctrl+alt+l": "reformat code",
    "cmdorctrl+alt+o": "optimize imports",
    "cmdorctrl+alt+i": "auto-indent line(s)",
    tab: "indent selected lines",
    "shift+tab": "unindent selected lines",
    "cmdorctrl+x": "cut current line or selected block to clipboard",
    "cmdorctrl+c": "copy current line or selected block to clipboard",
    "cmdorctrl+v": "paste from clipboard",
    "cmdorctrl+shift+v": "paste from recent buffers",
    "cmdorctrl+d": "duplicate current line or selected block",
    "cmdorctrl+y": "delete line at caret",
    "cmdorctrl+shift+j": "smart line join",
    "cmdorctrl+enter": "smart line split / view source",
    "shift+enter": "start new line",
    "cmdorctrl+shift+u": "toggle case for word at caret or selected block",
    "cmdorctrl+shift+]": "select till code block end",
    "cmdorctrl+shift+[": "select till code block start",
    "cmdorctrl+backspace": "delete to word end",
    "cmdorctrl+delete": "delete to word start",
    "cmdorctrl+plus": "expand code block",
    "cmdorctrl+minus": "collapse code block",
    "cmdorctrl+shift+plus": "expand all",
    "cmdorctrl+shift+minus": "collapse all",
    "cmdorctrl+f4": "close active editor tab",
    "alt+f7": "find usages",
    "cmdorctrl+f7": "find usages in file",
    "cmdorctrl+shift+f7": "highlight usages in file",
    "cmdorctrl+alt+f7": "show usages",
    "cmdorctrl+n": "go to class",
    "cmdorctrl+shift+n": "go to file",
    "cmdorctrl+alt+shift+n": "go to symbol",
    "alt+right": "go to next editor tab",
    "alt+left": "go to previous editor tab",
    f12: "go back to previous tool window",
    esc: "go to editor",
    "cmdorctrl+shift+f4": "close active run, messages...",
    "cmdorctrl+g": "go to line",
    "cmdorctrl+e": "recent files popup",
    "cmdorctrl+alt+left": "navigate back",
    "cmdorctrl+alt+right": "navigate forward",
    "cmdorctrl+shift+backspace": "navigate to last edit location",
    "alt+f1": "select current file or symbol in any view",
    "cmdorctrl+b": "go to declaration",
    "cmdorctrl+alt+b": "go to implementation(s)",
    "cmdorctrl+shift+i": "open quick definition lookup",
    "cmdorctrl+shift+b": "go to type declaration",
    "cmdorctrl+u": "go to super-method/super-class",
    "alt+up": "go to previous method",
    "alt+down": "go to next method",
    "cmdorctrl+]": "move to code block end",
    "cmdorctrl+[": "move to code block start",
    "cmdorctrl+f12": "file structure popup",
    "cmdorctrl+h": "type hierarchy",
    "cmdorctrl+shift+h": "method hierarchy",
    "cmdorctrl+alt+h": "call hierarchy",
    f2: "next highlighted error",
    "shift+f2": "previous highlighted error",
    f4: "edit source",
    "alt+home": "show navigation bar",
    f11: "toggle bookmark",
    "cmdorctrl+f11": "toggle bookmark with mnemonic",
    "shift+f11": "show bookmarks",
    "cmdorctrl+f": "find",
    f3: "find next",
    "shift+f3": "find previous",
    "cmdorctrl+r": "replace",
    "cmdorctrl+shift+f": "find in path",
    "cmdorctrl+shift+r": "replace in path",
    "cmdorctrl+alt+j": "surround with live template",
    "cmdorctrl+j": "insert live template",
    f5: "copy",
    f6: "move",
    "alt+delete": "safe delete",
    "shift+f6": "rename",
    "cmdorctrl+f6": "change signature",
    "cmdorctrl+alt+n": "inline",
    "cmdorctrl+alt+m": "extract method",
    "cmdorctrl+alt+v": "extract variable",
    "cmdorctrl+alt+f": "extract field",
    "cmdorctrl+alt+c": "extract constant",
    "cmdorctrl+alt+p": "extract parameter",
    f8: "step over",
    f7: "step into",
    "shift+f7": "smart step into",
    "shift+f8": "step out",
    "alt+f9": "run to cursor",
    "alt+f8": "evaluate expression",
    f9: "resume program",
    "cmdorctrl+f8": "toggle breakpoint",
    "cmdorctrl+shift+f8": "view breakpoints",
    "cmdorctrl+f9": "make project",
    "cmdorctrl+shift+f9": "compile selected file, package or module",
    "alt+shift+f10": "select configuration and run",
    "alt+shift+f9": "select configuration and debug",
    "shift+f10": "run",
    "shift+f9": "debug",
    "cmdorctrl+shift+f10": "run context configuration from editor",
    "cmdorctrl+k": "commit project to vcs",
    "cmdorctrl+t": "update from vcs",
    "alt+shift+c": "view recent changes",
    "alt+`": "vcs operations popup",
    "cmdorctrl+s": "save all",
    "cmdorctrl+alt+y": "synchronize",
    "cmdorctrl+shift+f12": "toggle maximizing editor",
    "alt+shift+f": "add to favorites",
    "alt+shift+i": "inspect current file",
    "cmdorctrl+`": "quick switch current scheme",
    "cmdorctrl+alt+s": "open settings dialog",
    "cmdorctrl+alt+shift+s": "open project structure dialog",
    "cmdorctrl+shift+a": "find action",
    "cmdorctrl+tab": "switch between tool and tabs",
  },
} as AppParams;

export default app;
