const app = {
  id: "iterm2",
  name: "iTerm2",
  icon: "/app-icons/iterm2.png",
  homepage: "https://iterm2.com/",
  description: "Mozilla Firefox is a free and open-source web browser.",
  globals: {},
  shortcuts: {
    "cmd+t": "new tab",
    "cmd+w": "close tab or window",
    "cmd+alt+up": "go to split pane by direction",
    "cmd+alt+down": "go to split pane by direction",
    "cmd+alt+left": "go to split pane by direction",
    "cmd+alt+right": "go to split pane by direction",
    "cmd+`": "cycle iterm windows",
    "cmd+d": "split window vertically (same profile)",
    "cmd+shift+d": "split window horizontally (same profile)",
    "cmd+enter": "fullscreen",
    "cmd+shift+enter": "maximize a pane",
    "ctrl+cmd+up": "resize pane",
    "ctrl+cmd+down": "resize pane",
    "ctrl+cmd+left": "resize pane",
    "ctrl+cmd+right": "resize pane",
    "cmd+]": "go to split pane by order of use",
    "alt+cmd+h": "split window horizontally (new profile)",
    "alt+cmd+v": "split window vertically (new profile)",
    "cmd+left": "previous/next tab",
    "cmd+right": "previous/next tab",
    "shift+cmd+c": "enter copy mode",
    "ctrl+v": "enter character selection mode in copy mode",
    h: "move cursor in copy mode",
    j: "move cursor in copy mode",
    k: "move cursor in copy mode",
    l: "move cursor in copy mode",
    up: "move cursor in copy mode",
    down: "move cursor in copy mode",
    left: "move cursor in copy mode",
    right: "move cursor in copy mode",
    "ctrl+k": "copy text in copy mode",
    "ctrl+r": "search as you type",
    "ctrl+g": "cancel the search and restore original line",
    "cmd+k": "clear the screen/pane",
    "cmd+alt+i": "broadcast command to all panes in window",
    "cmd+/": "find cursor",
  },
};

export default app;
