const app = {
  id: "jenkins",
  name: "Jenkins",
  icon: "/app-icons/jenkins.png",
  homepage: "https://www.mozilla.org/firefox",
  description:
    "Jenkins is an open source automation server. It helps automate the parts of software development related to building, testing, and deploying, facilitating continuous integration, and continuous delivery. It is a server-based system that runs in servlet containers and supports version control tools.",
  globals: {},
  shortcuts: {
    "g+d": "go to dashboard",
    "g+p": "browse to a project",
    "g+i": "find issues",
    "g+g": "administration quick search",
    "/": "quick search",
    c: "create an issue",
    ".": "quick operations",
    "?": "open shortcut help",
    "p+?": "open plans shortcut help",
    "p+v": "go to the view plans page",
    "alt+s": "submit a form",
    "cmdorctrl+enter": "submit a description or comment",
    o: "view selected issue",
    enter: "view selected issue",
    j: "next issue",
    k: "previous issue",
    z: "toggle issue fullscreen",
    "[": "dock/undock the filters panel",
    n: "next activity",
    p: "previous activity",
    f: "focus search field",
    u: "search for issues",
    t: "switch filter view",
    y: "detail view order by",
    right: "select issue detail view",
    left: "select list view",
    e: "edit issue",
    a: "assign issue",
    m: "comment on issue",
    l: "edit issue labels",
    ",": "jump to fields for editing",
    i: "assign to me",
  },
};

export default app;
