import { AppParams } from "~/types";

const app = {
  id: "jira",
  name: "Jira",
  icon: "/app-icons/jira.png",
  homepage: "https://www.atlassian.com/software/jira",
  description:
    "Jira is a product that allows bug tracking, issue tracking, and agile project management.",
  globals: {},
  shortcuts: {
    "g+d": "go to dashboard",
    "g+p": "browse to a project",
    "g+i": "find issues",
    "g+g": "administration quick search",
    "/": "quick search",
    c: "create an issue",
    ".": "quick operations",
    "?": "open shortcut help",
    "p+?": "open plans shortcut help",
    "p+v": "go to the view plans page",
    "alt+s": "submit a form",
    "cmdorctrl+enter": "submit a description or comment",
    o: "view selected issue",
    enter: "view selected issue",
    j: "next issue",
    k: "previous issue",
    z: "toggle issue fullscreen",
    "[": "dock/undock the filters panel",
    n: "next activity",
    p: "previous activity",
    f: "focus search field",
    u: "search for issues",
    t: "switch filter view",
    y: "detail view order by",
    "→": "select issue detail view",
    "←": "select list view",
    e: "edit issue",
    a: "assign issue",
    m: "comment on issue",
    l: "edit issue labels",
    ",": "jump to fields for editing",
    i: "assign to me",
  },
} as AppParams;

export default app;
