import { AppParams } from "~/types";

const app = {
  id: "keynote",
  name: "Keynote",
  icon: "/app-icons/keynote.png",
  homepage: "https://www.apple.com/keynote/",
  description: "Create and edit presentations.",
  globals: {},
  shortcuts: {
    "cmd+m": "minimize the window",
    "alt+cmd+m": "minimize all windows",
    "cmd+h": "hide keynote",
    "alt+cmd+h": "hide all other app windows",
    "ctrl+cmd+f": "enter full-screen mode",
    "cmd+>": "zoom in",
    "cmd+<": "zoom out",
    "shift+cmd+0": "zoom to selection",
    "alt+shift+cmd+0": "zoom to fit",
    "cmd+0": "return to normal size",
    "cmd+,": "open keynote preferences",
    "shift+cmd+?": "open the pages user guide",
    "cmd+w": "close the window",
    "alt+cmd+w": "close all windows",
    "cmd+q": "quit keynote",
    "alt+cmd+q": "quit keynote with windows open",
    "alt+cmd+p": "play your presentation",
    f: "pause your presentation",
    b: "pause your presentation with a black screen",
    w: "pause your presentation with a white screen",
    home: "go to the first slide",
    "fn+up": "go to the first slide",
    end: "go to the last slide",
    "fn+down": "go to the last slide",
    right: "go to the next slide / expand a group of slides",
    down: "go to the next slide",
    "shift+right":
      "go to the next slide without animation / expand your selection to the next slide in light table view",
    left: "go to the previous slide / collapse a group of slides",
    up: "go to the previous slide",
    z: "go through previously viewed slides",
    s: "show the slide number",
    c: "show or hide the pointer",
    "shift+cmd+p": "show or hide the presenter notes",
    u: "scroll up the presenter notes",
    d: "scroll down the presenter notes",
    "cmd+plus": "increase presenter notes font size",
    x: "switch the primary and presenter displays",
    r: "reset the timer",
    h: "hide the presentation and move to the last app used",
    escape: "quit presentation mode",
    q: "quit presentation mode",
    "?": "show or hide keyboard shortcuts",
    "/": "show or hide keyboard shortcuts",
    space: "play your video",
    k: "pause or resume playing the video",
    j: "rewind the video by frame when paused",
    l: "fast forward the video by frame when paused",
    i: "move to the beginning of the video",
    o: "move to the end of the video",
    tab: "indent selected slides right",
    "shift+tab": "move indented slides left",
    enter: "add a new slide at the same level as the selected slide",
    "shift+cmd+n": "add a new slide at the same level as the selected slide",
    "cmd+d": "duplicate a selected slide",
    delete: "delete a selected slide",
    "shift+cmd+h":
      "skip a slide in your presentation or show a slide you're skipping",
    "cmd+up": "select the first slide in light table view",
    "cmd+down": "select the last slide in light table view",
    "shift+left":
      "expand your selection to the previous slide in light table view",
    "shift+cmd+up":
      "expand your selection to the first slide in light table view",
    "shift+cmd+down":
      "expand your selection to the last slide in light table view",
  },
} as AppParams;

export default app;
