import { AppParams } from "~/types";

const app = {
  id: "linear",
  name: "Linear",
  icon: "/app-icons/linear.png",
  homepage: "https://linear.app",
  description:
    "Linear is an issue tracking tool built for speed. It helps users streamline software projects, tasks, and bug tracking.",
  globals: {},
  shortcuts: {
    "cmdOrCtrl+K": "Open command menu",
    "cmdOrCtrl+Enter": "Save or submit",
    Esc: "Back",
    Space: "Peek into issue",
    "Enter+O": "Open focused item",
    X: "Select in a list",
    "up+K": "Move up",
    "down+J": "Move down",
    "→": "Move right",
    "←": "Move left",
    "alt+shift+Q": "Log out",
    "O+I": "Open issue",
    "cmdOrCtrl+shift+up": "Open parent issue",
    "cmdOrCtrl+shift+down": "Open sub issue",
    "/": "Open search",
    "?": "Open this view",
    "cmdOrCtrl+I": "Open details sidebar",
    "cmdOrCtrl+B": "Toggle list / board view",
    "ctrl+shift+1": "Go to team 1",
    "ctrl+shift+2": "Go to team 2",
    "ctrl+shift+3": "Go to team 3",
    "ctrl+shift+4": "Go to team 4",
    "ctrl+shift+5": "Go to team 5",
    "ctrl+shift+6": "Go to team 6",
    "ctrl+shift+7": "Go to team 7",
    "ctrl+shift+8": "Go to team 8",
    "ctrl+shift+9": "Go to team 9",
    "G+I": "Go to inbox",
    "G+A": "Go to my issues",
    "G+B": "Go to backlog",
    "G+X": "Go to archived issues",
    "G+E": "Go to all issues",
    "G+D": "Go to board",
    "G+C": "Go to cycles",
    "G+V": "Go to active cycle",
    "G+W": "Go to upcoming cycle",
    "G+P": "Go to projects",
    "G+S": "Go to settings",
    "O+F": "Open a favorite",
    "O+P": "Open a project",
    "O+C": "Open a cycle",
    "O+U": "Open a user",
    "O+M": "Open my profile",
    "O+T": "Open a team",
    "cmdOrCtrl+alt+1": "Set issue status 1",
    "cmdOrCtrl+alt+2": "Set issue status 2",
    "cmdOrCtrl+alt+3": "Set issue status 3",
    "cmdOrCtrl+alt+4": "Set issue status 4",
    "cmdOrCtrl+alt+5": "Set issue status 5",
    "cmdOrCtrl+alt+6": "Set issue status 6",
    "cmdOrCtrl+alt+7": "Set issue status 7",
    "cmdOrCtrl+alt+8": "Set issue status 8",
    "cmdOrCtrl+alt+9": "Set issue status 9",
    C: "New issue",
    "alt+C": "New issue from template",
    V: "New issue in full screen view",
    E: "Edit issue",
    A: "Assign to user",
    I: "Assign to me",
    L: "Change labels",
    "shift+L": "Remove label",
    S: "Change status",
    P: "Change priority",
    "shift+E": "Change estimate",
    "shift+D": "Set due date",
    "cmdOrCtrl+shift+D": "Remove due date",
    R: "Rename",
    "cmdOrCtrl+shift+M": "Move to another team",
    "cmdOrCtrl+Delete": "Delete issue",
    "#": "Restore issue",
    "shift+S": "Subscribe to issue",
    "cmdOrCtrl+shift+S": "Manage issue subscribers",
    "M+B": "Mark as blocked",
    "M+X": "Mark as blocking",
    "M+R": "Reference related issue",
    "M+M": "Merge into another issue",
    "ctrl+L": "Link any URL to issue",
    F: "Filter issues",
    "shift+F": "Clear last issue filter",
    "alt+shift+F": "Clear all issue filters",
    "cmdOrCtrl+.": "Copy issue ID",
    "cmdOrCtrl+shift+.": "Copy git branch name",
    "cmdOrCtrl+shift+,": "Copy issue URL",
    "cmdOrCtrl+shift+O": "Create sub-issue",
    "shift+C": "Add to cycle",
    "shift+P": "Add to project",
    "ctrl+M": "Comment on issue",
    "cmdOrCtrl+shift+C": "Add to active cycle",
  },
} as AppParams;

export default app;
