const app = {
  id: "logicpro",
  name: "Logic Pro",
  icon: "/app-icons/logicpro.png",
  homepage: "https://www.apple.com/logic-pro/",
  description:
    "Logic Pro is a digital audio workstation and MIDI sequencer software application for the macOS platform.",
  globals: {},
  shortcuts: {
    r: "record",
    "shift+r":
      "capture recording (if you forgot to hit record and you played some nice melodies)",
    m: "metronome / mute selected tracks",
    s: "solo track(s)",
    p: "piano roll",
    e: "editor window",
    y: "library",
    i: "inspector",
    a: "(toggle) automation",
    g: "global tracks (tempo, time signature, markers) / show/hide global tracks",
    ",": "move playhead back 1 bar / pause",
    ".": "move playhead forward 1 bar",
    "shift+,": "move playhead back 8 bars",
    "shift+.": "move playhead forward 8 bars",
    "cmd+s": "save",
    "cmd+z": "undo",
    "shift+cmd+z": "redo",
    "cmd+c": "copy",
    "cmd+v": "paste",
    backspace: "delete",
    "cmd+d": "new track – with duplicate settings",
    "ctrl+alt+cmd+t": "toolbar",
    b: "smart controls",
    x: "mixer",
    n: "score editor",
    d: "list editors",
    "alt+cmd+p": "note pads",
    o: "apple loops browser",
    f: "media browser",
    "alt+c": "colors",
    "alt+k": "key command window",
    "alt+cmd+k": "step input keyboard",
    "alt+t": "track headers",
    v: "show/hide all plugin windows",
    "1": "recall screensets 1 / go to marker number 1",
    "2": "recall screensets 2 / go to marker number 2",
    "3": "recall screensets 3 / go to marker number 3",
    "4": "recall screensets 4 / go to marker number 4",
    "5": "recall screensets 5 / go to marker number 5",
    "6": "recall screensets 6 / go to marker number 6",
    "7": "recall screensets 7 / go to marker number 7",
    "8": "recall screensets 8 / go to marker number 8",
    "9": "recall screensets 9 / go to marker number 9",
    "alt+p": "project settings",
    "cmd+f1": "open/close instrument in selected track",
    "alt+cmd+f1": "open/close 1st insert fx on selected track",
    "alt+cmd+f2": "open/close 2nd insert fx on selected track",
    "alt+cmd+f3": "open/close 3rd insert fx on selected track",
    "ctrl+alt+cmd+f1": "open/close 1st midi fx on selected track",
    "ctrl+alt+cmd+f2": "open/close 2nd midi fx on selected track",
    "ctrl+alt+cmd+f3": "open/close 3rd midi fx on selected track",
    "cmd+n": "new track – with selection window",
    "alt+cmd+a": "new audio track",
    "alt+cmd+s": "new soft instrument track / new midi track",
    "alt+cmd+u": "new drummer track",
    "alt+cmd+x": "new external midi track",
    "0": "go to home / stop",
    "alt+,": "go to previous marker",
    "alt+.": "go to next marker",
    "ctrl+home": "go to selection start",
    "ctrl+end": "go to selection end",
    z: "zoom to selection or all content",
    "ctrl+alt": "zoom tool",
    "ctrl+z": "zoom focused track",
    "cmd+up": "zoom height",
    "cmd+down": "zoom height",
    "cmd+left": "zoom sequencer",
    "cmd+right": "zoom sequencer",
    "ctrl+shift+z": "zoom to fit locators",
    space: "play",
    "shift+space": "play from selection",
    "*": "record/record toggle",
    "shift+*": "record/record repeat",
    "cmd+.": "discard recording + go to previous position",
    c: "cycle mode",
    u: "set cycle area to rounded selection",
    "cmd+u": "set cycle area to exact selection",
    k: "metronome",
    "shift+k": "count-in",
    "=": "tuner",
    "ctrl+i": "track input monitor toggle",
    "ctrl+shift+cmd+s": "toggle solo’ed tracks",
    "ctrl+s":
      "solo selected regions + shift to add / toggle solo’ed regions / solo selected regions",
    "ctrl+m":
      "mute selected regions + shift to add / mute selected regions/notes",
    "ctrl+alt+cmd+v": "varispeed",
    "ctrl+shift+cmd+l": "low latency mode",
    "alt+g": "global tracks view settings",
    "‘": "show marker track only",
    "alt+'": "add new marker",
    "shift+'": "rename marker",
    "alt+backspace": "delete marker",
    "cmd+r": "repeat part",
    "ctrl+cmd+r": "repeat section between locators",
    q: "quantize",
    "cmd+g": "snap to grid",
    "ctrl+b": "bounce regions in place",
    h: "toggle hide view",
    "ctrl+alt+cmd+home": "set next higher division",
    "ctrl+alt+cmd+end": "set next lower division",
    "ctrl+alt+cmd+pageup": "set quantize to previous value",
    "ctrl+alt+cmd+pagedown": "set quantize to next value",
    "alt+cmd+n": "new track window",
    "shift+enter": "rename track",
    "shift+n": "rename region",
    "alt+shift+n": "name regions by track name",
    j: "join regions per track",
    "cmd+j": "join regions on separate tracks / join notes",
    "cmd+t": "split regions/notes at playhead",
    "alt+up": "move note up +1",
    "alt+down": "move note up -1",
    "shift+alt+up": "move note up +12",
    "shift+alt+down": "move note up -12",
    "alt+left": "nudge note left",
    "alt+right": "nudge note right",
    "shift+m": "select all muted notes",
    "shift+p": "select notes of same sub position",
    "shift+d": "select notes with same articulation",
    "shift+i": "invert selection",
    f1: "remove overlaps",
    f2: "force legato",
    f3: "midi in toggle",
    "ctrl+x": "strip silence",
    "ctrl+alt+cmd+n": "normalize region gain",
    "ctrl+n": "normalize audio in audio file editor",
    "ctrl+shift+r": "reverse audio in audio file editor",
    "ctrl+shift+t": "trim audio in audio file editor",
    "ctrl+e": "convert region to sampler track",
    "ctrl+t": "transient editing mode in audio file editor",
    "alt+cmd+f": "convert audio regions to independent copies",
    "cmd+y": "autoflow automation lanes",
    ctrl: "lock x-axis when editing point",
    "ctrl+cmd+backspace": "delete visible automation on selected track",
    "ctrl+shift+cmd+backspace": "delete all automation on selected track",
    "ctrl+cmd+a": "toggle read/latch automation",
    "ctrl+alt+cmd+g": "snap automation points",
  },
};

export default app;
