import { AppParams } from "~/types";

const app = {
  id: "missive",
  name: "Missive",
  icon: "/app-icons/missive.png",
  homepage: "https://missiveapp.com",
  description:
    "Missive is a collaborative email app that lets you manage Facebook, SMS, and Twitter accounts from a single place.",
  globals: {},
  shortcuts: {
    down: "next item",
    up: "previous item",
    "alt+up": "first item",
    "alt+down": "last item",
    right: "open item",
    left: "collapse item",
    tab: "next scope",
    "shift+tab": "previous scope",
    pgup: "scroll up",
    pgdn: "scroll down",
    "shift+up": "select next conversation",
    "shift+down": "select previous conversation",
    "alt+shift+up": "select until first conversation",
    "alt+shift+down": "select until last conversation",
    "cmdorctrl+a": "select all conversations",
    "cmdorctrl+n": "compose new email / create event",
    "cmdorctrl+shift+n": "create new conversation",
    "cmdorctrl+f": "search",
    "cmdorctrl+shift+c": "focus comment box / add cc recipients",
    "cmdorctrl+shift+x": "focus task box",
    space: "preview item",
    "cmdorctrl+up": "edit previous comment",
    "cmdorctrl+shift+y": "set a status",
    "cmdorctrl+.": "open conversation contextual menu",
    "cmdorctrl+g": "open more menu",
    "cmdorctrl+l": "open location / go to date",
    "cmdorctrl+,": "open preferences",
    "cmdorctrl+shift+,": "open contacts",
    "cmdorctrl+alt+s": "toggle right sidebar",
    "cmdorctrl+alt+n": "main right sidebar action",
    "cmdorctrl+alt+r": "reload",
    "cmdorctrl+shift+l": "label as...",
    "cmdorctrl+alt+l": "move to...",
    "cmdorctrl+shift+k": "assign",
    "cmdorctrl+shift+j": "snooze",
    "cmdorctrl+shift+s": "toggle star",
    "cmdorctrl+shift+m": "toggle watch",
    "cmdorctrl+r": "reply all / refresh",
    "cmdorctrl+shift+r": "reply",
    "cmdorctrl+shift+f": "forward",
    "cmdorctrl+shift+d": "open or focus draft",
    "cmdorctrl+p": "print",
    "cmdorctrl+o": "open in new window",
    "cmdorctrl+z": "undo last action",
    "cmdorctrl+shift+z": "redo last action",
    "cmdorctrl+shift+i": "mark as read",
    "cmdorctrl+shift+u": "mark as unread",
    "cmdorctrl+shift+=": "mark as important / increase text size",
    "cmdorctrl+minus": "mark as not important",
    "cmdorctrl+shift+right": "expand entire conversation",
    "cmdorctrl+shift+left": "collapse entire conversation",
    "cmdorctrl+shift+'": "toggle message quote",
    "cmdorctrl+shift+p": "pin to sidebar",
    "cmdorctrl+shift+g": "merge...",
    "cmdorctrl+enter": "send",
    "cmdorctrl+shift+enter": "send and archive",
    "cmdorctrl+d": "discard draft",
    "cmdorctrl+shift+b": "add bcc recipients",
    "cmdorctrl+k": "insert a link",
    "cmdorctrl+shift+o": "open responses",
    "cmdorctrl+shift+minus": "decrease text size",
    "cmdorctrl+b": "bold",
    "cmdorctrl+i": "italic",
    "cmdorctrl+u": "underline",
    "cmdorctrl+shift+7": "numbered list",
    "cmdorctrl+shift+8": "bulleted list",
    "cmdorctrl+[": "decrease indent",
    "cmdorctrl+]": "increase indent",
    enter: "view day",
    t: "today",
    d: "day view",
    w: "week view",
    m: "month view",
    a: "agenda view",
    "cmdorctrl+1": "go to mailbox 1",
    "cmdorctrl+2": "go to mailbox 2",
    "cmdorctrl+3": "go to mailbox 3",
    "cmdorctrl+4": "go to mailbox 4",
    "cmdorctrl+5": "go to mailbox 5",
    "cmdorctrl+6": "go to mailbox 6",
    "cmdorctrl+7": "go to mailbox 7",
    "cmdorctrl+8": "go to mailbox 8",
    "cmdorctrl+9": "go to mailbox 9",
  },
} as AppParams;

export default app;
