import { AppParams } from "~/types";

const app = {
  id: "msteams",
  name: "Microsoft Teams",
  icon: "/app-icons/msteams.png",
  homepage: "https://www.microsoft.com/microsoft-teams",
  description:
    "Microsoft Teams is a messaging app for organizations. It is a workspace for real-time collaboration and communication, meetings, file and app sharing.",
  globals: {},
  shortcuts: {
    "cmdorctrl+.": "show keyboard shortcuts",
    "cmdorctrl+e": "go to search",
    "cmdorctrl+/": "show commands",
    "cmdorctrl+g": "goto",
    "cmdorctrl+n": "start new chat",
    "cmdorctrl+,": "open settings",
    f1: "open help",
    esc: "close",
    "cmdorctrl+=": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+0": "return to default zoom",
    "cmdorctrl+1": "open activity",
    "cmdorctrl+2": "open chat",
    "cmdorctrl+3": "open teams",
    "cmdorctrl+4": "open calendar",
    "cmdorctrl+5": "open calls",
    "cmdorctrl+6": "open files",
    "alt+up": "go to previous list item",
    "alt+down": "go to next list item",
    "cmdorctrl+shift+up": "move selected team up",
    "cmdorctrl+shift+down": "move selected team down",
    "cmdorctrl+shift+f6": "go to the previous section",
    "cmdorctrl+f6": "go to the next section",
    "alt+shift+c": "go to compose box",
    "cmdorctrl+shift+x": "expand compose box",
    "cmdorctrl+enter": "send, in the expanded compose box",
    "cmdorctrl+o": "attach a file",
    "shift+enter": "start a new line",
    "alt+shift+r": "reply to thread",
    "cmdorctrl+shift+a": "accept video call",
    "cmdorctrl+shift+s": "accept audio call",
    "cmdorctrl+shift+d": "decline call",
    "cmdorctrl+shift+c": "start audio call",
    "cmdorctrl+shift+u": "start video call",
    "cmdorctrl+shift+m": "toggle mute",
    "cmdorctrl+shift+o": "toggle video",
    "cmdorctrl+shift+f": "toggle fullscreen",
    "cmdorctrl+shift+space": "go to sharing toolbar",
  },
} as AppParams;

export default app;
