import { AppParams } from "~/types";

const app = {
  id: "numbers",
  name: "Numbers",
  icon: "/app-icons/numbers.png",
  homepage: "https://www.apple.com/numbers/",
  description: "Create and edit spreadsheets.",
  globals: {},
  shortcuts: {
    "cmd+m": "minimize the window",
    "alt+cmd+m": "minimize all windows",
    "cmd+h": "hide numbers",
    "alt+cmd+h": "hide all other app windows",
    "ctrl+cmd+f": "enter full-screen mode",
    "cmd+>": "zoom in",
    "cmd+<": "zoom out",
    "shift+cmd+0": "zoom to selection",
    "cmd+0": "return to normal size",
    "cmd+,": "open numbers preferences",
    "shift+cmd+?": "open the numbers user guide",
    "cmd+w": "close the window",
    "alt+cmd+w": "close all windows",
    "cmd+q": "quit numbers",
    "alt+cmd+q": "quit numbers with windows open",
    "cmd+n": "open the template chooser",
    escape: "close the template chooser",
    "fn+fn": "start dictation",
    "cmd+o": "open an existing spreadsheet",
    "cmd+s": "save a spreadsheet",
    "alt+shift+cmd+s": "save a spreadsheet as",
    "shift+cmd+s": "duplicate a spreadsheet",
    "cmd+p": "print a spreadsheet",
    "cmd+z": "undo",
    "shift+cmd+z": "redo",
    left: "move left one character",
    right: "move right one character",
    "ctrl+b": "move back one character",
    "ctrl+f": "move forward one character",
    up: "move up one line",
    down: "move down one line",
    "ctrl+alt+b": "move to the start of the current or previous word",
    "ctrl+alt+f": "move to the end of the current or previous word",
    "cmd+up": "move to the start of the text area",
    "cmd+down": "move to the end of the text area",
    pageup: "scroll up the sheet",
    pagedown: "scroll down the sheet",
    home: "scroll to the start of the sheet",
    "fn+up": "scroll to the start of the sheet",
    end: "scroll to the end of the sheet",
    "fn+down": "scroll to the end of the sheet",
    "ctrl+v": "go down a page",
    tab: "select the next cell",
    "shift+tab": "select the previous cell",
    enter: "select the cell below",
    "shift+enter": "select the cell above",
    "alt+enter": "select the first cell in a table",
    "cmd+enter": "select a table from a selected cell",
    "alt+cmd+enter": "select the rows that intersect the selection",
    "ctrl+cmd+enter": "select the columns that intersect the selection",
    "shift+up": "select additional rows",
    "shift+down": "select additional rows",
    "shift+right": "select additional columns",
    "shift+left": "select additional columns",
    "cmd+a": "select all content in a table",
    "alt+up": "insert a row above the selected cells",
    "alt+down": "insert a row below the selected cells",
    "alt+right": "insert a column to the right of selected cells",
    "alt+left": "insert a column to the left of selected cells",
    "alt+cmd+delete": "delete selected rows",
    "ctrl+cmd+delete": "delete selected columns",
    "shift+cmd+r": "apply sorting rules",
    "shift+cmd+f": "turn on or off filters",
    "cmd+\\": "turn on autofill mode",
    "ctrl+cmd+m": "merge selected cells",
    "ctrl+shift+cmd+m": "unmerge selected cells",
  },
} as AppParams;

export default app;
