const app = {
  id: "obsidian",
  name: "Obsidian",
  icon: "/app-icons/obsidian.png",
  homepage: "https://obsidian.md",
  description:
    'Obsidian is a note-taking and knowledge management software tool that is designed for individuals who want to create a digital knowledge base and connect ideas and information in a structured way. It is often described as a "second brain" or "thought organizer" because it allows users to build a network of interconnected notes, thoughts, and references.',
  shortcuts: {
    "cmdOrCtrl+W": "Close current tab",
    "cmdOrCtrl+shift+W": "Close window",
    "CmdOrCtrl+P": "Open command palette",
    "CmdOrCtrl+N": "Create new note",
    "CmdOrCtrl+shift+N": "Create new note to the right",
    "CmdOrCtrl+D": "Delete paragraph",
    "Alt+Enter": "Follow link under cursor",
    "CmdOrCtrl+9": "go to last tab",
    "Ctrl+tab": "Go to next tab",
    "CmdOrCtrl+shift+]": "Go to next tab",
    "Ctrl+shift+tab": "Go to previous tab",
    "CmdOrCtrl+shift+[": "Go to previous tab",
    "CmdOrCtrl+1": "go to tab #1",
    "CmdOrCtrl+2": "go to tab #2",
    "CmdOrCtrl+3": "go to tab #3",
    "CmdOrCtrl+4": "go to tab #4",
    "CmdOrCtrl+5": "go to tab #5",
    "CmdOrCtrl+6": "go to tab #6",
    "CmdOrCtrl+7": "go to tab #7",
    "CmdOrCtrl+8": "go to tab #8",
    "CmdOrCtrl+G": "Open graph view",
    "CmdOrCtrl+K": "Insert markdown link",
    "Alt+CmdOrCtrl+left": "Navigate back",
    "Alt+CmdOrCtrl+right": "Navigate forward",
    "CmdOrCtrl+T": "New tab",
    F1: "Open help",
    "CmdOrCtrl+Enter": "Open link under cursor in new tab",
    "Alt+CmdOrCtrl+shift+Enter": "Open link under cursor in new window",
    "Alt+CmdOrCtrl+Enter": "Open link under cursor to the right",
    "CmdOrCtrl+,": "Open settings",
    "CmdOrCtrl+O": "Open quick switcher",
    F2: "Rename file",
    "CmdOrCtrl+S": "save current file",
    "CmdOrCtrl+alt+F": "Search & replace in current file",
    "CmdOrCtrl+F": "Search current file",
    "CmdOrCtrl+shift+F": "Search in all files",
    "CmdOrCtrl+B": "toggle bold",
    "CmdOrCtrl+L": "toggle checkbox status",
    "CmdOrCtrl+/": "toggle comment",
    "CmdOrCtrl+I": "toggle Italics",
    "CmdOrCtrl+E": "toggle reading view",
    "CmdOrCtrl+shift+I": "Undo close tab",
  },
};

export { app };
