import { AppParams } from "~/types";

const app = {
  id: "opera",
  name: "Opera",
  icon: "/app-icons/opera.png",
  homepage: "https://www.opera.com/",
  description: "Opera is a multi-platform web browser based on Chromium.",
  globals: {},
  shortcuts: {
    "cmdorctrl+j": "open downloads page",
    "cmdorctrl+shift+e": "open extensions page",
    "cmdorctrl+h": "open history page",
    "cmdorctrl+o": "open local file",
    "cmdorctrl+l": "focus address bar",
    "cmdorctrl+,": "open preferences (settings) page",
    "cmdorctrl+p": "print current page",
    "cmdorctrl+shift+x": "quit opera",
    "cmdorctrl+s": "save a page locally",
    f1: "open help",
    "cmdorctrl+f": "find on page",
    "cmdorctrl+g": "find next",
    "cmdorctrl+shift+g": "find previous",
    tab: "cycle forward through page elements",
    "shift+tab": "cycle back through page elements",
    "cmdorctrl+right": "go forward one page",
    "cmdorctrl+left": "go back one page",
    "cmdorctrl+down": "go to bottom of page",
    end: "go to bottom of page",
    "cmdorctrl+up": "go to top of page",
    home: "go to top of page",
    space: "page down",
    "shift+space": "page up",
    "cmdorctrl+r": "reload the current page",
    "cmdorctrl+u": "view current page source",
    "cmdorctrl+w": "close current tab",
    "alt+f4": "close current window",
    "ctrl+tab": "cycle forward through open tabs",
    "shift+ctrl+tab": "cycle back through open tabs",
    "cmdorctrl+`": "cycle through open windows",
    "alt+tab": "cycle through open windows",
    "cmdorctrl+m": "minimize a window",
    "win+m": "minimize a window",
    "cmdorctrl+t": "open new tab",
    "cmdorctrl+n": "open new window",
    "cmdorctrl+shift+n": "open new private window",
    "cmdorctrl+shift+t": "reopen last closed tab",
    "ctrl+m": "toggle tab menu",
    "ctrl+`": "view previous active tab",
    "cmdorctrl+c": "copy",
    "cmdorctrl+x": "cut",
    "cmdorctrl+v": "paste",
    "cmdorctrl+a": "select all",
    "cmdorctrl+z": "undo",
    "cmdorctrl+shift+z": "redo",
    "ctrl+cmdorctrl+f": "enter full-screen mode",
    f11: "enter full-screen mode",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+0": "reset zoom to 100%",
    "1": "cycle left through tabs",
    "2": "cycle right through tabs",
    "/": "find on page",
    z: "go back one page",
    x: "go forward one page",
    plus: "zoom in",
    "8": "zoom in more",
    minus: "zoom out",
    "9": "zoom out more",
    "7": "reset zoom to 100%",
    "6": "reset zoom to 100%",
  },
} as AppParams;

export default app;
