const app = {
  id: "origami",
  name: "Origami Studio",
  icon: "/app-icons/origami.png",
  homepage: "https://origami.design",
  description:
    "Origami Studio is a free design tool built by Facebook designers for creating interactive UI prototypes.",
  globals: {},
  shortcuts: {
    "alt+enter": "insert patch",
    "cmdorctrl+enter": "insert layer",
    "cmdorctrl+/": "documentation",
    i: "interaction",
    s: "switch",
    a: "pop animation",
    c: "classic animation",
    t: "transition",
    k: "keyboard",
    d: "delay",
    "shift+i": "option switch",
    o: "option picker",
    x: "splitter",
    w: "wireless broadcaster",
    "shift+w": "wireless receiver",
    u: "pulse",
    plus: "add",
    minus: "minus",
    "*": "multiply",
    "/": "divide",
    "%": "modulus or remainder",
    "shift+a": "and logic",
    "shift+o": "or logic",
    "shift+n": "not logic",
    e: "equals",
    ">": "greater than",
    "<": "less than",
    "shift+r": "progress",
    r: "reverse progress",
    "shift+enter": "rename patch / rename layer",
    "cmdorctrl+[": "align patches left",
    "cmdorctrl+]": "align patches right",
    "cmdorctrl+shift+[": "align patches top",
    "cmdorctrl+shift+]": "align patches bottom",
    "alt+ctrl+c": "insert comment around patches",
    "cmdorctrl+ctrl+g": "create patch component / create layer component",
    "alt+p": "publish input or output port",
    "alt+down": "enter patch component / decrease number by 0.1",
    "alt+up": "exit patch component / increase number by 0.1",
    "cmdorctrl+shift+i": "patch info / layer info",
    "cmdorctrl+alt+l": "add patch component to user library",
    "cmdorctrl+alt+shift+l": "add patch component to other library",
    "cmdorctrl+shift+h": "hide or show layer",
    "cmdorctrl+shift+l": "lock or unlock layer",
    "cmdorctrl+alt+up": "bring forward",
    "cmdorctrl+alt+down": "send backwards",
    "cmdorctrl+alt+shift+up": "bring to front",
    "cmdorctrl+alt+shift+down": "send to back",
    "cmdorctrl+alt+m": "mask layer",
    "cmdorctrl+alt+shift+m": "add to mask",
    "cmdorctrl+g": "group layers",
    "cmdorctrl+shift+g": "ungroup layers",
    "cmdorctrl+r": "restart prototype",
    "alt+d": "toggle device",
    "alt+h": "toggle hand",
    "cmdorctrl+alt+f": "mini viewer",
    "cmdorctrl+shift+f": "fullscreen viewer",
    "cmdorctrl+alt+0": "1:1 viewer",
    up: "increase number by one",
    down: "decrease number by one",
    "shift+up": "increase number by 10",
    "shift+down": "decrease number by 10",
  },
};

export default app;
