const app = {
  id: "phpstorm",
  name: "PhpStorm",
  icon: "/app-icons/phpstorm.png",
  homepage: "https://www.jetbrains.com/phpstorm/",
  description:
    "PhpStorm is a cross-platform IDE for PHP, built on JetBrains' IntelliJ IDEA platform.",
  globals: {},
  shortcuts: {
    "cmdorctrl+space": "basic code completion",
    "alt+enter": "show intention actions and quick-fixes",
    "cmdorctrl+p": "parameter info (within method call arguments)",
    "cmdorctrl+q": "quick documentation lookup",
    "alt+ins": "generate code... (getters, setters, constructors)",
    "cmdorctrl+o": "override methods",
    "cmdorctrl+i": "implement methods",
    "cmdorctrl+alt+t": "surround with...(if..else, try..catch, for, etc.)",
    "cmdorctrl+/": "comment/uncomment with line comment",
    "cmdorctrl+shift+/": "comment/uncomment with block comment",
    "cmdorctrl+w": "select successively increasing code blocks",
    "cmdorctrl+shift+w": "decrease current selection to previous state",
    "cmdorctrl+alt+l": "reformat code",
    "cmdorctrl+alt+i": "auto-indent line(s)",
    "cmdorctrl+d": "duplicate current line or selected block",
    "cmdorctrl+y": "delete line at caret",
    "cmdorctrl+shift+j": "smart line join (html and javascript only)",
    "cmdorctrl+enter": "smart line split (html and javascript only)",
    "shift+enter": "start a new line",
    "cmdorctrl+shift+u": "toggle case for word at caret or selected block",
    "cmdorctrl+shift+[": "select till code block start",
    "cmdorctrl+shift+]": "select till code block end",
    "cmdorctrl+delete": "delete to word end",
    "cmdorctrl+backspace": "delete to word start",
    "cmdorctrl+plus": "expand code block",
    "cmdorctrl+minus": "collapse code block",
    "cmdorctrl+f4": "close active editor tab",
    "cmdorctrl+shift+v": "paste from history",
    f8: "step over",
    f7: "step into",
    "shift+f8": "step out",
    "alt+f8": "evaluate expression",
    f9: "resume program",
    "cmdorctrl+f8": "toggle breakpoint",
    "cmdorctrl+shift+f8": "view breakpoints",
    "shift+f10": "run",
    "shift+f9": "debug",
    "cmdorctrl+shift+f10": "run context configuration from editor",
    "cmdorctrl+shift+x": "run command line",
    "cmdorctrl+f": "find",
    "cmdorctrl+r": "replace",
    f3: "find next",
    "shift+f3": "find previous",
    "cmdorctrl+shift+f": "find in path",
    "cmdorctrl+shift+r": "replace in path",
    "alt+f7": "find usages",
    "cmdorctrl+f7": "find usages in file",
    "cmdorctrl+shift+f7": "highlight usages in file",
    "cmdorctrl+alt+f7": "show usages",
    "cmdorctrl+n": "go to class",
    "cmdorctrl+shift+n": "go to file",
    "cmdorctrl+shift+alt+n": "go to symbol",
    "cmdorctrl+g": "go to line",
    "alt+left": "go to previous editor tab",
    "alt+right": "go to next editor tab",
    esc: "go to editor (from tool window)",
    "cmdorctrl+e": "recent files popup",
    "cmdorctrl+alt+left": "navigate back",
    "cmdorctrl+alt+right": "navigate forward",
    "cmdorctrl+shift+backspace": "navigate to last edit location",
    "alt+f1": "select current file or symbol in any view",
    "cmdorctrl+b": "go to declaration",
    "cmdorctrl+alt+b": "go to implementation(s)",
    "cmdorctrl+shift+i": "open quick definition lookup",
    "cmdorctrl+shift+b": "go to type declaration",
    "cmdorctrl+u": "go to super-method/super-class",
    "alt+up": "go to previous method",
    "alt+down": "go to next method",
    "cmdorctrl+]": "move to code block end",
    "cmdorctrl+[": "move to code block start",
    f2: "next highlighted error",
    "shift+f2": "previous highlighted error",
    f4: "edit/view source",
    f5: "copy",
    f6: "move",
    "alt+del": "safe delete",
    "shift+f6": "rename",
    "cmdorctrl+alt+n": "inline variable",
    "cmdorctrl+alt+m": "extract method/variable/field/constant",
    "cmdorctrl+alt+v": "extract method/variable/field/constant",
    "cmdorctrl+alt+f": "extract method/variable/field/constant",
    "cmdorctrl+alt+c": "extract method/variable/field/constant",
    "cmdorctrl+alt+shift+t": "refactor this (shows all available refactorings)",
    "alt+`": "vcs quick popup",
    "cmdorctrl+k": "commit project to vcs",
    "cmdorctrl+t": "update project from vcs",
    "alt+shift+c": "view recent changes",
    "shift+shift": "search everywhere",
    "cmdorctrl+shift+a": "find action / find action",
    "cmdorctrl+alt+f11": "toggle full screen mode",
    "cmdorctrl+shift+f12": "toggle maximizing editor",
    "alt+shift+f": "add to favorites",
    "alt+shift+i": "inspect current file with current profile",
    "cmdorctrl+alt+s": "open settings dialog",
    "cmdorctrl+tab": "switch between tabs and tool window",
    "cmdorctrl+j": "insert live template",
  },
};

export default app;
