import { AppParams } from "~/types";

const app = {
  id: "pitch",
  name: "Pitch",
  icon: "/app-icons/pitch.png",
  homepage: "https://pitch.com",
  description: "Pitch is a collaborative presentation software.",
  globals: {},
  shortcuts: {
    "cmdorctrl+k": "access the quick menu",
    n: "new presentation",
    g: "go to workspace",
    o: "open presentation",
    t: "create template / normal text",
    f: "create folder",
    "shift+n": "open a new presentation",
    h: "headline",
    i: "image",
    s: "shape",
    l: "list",
    "s+r": "rectangle shape",
    "s+c": "circle shape",
    "s+l": "line shape",
    "s+a": "arrow shape",
    "s+d": "diamond shape",
    "s+s": "star shape",
    "s+t": "triangle shape",
    "l+b": "bullet list",
    "l+n": "numbered list",
    "l+c": "check list",
    "cmdorctrl+shift+f": "enter the player",
    "cmdorctrl+shift+m": "add comment",
    "!+t": "set slide status to 'to do'",
    "!+i": "set slide status to 'in progress'",
    "!+d": "set slide status to 'done'",
    a: "assign to",
    "alt+t": "apply style",
    j: "jump to slide",
  },
} as AppParams;

export default app;
