import { AppParams } from "~/types";

const app = {
  id: "pocket",
  name: "Pocket",
  icon: "/app-icons/pocket.png",
  homepage: "https://getpocket.com",
  description:
    "Pocket is a service that lets you save what you find on the web to watch and read on any device, anytime.",
  globals: {},
  shortcuts: {
    "g+l": "go to my list",
    "g+a": "go to archive",
    "g+f": "go to favorites",
    "g+r": "go to articles",
    "g+h": "go to highlights",
    "g+v": "go to videos",
    "g+t": "go to all tags",
    "g+s": "go to search",
    "g+b": "bulk edit",
    "g+u": "save a url",
    "s+n": "sort by newest",
    "s+o": "sort by oldest",
    "v+l": "list view",
    "v+g": "grid view",
    "v+d": "detail view",
    "c+l": "change to light theme",
    "c+d": "change to dark theme",
    "c+s": "change to sepia theme",
    "?": "open help overlay",
    o: "open the original in a new tab / view the original",
    a: "archive the selected item",
    f: "favorite the selected item / favorite the item",
    t: "tag the selected item / archive the item",
    d: "delete the selected item / edit tags",
    x: "select item in bulk edit",
    j: "select the next item",
    k: "select the previous item",
    "cmdorctrl+=": "increase the font size",
    "cmdorctrl+minus": "decrease the font size",
    b: "toggle full screen mode",
    "alt+=": "increase the column width (premium only)",
    "alt+minus": "decrease the column width (premium only)",
  },
} as AppParams;

export default app;
