import { AppParams } from "~/types";

const app = {
  id: "protoio",
  name: "Proto.io",
  icon: "/app-icons/protoio.png",
  homepage: "https://www.proto.io/",
  description:
    "Proto.io is an application prototyping platform launched in 2011, designed to prototype for anything with a screen interface, utilizing a drag and drop user interface (UI), not requiring coding.",
  globals: {},
  shortcuts: {
    "cmdorctrl+f": "find",
    "cmdorctrl+k": "show keyboard shortcuts",
    "cmdorctrl+s": "save",
    esc: "close modal windows",
    "shift+p": "preview",
    "cmdorctrl+shift+s": "save and preview",
    "cmdorctrl+z": "undo",
    "cmdorctrl+shift+z": "redo",
    "cmdorctrl+[": "go to previous canvas",
    "cmdorctrl+]": "go to next canvas",
    "cmdorctrl+a": "select all",
    "cmdorctrl+x": "cut",
    "cmdorctrl+c": "copy",
    "cmdorctrl+v": "paste",
    "cmdorctrl+d": "duplicate",
    backspace: "delete",
    "cmdorctrl+'": "toggle grid",
    "cmdorctrl+\\": "toggle grid system",
    "cmdorctrl+;": "toggle custom guides",
    "cmdorctrl+l": "toggle smart guides",
    alt: "toggle snap to grid on drag or resize",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+0": "zoom to 100%",
    "cmdorctrl+1": "fit to screen",
    "cmdorctrl+2":
      "zoom to selected layers, or fit all layers if none selected",
    "cmdorctrl+3":
      "center selected layer(s) in the canvas, or center on screen if none selected",
    "cmdorctrl+right": "toggle right pane",
    "cmdorctrl+left": "toggle left pane",
    space: "pan canvas while keydown / play or pause state transition",
    "cmdorctrl+up": "bring to front",
    "cmdorctrl+down": "send to back",
    "cmdorctrl+shift+up": "bring forward",
    "cmdorctrl+shift+down": "send backwards",
    shift: "lock drag direction (hold while dragging)",
    r: "insert rectangle",
    o: "insert oval",
    l: "insert line",
    t: "insert text",
    i: "insert interaction area",
    enter: "enter selected container",
    "cmdorctrl+g": "group selected",
    "cmdorctrl+shift+g": "ungroup selected",
    ".": "forward state transition",
    ",": "rewind state transition",
  },
} as AppParams;

export default app;
