const app = {
  id: "putty",
  name: "PuTTy",
  icon: "/app-icons/putty.png",
  homepage: "https://www.putty.org/",
  description:
    "PuTTY is a free and open-source terminal emulator, serial console, and network file transfer application. It supports several network protocols, including SCP, SSH, Telnet, rlogin, raw socket connection, and can also connect to a serial port.",
  globals: {},
  shortcuts: {
    "cmdorctrl+a": "jump to the start of the line",
    "cmdorctrl+b": "move back a character",
    "cmdorctrl+c": "terminal the command",
    "cmdorctrl+d": "delete from under the cursor",
    "cmdorctrl+e": "jump to the end of the line",
    "cmdorctrl+f": "move forward a character",
    "cmdorctrl+k": "delete to end-of-line",
    "cmdorctrl+l": "clear the screen",
    "cmdorctrl+r": "search the history backwards",
    "cmdorctrl+shift+r": "search the history backwards with multi occurrence",
    "cmdorctrl+u": "delete backward from cursor",
    "cmdorctrl+x+x": "move between end-of-line and current cursor position",
    "cmdorctrl+x+@": "show possible hostname completions",
    "cmdorctrl+z": "suspend or stop the command",
    "alt+left": "move to the first line in the history",
    "alt+right": "move to the last line in the history",
    "alt+?": "show current completion list",
    "alt+*": "insert all possible completions",
    "alt+/": "attempt to complete filename",
    "alt+.": "yank last argument to previous command",
    "alt+b": "move backward",
    "alt+c": "capitalize the word",
    "alt+d": "delete word",
    "alt+f": "move forward",
    "alt+l": "make word lowercase",
    "alt+n": "search the history forwards non-incremental",
    "alt+p": "search the history backwards non-incremental",
    "alt+r": "recall command",
    "alt+t": "move words around",
    "alt+u": "make word uppercase",
    "alt+backspace": "delete backwards from the cursor",
  },
};

export default app;
