import { AppParams } from "~/types";

const app = {
  id: "pycharm",
  name: "PyCharm",
  icon: "/app-icons/pycharm.png",
  homepage: "https://www.jetbrains.com/pycharm/",
  description:
    "PyCharm is an integrated development environment (IDE) used in computer programming, specifically for the Python language.",
  globals: {},
  shortcuts: {
    "shift+shift": "search everywhere",
    "cmdorctrl+e": "view recent files",
    "cmdorctrl+shift+n": "go to the file directly",
    "cmdorctrl+/": "comment out a line or block of code",
    "cmdorctrl+shift+/": "comment out a line or block of code",
    "cmdorctrl+shift+f": "search in the entire file",
    "cmdorctrl+f": "search in a specific file",
    "alt+shift+c": "view recent changes",
    "cmdorctrl+d": "duplicate the selected block or line at caret",
    "cmdorctrl+g":
      "navigate to a line with the specified number in the current file",
    "cmdorctrl+z": "undo the operation done",
    "cmdorctrl+shift+z": "redo the operation done",
    "cmdorctrl+w": "extend your selection",
    "cmdorctrl+a": "select all data or lines",
    "cmdorctrl+shift+j": "join lines of code",
    "cmdorctrl+n": "jump to a class in the project with specified name",
    "cmdorctrl+s": "save all the files and settings",
    "cmdorctrl+v": "paste from the clipboard",
    "cmdorctrl+r": "call the replace text dialogue box",
    "cmdorctrl+y": "delete a word from caret location to the end of word",
    "cmdorctrl+pgup": "move down to the bottom of the page",
    "cmdorctrl+pgdn": "move to the top of the page",
    "cmdorctrl+down": "move line at caret down by one line",
    "cmdorctrl+left": "move to previous word",
    "cmdorctrl+right": "move to next word",
    "cmdorctrl+up": "scroll up",
    "cmdorctrl+home": "move to the beginning of text",
    "cmdorctrl+end": "move to the end of text",
    "cmdorctrl+enter": "split line or open item",
    "cmdorctrl+backspace": "delete to word start",
    "shift+f10": "run",
    "shift+f9": "debug",
    "alt+5": "activate debug window",
    "alt+f8": "evaluate arbitrary expression",
    "shift+alt+f10": "choose and run a configuration file",
    f7: "step to the next line executed",
    f8: "step to the next line in this file",
    f9: "resume program execution",
    "shift+f2": "terminate a debugging session",
    "cmdorctrl+shift+f8": "view and manage breakpoints",
    "cmdorctrl+alt+o": "optimize imports",
    "shift+f6": "rename variable",
    "cmdorctrl+f12": "shows the file structure",
    "alt+cmdorctrl+f4": "open image in external editor",
    "shift+tab": "open an unindent tab",
  },
} as AppParams;

export default app;
