const app = {
  id: "safari",
  name: "Safari",
  icon: "/app-icons/safari.png",
  homepage: "https://apple.com/safari",
  description:
    "Safari is a web browser developed by Apple. It is the default web browser for Apple's macOS and iOS operating systems, as well as for iPadOS. Safari is known for its speed, efficiency, and seamless integration with Apple's ecosystem of devices and services. It's designed to provide users with a fast and secure web browsing experience.",
  shortcuts: {
    "Shift+up": "Scroll up",
    "Shift+down": "Scroll down",
    "Shift+left": "Scroll left",
    "Shift+right": "Scroll right",
    "Alt+up": "Scroll up in larger increments",
    "Alt+down": "Scroll down in larger increments",
    "Alt+left": "Scroll left in larger increments",
    "Alt+right": "Scroll right in larger increments",
    Space: "Scroll down a screen",
    "Shift+Space": "Scroll up a screen",
    "CmdOrCtrl+up": "Scroll to the top-left corner of the page",
    "CmdOrCtrl+down": "Scroll to the bottom-left corner of the page",
    "CmdOrCtrl+F": "Search the current webpage",
    Esc: "While typing in the Smart Search field, restore the current webpage address",
    "CmdOrCtrl+L": "Select the Smart Search field",
    "CmdOrCtrl+P": "Print the current webpage",
    "CmdOrCtrl+C": "Copy the selected item",
    "CmdOrCtrl+V": "Paste the most recently copied item",
    "Shift+CmdOrCtrl+\\": "Show tab overview",
    "CmdOrCtrl+Return": "Open a page in a new tab",
    "Shift+CmdOrCtrl+Return":
      "Open a page in a new tab, and make that tab the active tab",
    "Ctrl+Tab": "Go to the next tab",
    "Shift+CmdOrCtrl+]": "Go to the next tab",
    "Ctrl+Shift+Tab": "Go to the previous tab",
    "Shift+CmdOrCtrl+[": "Go to the previous tab",
    "CmdOrCtrl+1 to CmdOrCtrl+9": "Select one of your first nine tabs",
    "CmdOrCtrl+W": "Close the active tab",
    "Shift+CmdOrCtrl+T": "Reopen the last tab you closed",
    "Shift+CmdOrCtrl+H": "Go to your homepage",
    "CmdOrCtrl+,": "Change Safari preferences",
    "CmdOrCtrl+[": "Go back to the previous webpage",
    "CmdOrCtrl+]": "Go forward to the next webpage",
    "CmdOrCtrl+plus": "Zoom in website content",
    "CmdOrCtrl+minus": "Zoom out website content",
    "CmdOrCtrl+`": "Switch to another Safari window",
    "Ctrl+CmdOrCtrl+2": "Show or Hide the Reading List sidebar",
    "Shift+CmdOrCtrl+D": "Add the current page",
    "Shift+CmdOrCtrl+R": "Open Reader",
    "Ctrl+CmdOrCtrl+1": "Show or Hide the Bookmarks sidebar",
    Return: "Finish editing a bookmark name",
  },
};

export default app;
