const app = {
  id: "safari",
  name: "Safari",
  icon: "/app-icons/safari.png",
  homepage: "https://apple.com/safari",
  shortcuts: {
    "Shift+ArrowUp": "Scroll up",
    "Shift+ArrowDown": "Scroll down",
    "Shift+ArrowLeft": "Scroll left",
    "Shift+ArrowRight": "Scroll right",
    "Alt+ArrowUp": "Scroll up in larger increments",
    "Alt+ArrowDown": "Scroll down in larger increments",
    "Alt+ArrowLeft": "Scroll left in larger increments",
    "Alt+ArrowRight": "Scroll right in larger increments",
    PgDown: "Scroll down a screen",
    Space: "Scroll down a screen",
    PgUp: "Scroll up a screen",
    "Shift+Space": "Scroll up a screen",
    "CmdOrCtrl+ArrowUp": "Scroll to the top-left corner of the page",
    "CmdOrCtrl+ArrowDown": "Scroll to the bottom-left corner of the page",
    "CmdOrCtrl+F": "Search the current webpage",
    Esc: "While typing in the Smart Search field, restore the current webpage address",
    "CmdOrCtrl+L": "Select the Smart Search field",
    "CmdOrCtrl+P": "Print the current webpage",
    "CmdOrCtrl+C": "Copy the selected item",
    "CmdOrCtrl+V": "Paste the most recently copied item",
    "Shift+CmdOrCtrl+\\": "Show tab overview",
    "CmdOrCtrl+Return": "Open a page in a new tab",
    "Shift+CmdOrCtrl+Return":
      "Open a page in a new tab, and make that tab the active tab",
    "Ctrl+Tab, Shift+CmdOrCtrl+]": "Go to the next tab",
    "Ctrl+Shift+Tab, Shift+CmdOrCtrl+[-": "Go to the previous tab",
    "CmdOrCtrl+1 to CmdOrCtrl+9": "Select one of your first nine tabs",
    "CmdOrCtrl+W": "Close the active tab",
    "Shift+CmdOrCtrl+T": "Reopen the last tab you closed",
    "Shift+CmdOrCtrl+H": "Go to your homepage",
    "CmdOrCtrl+,": "Change Safari preferences",
    "CmdOrCtrl+[": "Go back to the previous webpage",
    "CmdOrCtrl+]": "Go forward to the next webpage",
    "Hold down the Back or Forward button until the list appears":
      "See a list of your recently visited pages by name",
    "Press Alt and hold down the Back or Forward button until the list appears":
      "See a list of your recently visited pages by web address (URL)",
    "CmdOrCtrl+Plus Sign or CmdOrCtrl+Minus Sign": "Zoom website content",
    "Alt+Choose View > Make Text Bigger or View > Make Text Smaller":
      "Zoom website text",
    "CmdOrCtrl+`": "Switch to another Safari window",
    "Ctrl+CmdOrCtrl+2": "Show or Hide the Reading List sidebar",
    "Shift+CmdOrCtrl+D": "Add the current page",
    "Shift+CmdOrCtrl+R": "Open Reader",
    "Ctrl+CmdOrCtrl+1": "Show or Hide the Bookmarks sidebar",
    Return: "Finish editing a bookmark name",
  },
};

export { app };
