import { AppParams } from "~/types";

const app = {
  id: "sequel-pro",
  name: "Sequel Pro",
  icon: "/app-icons/sequel-pro.png",
  homepage: "https://www.sequelpro.com/",
  description:
    "Sequel Pro is a fast, easy-to-use Mac database management application for working with MySQL & MariaDB databases.",
  globals: {},
  shortcuts: {
    "cmd+1": "table structure",
    "cmd+2": "table content",
    "cmd+3": "table relations",
    "cmd+4": "table info",
    "cmd+5": "custom query",
    "cmd+6": "table triggers",
    "cmd+n": "new window (connection file)",
    "cmd+t": "new tab (connection file)",
    "cmd+shift+a": "add connection to favorites",
    "cmd+o": "open (connection file or SQL file)",
    "cmd+alt+o": "open current connection file in new window",
    "cmd+s": "save (connection file)",
    "cmd+shift+s": "save as (connection file)",
    "cmd+ctrl+s": "save query",
    "cmd+w": "close (connection file)",
    "cmd+alt+w": "close all (connection file)",
    "cmd+p": "print",
    "cmd+shift+i": "import",
    "cmd+shift+k": "show console window",
    "cmd+k": "clear console",
    "ctrl+alt+left": "back in history",
    "ctrl+alt+right": "forward in history",
    "ctrl+tab": "select next tab",
    "ctrl+shift+tab": "select previous tab",
    "ctrl+shift+n": "insert null value",
    "cmd+shift+c": "copy create table syntax",
    "cmd+alt+s": "show create table syntax",
    "cmd+shift+r": "refresh databases",
    "cmd+shift+d": "choose database",
    "cmd+shift+v": "show server variables",
    "cmd+alt+p": "show server processes",
    "cmd+ctrl+r": "refresh tables",
    "cmd+shift+f": "flush privileges",
    "cmd+u": "user accounts...",
    "cmd+c": "copy selection or selected row(s)",
    "cmd+alt+c": "copy selected row(s) with column names",
    "cmd+alt+ctrl+c": "copy selected row(s) as SQL INSERT",
    "cmd+shift+t": "show/hide toolbar",
    "cmd+ctrl+f": "filter table content",
    "cmd+alt+ctrl+f": "filter tables",
    "cmd+alt+ctrl+b": "bundle editor",
    "cmd+alt+ctrl+n": "navigator",
    "ctrl+w": "select current word",
    "ctrl+l": "select current line",
    "cmd+shift+b": "select enclosing brackets",
    "cmd+a": "select all",
    "cmd+alt+a": "add a new field / row",
    delete: "delete selected field / row(s)",
    "cmd+d": "duplicate selected field / row",
    "cmd+alt+r":
      "run all queries (1.0+) / run current query or selection (<=0.9.9.1)",
    "cmd+r": "refresh table contents / run current query or selection",
    "cmd+[": "shift line or selection rightwards",
    "cmd+]": "shift line or selection leftwards",
    "cmd+/": "toggle comment line or selection",
    "cmd+alt+/": "toggle comment current query",
    f5: "spell checker completion (narrow-down list)",
    "ctrl+y": "select current query",
    "ctrl+h": "show MySQL help for current word or selection",
    "cmd+alt+f": "open query favorites popup menu",
    "cmd+alt+y": "open query history popup menu",
    "ctrl+up": "insert previous history item (successively)",
    "ctrl+down": "insert next history item (successively)",
    "cmd+alt+1": "show all database names as completion list",
    "cmd+alt+2": "show all table and view names as completion list",
    "cmd+alt+3":
      "Show all table names from current database as completion list",
  },
} as AppParams;

export default app;
