import { AppParams } from "~/types";

const app = {
  id: "shopify",
  name: "Shopify",
  icon: "/app-icons/shopify.png",
  homepage: "https://www.shopify.com/",
  description:
    "The Shopify platform offers online retailers a suite of services, including payments, marketing, shipping and customer engagement tools.",
  globals: {},
  shortcuts: {
    "?": "keyboard help",
    s: "focus search bar",
    f: "focus filter bar",
    "b+y+e": "log out",
    "m+e": "your profile",
    "o+s": "open the store switcher",
    "a+p": "add product",
    "a+c": "add collection",
    "a+d": "add discount",
    "a+o": "add order",
    "a+u": "add customer",
    "a+b": "add blog post",
    "a+l": "add blog",
    "a+g": "add page",
    "g+h": "go to home",
    "g+p+p": "go to products",
    "g+n": "go to analytics",
    "g+d": "go to discounts",
    "g+a": "go to apps",
    "g+b+c": "go to abandoned checkouts",
    "g+p+i": "go to products, inventory",
    "g+p+g": "go to products, gift cards",
    "g+w+b": "go to online store, blog posts",
    "g+w+t": "go to online store, themes",
    "g+w+d": "go to online store, domains",
    "g+t+l": "go to settings, locations",
    "g+s+p": "go to settings, payments",
    "g+s+s": "go to settings, shipping",
    "g+s+n": "go to settings, notifications",
    "g+s+f": "go to settings, files",
    "g+s+w": "go to settings, online store",
    "g+s+l": "go to settings, sales channels",
    "g+o": "go to orders",
    "g+c": "go to customers",
    "g+m": "go to marketing",
    "g+l": "go to sales channels",
    "g+s": "go to settings",
    "g+p+t": "go to products, transfers",
    "g+p+c": "go to products, collections",
    "g+w+o": "go to online store, overview",
    "g+w+p": "go to online store, pages",
    "g+w+n": "go to online store, navigation",
    "g+t+o": "go to point of sale, overview",
    "g+s+g": "go to settings, general",
    "g+s+c": "go to settings, checkout",
    "g+s+x": "go to settings, taxes",
    "g+s+i": "go to settings, gift cards",
    "g+s+a": "go to settings, account",
    "g+s+t": "go to settings, point of sale",
    "g+s+b": "go to settings, billing",
  },
} as AppParams;

export default app;
