import { AppParams } from "~/types";

const app = {
  id: "sketch",
  name: "Sketch",
  icon: "/app-icons/sketch.png",
  homepage: "https://www.sketch.com/",
  description:
    "Sketch is a vector graphics editor for macOS. It is primarily used for user interface and user experience design of websites and mobile apps and does not include print design features.",
  globals: {},
  shortcuts: {
    "cmd+c": "copy",
    "cmd+x": "cut",
    "cmd+v": "paste",
    "cmd+shift+v": "paste over selection",
    "cmd+shift+n": "new page / new cloud document",
    "fn+up": "previous page",
    "fn+down": "next page",
    "cmd+plus": "zoom in",
    "cmd+minus": "zoom out",
    "ctrl+r": "toggle rulers",
    "ctrl+p": "toggle pixels",
    "ctrl+x": "toggle pixel grid",
    "ctrl+g": "toggle grid",
    "ctrl+l": "toggle layout",
    "ctrl+e": "toggle slices",
    "ctrl+f": "toggle prototyping",
    "cmd+f": "filter in layer list",
    "cmd+ctrl+k": "run custom plugin",
    "cmd+z": "undo",
    "cmd+shift+z": "redo",
    "cmd+n": "new document",
    "cmd+o": "open document",
    "cmd+shift+o": "open cloud document",
    "cmd+w": "close window",
    "cmd+s": "save document",
    "cmd+shift+s": "duplicate document",
    "cmd+shift+alt+s": "save document as...",
    "cmd+shift+p": "page setup",
    "cmd+,": "open preferences window",
    "cmd+h": "hide sketch",
    "cmd+q": "quit sketch",
    "cmd+shift+?": "open the help menu",
    "cmd+p": "open preview window",
    r: "rectangle",
    o: "oval",
    l: "line",
    u: "rounded rectangle",
    v: "vector tool",
    p: "pencil tool",
    t: "text tool",
    a: "artboard tool",
    s: "slice tool",
    h: "hotspot tool",
    "cmd+a": "select all",
    "cmd+shift+a": "select all artboards",
    "fn+right": "select next artboard",
    "fn+left": "select previous artboard",
    "cmd+shift+j": "reveal selection in layer list",
    alt: "display distance between other layers (while hovering) / show all handle control points",
    "cmd+d": "duplicate",
    "cmd+k": "scale layer",
    "cmd+right": "expand by 1px",
    "cmd+down": "expand by 1px",
    "cmd+left": "contract by 1px",
    "cmd+up": "contract by 1px",
    "cmd+shift+right": "expand by 10px",
    "cmd+shift+down": "expand by 10px",
    "cmd+shift+left": "contract by 10px",
    "cmd+shift+up": "contract by 10px",
    "ctrl+alt":
      "show distance to baseline or cap height on text layers (while hovering)",
    enter: "edit layer / selects layer inside group / confirm change",
    esc: "finish editing / selects parent group / clear change",
    "alt+tab":
      "focus x position input field in the inspector / focus inspector",
    del: "delete layer",
    "cmd+alt+c": "copy style",
    "cmd+alt+v": "paste style",
    "ctrl+s": "sync shared style",
    "alt+ctrl+s": "reset shared style",
    w: "add link to artboard",
    f: "toggle fill",
    b: "toggle border",
    "ctrl+c": "pick color",
    "cmd+shift+t": "transform shape",
    "cmd+shift+r": "rotate layer",
    "cmd+ctrl+m": "use as mask",
    "cmd+esc": "return to instance",
    "cmd+alt+u": "union multiple layers",
    "cmd+alt+s": "subtract multiple layers",
    "cmd+alt+i": "intersect multiple layers",
    "cmd+alt+x": "difference multiple layers",
    "cmd+alt+o": "open or close path / convert to outlines",
    tab: "selects next point / select next layer in group / select next field",
    "1": "straight point type",
    "2": "mirrored point type",
    "3": "disconnected point type",
    "4": "asymmetric point type",
    "cmd+shift+alt+v": "paste as rich text",
    "cmd+t": "change typeface",
    "cmd+b": "bold",
    "cmd+i": "italic",
    "cmd+u": "underline",
    "cmd+alt+plus": "increase font size",
    "cmd+alt+minus": "decrease font size",
    "ctrl+alt+l": "increase character spacing",
    "ctrl+alt+t": "decrease character spacing",
    "cmd+shift+[": "align left",
    "cmd+shift+\\": "align center",
    "cmd+shift+]": "align right",
    "cmd+alt+space": "emoji and symbols",
    "shift+enter": "insert a line break",
    "cmd+g": "group",
    "cmd+shift+g": "ungroup",
    "cmd+r": "rename layer",
    "shift+tab": "select previous layer in group / select previous field",
    "cmd+]": "bring forward",
    "cmd+alt+]": "bring to front",
    "cmd+[": "send backward",
    "cmd+alt+[": "send to back",
    "cmd+shift+alt+up": "move up, out of group or artboard",
    "cmd+ctrl+h": "distribute horizontally",
    "cmd+ctrl+v": "distribute vertically",
    "cmd+shift+h": "hide or show layer",
    "cmd+shift+l": "lock or unlock layer",
    "cmd+shift+e": "export",
    "cmd+e": "export selected layer(s)",
    "cmd+0": "zoom to 100%",
    "cmd+1": "zoom to all elements on canvas",
    "cmd+2": "zoom to selected layer(s)",
    "cmd+3": "center selected layer(s) in canvas",
    "shift+`": "temporarily zoom out to 100%",
    "cmd+ctrl+f": "toggle full screen",
    "cmd+alt+1": "show or hide layer list",
    "cmd+alt+2": "show or hide inspector",
    "cmd+.": "enter presentation mode",
    "cmd+alt+t": "show or hide toolbar",
    up: "increase value by 1",
    down: "decrease value by 1",
    "shift+up": "increase value by 10",
    "shift+down": "decrease value by 10",
    "alt+up": "increase value by 0.1",
    "alt+down": "decrease value by 0.1",
    shift: "launch sketch with all plugins disabled (hold on startup)",
    "cmd+ctrl+d": "detach from symbol",
    "cmd+ctrl+alt+d": "detach all contents from symbol",
    "cmd+shift+d": "refresh data",
    "cmd+ctrl+r": "run last-used plugin again",
    "=": "position selected gradient stop directly between two existing stops",
  },
} as AppParams;

export default app;
