import { AppParams } from "~/types";

const app = {
  id: "skype",
  name: "Skype",
  icon: "/app-icons/skype.png",
  homepage: "https://www.skype.com/",
  description:
    "Skype is a telecommunications application, best known for VoIP-based videotelephony, videoconferencing, and voice calls.",
  globals: {},
  shortcuts: {
    "cmdorctrl+shift+o": "open notification panel",
    "cmdorctrl+,": "open app settings",
    "cmdorctrl+2": "launch main dial pad",
    "cmdorctrl+n": "start new conversation",
    "cmdorctrl+g": "new group",
    "cmdorctrl+f": "find in current conversation",
    "shift+enter": "select next message in search results",
    enter: "select previous message in search results",
    "cmdorctrl+shift+e": "edit the last message sent / focus message composer",
    "cmdorctrl+alt+s": "search for people, groups, and messages",
    "alt+1": "navigate to recent chats",
    "cmdorctrl+shift+c": "open contacts",
    "cmdorctrl+shift+b": "open contact screen to bots",
    "cmdorctrl+alt+o": "send feedback",
    "cmdorctrl+r": "refresh the app",
    "cmdorctrl+t": "open themes",
    "cmdorctrl+shift+t": "toggle between light and dark mode",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "cmdorctrl+0": "actual size",
    "cmdorctrl+i": "show conversation profile",
    "cmdorctrl+shift+a": "add people to conversation or call",
    "cmdorctrl+e": "hide conversation",
    "cmdorctrl+shift+u": "mark as unread",
    "cmdorctrl+shift+k": "start video call or toggle video on/off",
    "cmdorctrl+shift+l": "select multiple messages in conversation",
    "cmdorctrl+shift+r": "start or answer audio call",
    "cmdorctrl+shift+f": "send a file",
    "cmdorctrl+shift+g": "open gallery",
    "cmdorctrl+s": "take a snapshot",
    "cmdorctrl+shift+h": "hang up",
    "cmdorctrl+shift+m": "toggle mute",
  },
} as AppParams;

export default app;
