const app = {
  id: "slack",
  name: "Slack",
  icon: "/app-icons/slack.png",
  homepage: "https://slack.com/",
  description:
    "Slack is a cloud-based team communication platform, which offers functionalities such as text messaging, file and media sharing, voice and video calls, and group chat for team collaboration.",
  globals: {},
  shortcuts: {
    "cmdorctrl+n": "compose a new message / undo formatting",
    "cmdorctrl+z": "unsend a message",
    "cmdorctrl+shift+y": "set your status",
    "cmdorctrl+,": "open your preferences",
    "cmdorctrl+shift+d": "show or hide the left sidebar",
    "cmdorctrl+.": "hide the right sidebar",
    "cmdorctrl+shift+n": "create a new canvas",
    "cmdorctrl+u": "upload a file",
    "cmdorctrl+shift+j": "view all downloaded files",
    "cmdorctrl+shift+enter": "create a new snippet",
    "cmdorctrl+shift+`": "add an emoji reaction to a message",
    "cmdorctrl+shift+#": "add an emoji reaction to a message",
    "cmdorctrl+shift+\\": "add an emoji reaction to a message",
    "cmdorctrl+shift+_": "add an emoji reaction to a message",
    "cmdorctrl+shift+e": "open the directory",
    "cmdorctrl+g": "start a search / find next",
    "cmdorctrl+f":
      "search in the current conversation / find text in the canvas",
    "cmdorctrl+shift+h":
      "start, join, leave, or end a huddle / find and replace",
    "cmdorctrl+shift+space": "toggle mute on a huddle",
    f1: "open help",
    "ctrl+cmdorctrl+f": "toggle full screen view",
    f11: "toggle full screen view",
    "cmdorctrl+shift+w": "reopen last closed window",
    "cmdorctrl+k": "jump to a conversation",
    "cmdorctrl+t": "jump to a conversation",
    "cmdorctrl+j": "jump to the most recent unread message in a conversation",
    "alt+shift+up": "jump to previous unread channel or direct message",
    "alt+shift+down": "jump to next unread channel or direct message",
    "cmdorctrl+[": "go back in history",
    "cmdorctrl+]": "go forward in history",
    "cmdorctrl+shift+t": "open the threads view",
    "cmdorctrl+shift+k": "browse dms",
    "cmdorctrl+shift+m": "view mentions & reactions",
    "cmdorctrl+shift+l": "browse channels",
    "cmdorctrl+shift+i": "open conversation details",
    "cmdorctrl+alt+.": "open a conversation's canvas",
    f6: "move focus to the next section",
    "shift+f6": "move focus to the previous section",
    esc: "mark all messages in current conversation as read / mark a group of messages as unread",
    "shift+esc": "mark all messages as read",
    "cmdorctrl+shift+a": "open the all unreads view",
    up: "move between messages",
    down: "move between messages",
    left: "open or collapse a group of messages",
    right: 'open or collapse a group of messages / open or reply to a thread"',
    "cmdorctrl+shift+[": "switch to previous workspace",
    "cmdorctrl+shift+]": "switch to next workspace",
    e: "edit a message you sent",
    delete: "delete a message you sent",
    t: "open or reply to a thread",
    f: "forward a message",
    p: "pin or unpin a message",
    a: "save a message or remove a message from later",
    u: "mark all messages above the one in focus as unread",
    m: "create a reminder about a message",
    r: "add an emoji reaction to a message",
    "shift+up": "select text to beginning of current line",
    "shift+down": "select text to end of current line",
    "shift+enter": "create a new line",
    "cmdorctrl+b": "bold selected text",
    "cmdorctrl+i": "italicize selected text",
    "cmdorctrl+shift+x": "strikethrough selected text",
    "cmdorctrl+shift+u": "hyperlink selected text",
    "cmdorctrl+shift+9": "quote selected text",
    "cmdorctrl+shift+c": "code selected text",
    "cmdorctrl+alt+shift+c": "codeblock selected text",
    "cmdorctrl+shift+8": "format selected text as a bulleted list",
    "cmdorctrl+shift+7": "format selected text as a numbered list",
    "cmdorctrl+shift+f": "apply markdown formatting",
    "cmdorctrl+alt+0": "format selected text as paragraph",
    "cmdorctrl+alt+1": "format selected text as big heading",
    "cmdorctrl+alt+2": "format selected text as medium heading",
    "cmdorctrl+alt+3": "format selected text as small heading",
    "cmdorctrl+shift+0": "format selected text as checklist",
    "cmdorctrl+alt+t": "view comment thread",
    "cmdorctrl+alt+r": "show reader or edit view",
    "cmdorctrl+shift+/": "open context menu",
    "cmdorctrl+shift+g": "find previous",
    "ctrl+alt+q": "copy anchor link to section",
    "cmdorctrl+shift+z": "redo last action",
    "cmdorctrl+alt+up": "move item in a formatted list up",
    "cmdorctrl+alt+down": "move item in a formatted list down",
    "shift+f10": "open context menu",
  },
};

export default app;
