import { AppParams } from "~/types";

const app = {
  id: "superhuman",
  name: "Superhuman",
  icon: "/app-icons/superhuman.png",
  homepage: "https://superhuman.com/",
  description:
    "Superhuman is an email app, targeted at users who want to improve their productivity and features liberal use of keyboard shortcuts to speed up email reading and replying. The app claims they can save up to three hours a week by using it.",
  globals: {},
  shortcuts: {
    "cmdorctrl+k": "superhuman command / hyperlink",
    "/": "search",
    z: "undo",
    "?": "shortcuts",
    x: "select conversation",
    "shift+j": "add to selection",
    "shift+k": "add to selection",
    "shift+u": "unread",
    "shift+s": "starred",
    "shift+i": "important",
    "shift+r": "no reply / pop out reply",
    c: "compose",
    enter: "reply all / open conversation",
    r: "reply",
    f: "forward",
    "cmdorctrl+o": "open links and attachments / color",
    tab: "cycle through links and dates / indent list / next split",
    o: "expand message",
    "shift+o": "expand all messages",
    e: "mark done (archive)",
    "shift+e": "mark as not done",
    h: "remind me (snooze)",
    s: "star",
    u: "mark as read or unread",
    "shift+3": "trash",
    "shift+1": "mark as spam",
    "shift+m": "mute",
    "cmdorctrl+u": "unsubscribe / underline",
    "g+i": "go to inbox or important",
    "g+o": "go to other",
    "g+s": "go to starred",
    "g+d": "go to drafts",
    "g+t": "go to sent mail",
    "g+e": "go to done",
    "g+h": "go to reminders",
    "g+m": "go to muted",
    "g+;": "go to snippets",
    "g+!": "go to spam",
    "g+#": "go to trash",
    "g+a": "go to all mail",
    "g+l": "go to label",
    "cmdorctrl+b": "bold",
    "cmdorctrl+i": "italics",
    "cmdorctrl+shift+x": "strikethrough",
    "cmdorctrl+shift+7": "numbers",
    "cmdorctrl+shift+8": "bullets",
    "cmdorctrl+shift+9": "quote",
    "shift+tab": "outdent list / previous split",
    "cmdorctrl+]": "increase indent",
    "cmdorctrl+[": "decrease indent",
    l: "add or remove a label",
    y: "remove label",
    "[": "remove label, next",
    "]": "remove label, previous",
    "shift+y": "remove all labels",
    v: "move",
    "0": "toggle calendar",
    "-": "previous day",
    "=": "next day",
    j: "next conversation",
    k: "previous conversation",
    n: "next message",
    p: "previous message",
    space: "scroll down",
    "shift+space": "scroll up",
    "cmdorctrl+up": "jump to the top",
    "cmdorctrl+down": "jump to the bottom",
    "cmdorctrl+n": "new window",
    "cmdorctrl+t": "new tab",
    "cmdorctrl+shift+]": "next tab",
    "cmdorctrl+shift+[": "previous tab",
    "cmdorctrl+1": "switch tabs",
    "cmdorctrl+2": "switch tabs",
    "cmdorctrl+3": "switch tabs",
    "cmdorctrl+w": "close tab",
    "ctrl+1": "switch accounts",
    "ctrl+2": "switch accounts",
    "ctrl+3": "switch accounts",
    "cmdorctrl+=": "increase font size",
    "cmdorctrl+minus": "decrease font size",
    "cmdorctrl+0": "reset font size",
    "ctrl+/": "copy page link",
    esc: "back",
    "cmdorctrl+shift+p": "pop draft in or out",
    "shift+enter": "pop out reply-all",
    "shift+c": "pop out new message",
    "shift+f": "pop out forward",
    "cmdorctrl+/": "pop out a draft and search",
    "cmdorctrl+d": "switch to or from a draft",
    "cmdorctrl+shift+o": "to",
    "cmdorctrl+shift+c": "cc",
    "cmdorctrl+shift+b": "bcc",
    "cmdorctrl+shift+f": "from",
    "cmdorctrl+shift+s": "edit subject",
    "cmdorctrl+shift+m": "edit message",
    "cmdorctrl+shift+a": "attach",
    "cmdorctrl+shift+,": "discard draft",
    "cmdorctrl+shift+i": "move contacts to bcc",
    "cmdorctrl+shift+h": "remind me",
    "cmdorctrl+shift+l": "send later",
    "cmdorctrl+;": "use snippet",
    "cmdorctrl+enter": "send",
    "cmdorctrl+shift+enter": "send and mark done",
    "cmdorctrl+shift+z": "instant send",
  },
} as AppParams;

export default app;
