import { AppParams } from "~/types";

const app = {
  id: "tableplus",
  name: "TablePlus",
  icon: "/app-icons/tableplus.png",
  homepage: "https://tableplus.com",
  description:
    "TablePlus is a modern, native, and friendly GUI tool for relational databases.",
  globals: {},
  shortcuts: {
    "cmdorctrl+n": "open a new connection",
    "cmdorctrl+q": "quit app",
    "cmdorctrl+shift+o": "open sql file",
    "cmdorctrl+,": "open preferences",
    "cmdorctrl+w": "close a tab/window",
    "cmdorctrl+s": "commit the changes",
    "cmdorctrl+t": "open a new tab",
    "cmdorctrl+l": "open plugin manager",
    "cmdorctrl+.": "run custom script",
    "cmdorctrl+r": "reload workspace",
    "cmdorctrl+[": "navigate to left tab",
    "cmdorctrl+]": "navigate to right tab",
    "cmdorctrl+shift+[": "navigate to left pane",
    "cmdorctrl+shift+]": "navigate to right pane",
    "cmdorctrl+d": "split pane horizontally",
    "cmdorctrl+1-9": "navigate to number tab",
    "cmdorctrl+k": "switch database",
    "cmdorctrl+shift+k": "switch connection",
    "cmdorctrl+i": "indent selected sql code",
    "cmdorctrl+e": "execute sql code",
    "cmdorctrl+o": "open file sql / open sql query",
    "cmdorctrl+shift+enter": "uglify selected sql statements",
    "cmdorctrl+\\": "comment/uncomment lines of sql",
    "cmdorctrl+z": "undo",
    "cmdorctrl+shift+z": "redo",
    "cmdorctrl+p": "open anything",
    tab: "move focus while editing",
    space: "toggle row detail when row selected",
    "cmdorctrl+c": "copy rows",
    "cmdorctrl+v": "paste rows",
    "cmdorctrl+alt+i": "insert a new row",
  },
} as AppParams;

export default app;
