import { AppParams } from "~/types";

const app = {
  id: "telegram",
  name: "Telegram",
  icon: "/app-icons/telegram.png",
  homepage: "https://telegram.org/",
  description:
    "Telegram is a cloud-based instant messaging and voice over IP service.",
  globals: {},
  shortcuts: {
    up: "edit last message sent / in-chat navigation / navigate / suggested stickers navigation",
    down: "in-chat navigation / navigate / suggested stickers navigation",
    left: "suggested stickers navigation / suggested emojis navigation",
    right: "suggested stickers navigation / suggested emojis navigation",
    "cmdorctrl+tab": "move to the chat below",
    "cmdorctrl+shift+tab": "move to the chat above",
    esc: "exit/go back/cancel current action / exit search",
    "cmdorctrl+o": "send file",
    "cmdorctrl+up": "reply to a message",
    "cmdorctrl+down": "reply to a message / cancel reply",
    delete: "delete currently selected message",
    "cmdorctrl+e": "edit media",
    "cmdorctrl+f": "search selected chat",
    enter: "select chat",
    backspace: "remove chat",
    "cmdorctrl+enter": "send message",
    "alt+enter":
      "jump to the bottom of the chat/scroll the chat list to the top",
    "cmdorctrl+0": "jump to your saved messages",
    "cmdorctrl+1": "jump between folders",
    "cmdorctrl+2": "jump between folders",
    "cmdorctrl+3": "jump between folders",
    "cmdorctrl+4": "jump between folders",
    "cmdorctrl+5": "jump between folders",
    "cmdorctrl+shift+down": "jump to the next folder",
    "cmdorctrl+shift+up": "jump to the previous folder",
    "cmdorctrl+w": "minimize to system tray",
    "cmdorctrl+q": "quit telegram",
    "cmdorctrl+l": "lock telegram",
    "cmdorctrl+m": "minimize telegram",
    "cmdorctrl+b": "bold",
    "cmdorctrl+i": "italic",
    "cmdorctrl+k": "create link",
    "cmdorctrl+u": "underline",
    "cmdorctrl+shift+m": "monospace",
    "cmdorctrl+shift+n": "null/plain text",
    "cmdorctrl+shift+x": "strikethrough",
  },
} as AppParams;

export default app;
