import { AppParams } from "~/types";

const app = {
  id: "todoist",
  name: "Todoist",
  icon: "/app-icons/todoist.png",
  homepage: "https://todoist.com/",
  description:
    "Todoist is a task management application for personal and professional productivity.",
  globals: {},
  shortcuts: {
    q: "quick add",
    "/": "search / pick a section",
    f: "search",
    esc: "dismiss/cancel",
    m: "open/close sidebar",
    "cmdorctrl+k": "open quick find",
    "cmdorctrl+p": "print current view",
    "cmdorctrl+plus": "zoom in",
    "cmdorctrl+minus": "zoom out",
    "#": "pick a project",
    plus: "add an assignee",
    "@": "add a label",
    "!": "add a reminder",
    "shift+g": "open task in its project",
    "o+p": "open productivity",
    "o+h": "open help",
    "o+n": "open notifications",
    "o+u": "open profile photo menu",
    up: "move focus up",
    down: "move focus down",
    right: "move focus to the right",
    left: "move focus to the left",
    "g+i": "go to inbox",
    "g+t": "go to today",
    "g+u": "go to upcoming",
    "g+l": "go to labels",
    "g+p": "go to projects",
    "g+/": "go to section",
    "o+s": "open settings",
    "o+t": "open theme",
    "g+a": "open activity log",
    "g+v": "open filters & labels",
    a: "add new task to the bottom of list",
    "shift+a": "add new task to the top of list",
    enter: "save a newly created task and create a new one below",
    "shift+enter":
      "save changes to an existing task and create a new task below",
    "ctrl+enter":
      "save a new task or save changes to an existing one and create a new task above",
    e: "complete focused task",
    "cmdorctrl+e": "edit task",
    "cmdorctrl+enter": "save edits",
    t: "set due date",
    "shift+t": "remove due date",
    "1": "set priority level",
    "2": "set priority level",
    "3": "set priority level",
    "4": "set priority level",
    y: "change priority level",
    c: "comment",
    l: "add label",
    "shift+r": "assign/reassign",
    v: "move to …",
    ".": "more task actions",
    x: "select focused task",
    ",": "move focus to multi-select toolbar",
    "cmdorctrl+delete": "delete selected task",
    "shift+cmdorctrl+c": "copy link to task",
    "cmdorctrl+up": "move to the task above the task currently being edited",
    "cmdorctrl+down": "move to the task below the task currently being edited",
    "cmdorctrl+]": "increase indent of focused task",
    "cmdorctrl+[": "decrease indent of focused task",
    "shift+e": "see/hide sub-tasks",
    "shift+v": "change to list/board view",
    s: "add section",
    "shift+s": "share project",
    d: "sort by due date",
    p: "sort by priority",
    n: "sort alphabetically",
    r: "sort by assignee",
    w: "open more project actions",
    "alt+shift+y": "go to today in upcoming",
    "shift+right": "next week in upcoming",
    "shift+left": "previous week in upcoming",
  },
} as AppParams;

export default app;
