import { AppParams } from "~/types";

const app = {
  id: "transmit",
  name: "Transmit",
  icon: "/app-icons/transmit.png",
  homepage: "https://panic.com/transmit/",
  description: "Transmit is a file transfer client for macOS and iOS.",
  globals: {},
  shortcuts: {
    "cmdorctrl+,": "preferences",
    "cmdorctrl+h": "hide transmit",
    "cmdorctrl+alt+h": "hide others",
    "cmdorctrl+q": "quit transmit",
    "cmdorctrl+alt+q": "quit and close all windows",
    "cmdorctrl+n": "new window",
    "cmdorctrl+t": "new tab",
    "cmdorctrl+shift+n": "new folder",
    "cmdorctrl+alt+n": "new file",
    "cmdorctrl+w": "close tab",
    "cmdorctrl+shift+w": "close window",
    "cmdorctrl+alt+w": "close all",
    "cmdorctrl+e": "disconnect",
    "cmdorctrl+o": "open",
    "cmdorctrl+s": "save",
    "cmdorctrl+b": "preview in browser",
    "cmdorctrl+i": "get info",
    "cmdorctrl+d": "duplicate",
    "cmdorctrl+y": "quick look at selected-file",
    "cmdorctrl+p": "print",
    "cmdorctrl+z": "undo",
    "cmdorctrl+shift+z": "redo",
    "cmdorctrl+x": "cut",
    "cmdorctrl+c": "copy",
    "cmdorctrl+v": "paste",
    "cmdorctrl+a": "select all",
    "cmdorctrl+j": "jump to selection",
    "cmdorctrl+:": "show spelling and grammar",
    "cmdorctrl+;": "check spelling",
    "cmdorctrl+l": "show transfers",
    "cmdorctrl+alt+l": "show transfers window",
    "cmdorctrl+1": "view as thumbnails",
    "cmdorctrl+2": "view as list",
    "cmdorctrl+3": "view as columns",
    "cmdorctrl+4": "view as cover flow",
    "cmdorctrl+r": "refresh",
    "cmdorctrl+shift+b": "show invisible files",
    "cmdorctrl+shift+s": "hide places bar",
    "cmdorctrl+shift+j": "show view options",
    "cmdorctrl+ctrl+f": "enter full screen",
    "cmdorctrl+alt+left": "focus on local",
    "cmdorctrl+alt+right": "focus on remote",
    "cmdorctrl+[": "back",
    "cmdorctrl+]": "forward",
    "cmdorctrl+up": "enclosing folder",
    "cmdorctrl+alt+g": "go to folder",
    "cmdorctrl+alt+t": "open in terminal",
    "cmdorctrl+shift+l": "link folder navigation",
    "cmdorctrl+k": "connect to last used protocol",
    "cmdorctrl+shift+r": "transfer selected items",
    "cmdorctrl+alt+shift+r": "transfer selected items without rules",
    "cmdorctrl+.": "cancel",
    "cmdorctrl+shift+a": "add new server",
    "cmdorctrl+shift+f": "show quick connect",
    "cmdorctrl+shift+i": "edit server",
    "cmdorctrl+m": "minimize",
    "cmdorctrl+alt+m": "minimize all",
    "ctrl+tab": "select next tab",
    "ctrl+shift+tab": "select previous tab",
    "cmdorctrl+ctrl+t": "transcript",
  },
} as AppParams;

export default app;
