import { AppParams } from "~/types";

const app = {
  id: "vivaldi",
  name: "Vivaldi",
  icon: "/app-icons/vivaldi.png",
  homepage: "https://vivaldi.com/",
  description: "Vivaldi is a freeware, cross-platform web browser.",
  globals: {},
  shortcuts: {
    "cmdorctrl+n": "new window",
    "cmdorctrl+shift+n": "new private window",
    "cmdorctrl+shift+w": "close window",
    "cmdorctrl+e": "quick commands",
    "cmdorctrl+,": "settings",
    "cmdorctrl+alt+e": "extensions",
    "cmdorctrl+h": "history",
    "cmdorctrl+shift+delete": "delete browsing data",
    "cmdorctrl+q": "quit vivaldi",
    "cmdorctrl+shift+?": "help",
    "cmdorctrl+f1": "keyboard cheat sheet",
    "cmdorctrl+p": "print",
    "cmdorctrl+u": "view page source",
    "cmdorctrl+shift+i": "developer tools",
    "cmdorctrl+shift+j": "developer tools console",
    "cmdorctrl+shift+v": "paste and go",
    "cmdorctrl+m": "minimize",
    "cmdorctrl+shift+f": "fullscreen mode",
    "cmdorctrl+shift+b": "bookmarks bar",
    "cmdorctrl+/": "status bar",
    "cmdorctrl+f10": "toggle ui",
    "cmdorctrl+plus": "page zoom in",
    "cmdorctrl+minus": "page zoom out",
    "cmdorctrl+0": "page zoom reset",
    "cmdorctrl+alt+p": "panel",
    f7: "focus panel",
    "cmdorctrl+alt+down": "open next panel",
    "cmdorctrl+alt+up": "open previous panel",
    "cmdorctrl+alt+b": "bookmarks panel",
    "cmdorctrl+alt+l": "downloads panel",
    "cmdorctrl+alt+n": "notes panel",
    "cmdorctrl+alt+y": "history panel",
    "cmdorctrl+t": "new tab",
    "cmdorctrl+w": "close tab",
    "cmdorctrl+shift+tab": "tab cycler back",
    "cmdorctrl+tab": "tab cycler forward",
    "cmdorctrl+shift+[": "previous tab (by order)",
    "cmdorctrl+shift+]": "next tab (by order)",
    "cmdorctrl+shift+up": "move active tab backward",
    "cmdorctrl+shift+down": "move active tab forward",
    "cmdorctrl+1": "switch to tab 1",
    "cmdorctrl+2": "switch to tab 2",
    "cmdorctrl+3": "switch to tab 3",
    "cmdorctrl+4": "switch to tab 4",
    "cmdorctrl+5": "switch to tab 5",
    "cmdorctrl+6": "switch to tab 6",
    "cmdorctrl+7": "switch to tab 7",
    "cmdorctrl+8": "switch to tab 8",
    "cmdorctrl+9": "switch to the last tab",
    "cmdorctrl+shift+t": "reopen last tab",
    "cmdorctrl+f9": "tile vertically",
    "cmdorctrl+f8": "tile horizontally",
    "cmdorctrl+f7": "tile to grid",
    "cmdorctrl+f6": "untile tabs",
    "cmdorctrl+alt+i": "load images",
    "cmdorctrl+d": "create bookmark",
    "cmdorctrl+l": "focus address field",
    "cmdorctrl+r": "reload page",
    "cmdorctrl+shift+r": "force reload page",
    f9: "focus page",
    "cmdorctrl+k": "focus search field",
    "cmdorctrl+f": "find in page",
    "cmdorctrl+g": "find next in page",
    "cmdorctrl+shift+g": "find previous in page",
    "cmdorctrl+left": "history back",
    "cmdorctrl+right": "history forward",
    esc: "stop loading",
    "cmdorctrl+o": "open file",
    "cmdorctrl+s": "save page as",
    "cmdorctrl+shift+h": "home",
    "cmdorctrl+alt+c": "copy selected text to note",
    "shift+left": "spatial navigation left",
    "shift+up": "spatial navigation up",
    "shift+right": "spatial navigation right",
    "shift+down": "spatial navigation down",
  },
} as AppParams;

export default app;
