import { AppParams } from "~/types";

const app = {
  id: "vlc",
  name: "VLC",
  icon: "/app-icons/vlc.png",
  homepage: "https://www.videolan.org/vlc/",
  description:
    "VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.",
  globals: {},
  shortcuts: {
    f: "fullscreen",
    esc: "leave fullscreen",
    space: "play/pause",
    "]": "pause only",
    "[": "play only",
    plus: "faster",
    minus: "slower",
    "=": "normal rate",
    n: "next",
    p: "previous",
    s: "stop",
    t: "position",
    "shift+left": "very short backwards jump",
    "shift+right": "very short forwards jump",
    "alt+left": "short backwards jump",
    "alt+right": "short forwards jump",
    "cmdorctrl+left": "medium backwards jump",
    "cmdorctrl+right": "medium forwards jump",
    "cmdorctrl+alt+left": "long backwards jump",
    "cmdorctrl+alt+right": "long forwards jump",
    e: "next frame",
    enter: "activate",
    up: "navigate up",
    down: "navigate down",
    left: "navigate left",
    right: "navigate right",
    "shift+m": "go to the DVD menu",
    "shift+o": "select previous DVD title",
    "shift+b": "select next DVD title",
    "shift+p": "select previous DVD chapter",
    "shift+n": "select next DVD chapter",
    "cmdorctrl+q": "quit",
    "cmdorctrl+up": "volume up",
    "cmdorctrl+down": "volume down",
    m: "mute",
    h: "subtitle delay up",
    g: "subtitle delay down",
    k: "audio delay up",
    j: "audio delay down",
    b: "cycle audio track",
    "shift+a": "cycle through audio devices",
    v: "cycle subtitle track",
    a: "cycle source aspect ratio",
    c: "cycle video crop",
    o: "toggle autoscaling",
    "alt+o": "increase scale factor",
    "shift+alt+o": "decrease scale factor",
    d: "cycle deinterlace modes",
    i: "show interface",
    "shift+i": "hide interface",
    "shift+s": "take video snapshot",
    "shift+g": "go back in browsing history",
    "shift+h": "go forward in browsing history",
    "shift+r": "record",
    "shift+d": "dump",
    z: "zoom",
    "shift+z": "un-zoom",
    w: "toggle wallpaper mode",
    "alt+shift+m": "display OSD menu on top",
    "alt+cmdorctrl+m": "do not display OSD menu",
    "alt+shift+right": "highlight widget on the right",
    "alt+shift+left": "highlight widget on the left",
    "alt+shift+up": "highlight widget on top",
    "alt+shift+down": "highlight widget on bottom",
    "alt+shift+enter": "select current widget",
    "alt+r": "crop one pixel from the top",
    "alt+shift+r": "uncrop one pixel from the top",
    "alt+d": "crop one pixel from the left",
    "alt+shift+d": "uncrop one pixel from the left",
    "alt+c": "crop one pixel from the bottom",
    "alt+shift+c": "uncrop one pixel from the bottom",
    "alt+f": "crop one pixel from the right",
    "alt+shift+f": "uncrop one pixel from the right",
    r: "random",
    l: "normal/repeat/loop",
    "cmdorctrl+1": "1:4 quarter",
    "cmdorctrl+2": "1:2 half",
    "cmdorctrl+3": "1:1 original",
    "cmdorctrl+4": "2:1 double",
    "3": "very short jump length (integer)",
    "cmdorctrl+f1": "set playlist bookmark 1",
    "cmdorctrl+f2": "set playlist bookmark 2",
    "cmdorctrl+f3": "set playlist bookmark 3",
    "cmdorctrl+f4": "set playlist bookmark 4",
    "cmdorctrl+f5": "set playlist bookmark 5",
    "cmdorctrl+f6": "set playlist bookmark 6",
    "cmdorctrl+f7": "set playlist bookmark 7",
    "cmdorctrl+f8": "set playlist bookmark 8",
    "cmdorctrl+f9": "set playlist bookmark 9",
    "cmdorctrl+f10": "set playlist bookmark 10",
    f1: "play playlist bookmark 1",
    f2: "play playlist bookmark 2",
    f3: "play playlist bookmark 3",
    f4: "play playlist bookmark 4",
    f5: "play playlist bookmark 5",
    f6: "play playlist bookmark 6",
    f7: "play playlist bookmark 7",
    f8: "play playlist bookmark 8",
    f9: "play playlist bookmark 9",
    f10: "play playlist bookmark 10",
  },
} as AppParams;

export default app;
