const app = {
  id: "webstorm",
  name: "Webstorm",
  icon: "/app-icons/webstorm.png",
  homepage: "https://www.jetbrains.com/webstorm/",
  description:
    "WebStorm is a cross-platform IDE primarily for web, JavaScript, and TypeScript development.",
  globals: {},
  shortcuts: {
    "cmdorctrl+space": "basic code completion",
    "alt+enter": "show intention actions, quick fixes",
    "cmdorctrl+p": "parameter info",
    "cmdorctrl+q": "quick documentation lookup",
    "cmdorctrl+f1": "error or warning at caret",
    "alt+ins": "generate code...",
    "cmdorctrl+alt+t": "surround with...",
    "cmdorctrl+j": "insert live template",
    "cmdorctrl+/": "comment/uncomment with line",
    "cmdorctrl+shift+/": "comment/uncomment with block",
    "cmdorctrl+w": "select successively increasing code blocks",
    "cmdorctrl+shift+w": "decrease current selection to previous state",
    "alt+q": "context info",
    "cmdorctrl+alt+l": "reformat code",
    "cmdorctrl+alt+i": "auto-indent line(s)",
    tab: "indent selected lines",
    "shift+tab": "unindent selected lines",
    "cmdorctrl+shift+v": "paste from recent buffers...",
    "cmdorctrl+d": "duplicate current line or selected block",
    "cmdorctrl+y": "delete line at caret",
    "alt+shift+up": "move line up",
    "alt+shift+down": "move line down",
    "cmdorctrl+shift+j": "join lines",
    "cmdorctrl+enter": "split lines",
    "shift+enter": "start new line",
    "cmdorctrl+shift+u": "toggle case for word at caret or selected block",
    "cmdorctrl+shift+]": "select till code block end",
    "cmdorctrl+shift+[": "select till code block start",
    "cmdorctrl+delete": "delete to word end",
    "cmdorctrl+backspace": "delete to word start",
    "cmdorctrl+plus": "expand code block",
    "cmdorctrl+minus": "collapse code block",
    "cmdorctrl+shift+plus": "expand all",
    "cmdorctrl+shift+minus": "collapse all",
    "cmdorctrl+f4": "close active editor tab",
    "cmdorctrl+shift+a": "find action",
    "alt+0...9": "open corresponding tool window",
    "cmdorctrl+shift+f12": "toggle maximizing editor",
    "alt+shift+f": "add to favorites",
    "alt+shift+i": "inspect current file",
    "cmdorctrl+`": "quick switch current scheme",
    "cmdorctrl+alt+s": "open settings dialog",
    "cmdorctrl+tab": "switch between tools and tabs",
    "cmdorctrl+b": "go to declaration",
    "cmdorctrl+n": "go to class",
    "cmdorctrl+shift+n": "go to file",
    "cmdorctrl+alt+shift+n": "go to symbol",
    "alt+right": "go to next editor tab",
    "alt+left": "go to previous editor tab",
    f12: "go back to previous tool window",
    esc: "go to editor / unselect all occurrences or carets",
    "cmdorctrl+g": "go to line",
    "cmdorctrl+e": "recent files popup",
    "cmdorctrl+alt+right": "navigate forward",
    "cmdorctrl+alt+left": "navigate back",
    "cmdorctrl+shift+backspace": "navigate to last edit location",
    "alt+f1": "select current file or symbol in any view",
    "cmdorctrl+alt+b": "go to implementation(s)",
    "cmdorctrl+shift+i": "open quick definition lookup",
    "cmdorctrl+shift+b": "go to type declaration",
    "cmdorctrl+u": "go to super-method/super-class",
    "alt+up": "go to previous method",
    "alt+down": "go to next method",
    "cmdorctrl+]": "move to code block end",
    "cmdorctrl+[": "move to code block start",
    "cmdorctrl+shift+m": "move caret to matching brace",
    "cmdorctrl+f12": "file structure popup",
    "cmdorctrl+h": "type hierarchy",
    "cmdorctrl+alt+h": "call hierarchy",
    f2: "next highlighted error",
    "shift+f2": "previous highlighted error",
    f4: "jump to source",
    "alt+home": "jump to navigation bar",
    f11: "toggle bookmark",
    "cmdorctrl+shift+f11": "toggle bookmark with mnemonic",
    "shift+f11": "show bookmarks",
    "shift+cmdorctrl+alt+j": "select all occurrences",
    "alt+j": "select next occurrence",
    "alt+shift+j": "unselect occurrence",
    f8: "step over",
    f7: "step into",
    "shift+f7": "smart step into",
    "shift+f8": "step out",
    "alt+f9": "run to cursor",
    "alt+f8": "evaluate expression",
    f9: "resume program",
    "cmdorctrl+f8": "toggle breakpoint",
    "cmdorctrl+shift+f8": "view breakpoints",
    "alt+shift+f10": "select configuration and run",
    "alt+shift+f9": "select configuration and debug",
    "shift+f10": "run",
    "shift+f9": "debug",
    "cmdorctrl+shift+f10": "run context configuration from editor",
    "alt+shift+r": "rerun tests",
    "alt+f11": "run gulp/grunt/npm tasks",
    "alt+f7": "find usages",
    "cmdorctrl+f7": "find usages in file",
    "cmdorctrl+shift+f7": "highlight usages in file",
    "cmdorctrl+alt+f7": "show usages",
    "alt+`": "vcs quick popup",
    "cmdorctrl+k": "commit project to vcs",
    "cmdorctrl+t": "update project from vcs",
    "alt+shift+c": "view recent changes",
    "cmdorctrl+f": "find",
    f3: "find next",
    "shift+f3": "find previous",
    "cmdorctrl+shift+f": "find in path",
    "cmdorctrl+r": "replace",
    "cmdorctrl+shift+r": "replace in path",
    "cmdorctrl+alt+shift+t": "refactor this",
    f5: "copy",
    f6: "move",
    "alt+delete": "safe delete",
    "Shift+F6": "Rename",
    "Ctrl+F6": "Change function signature",
    "Ctrl+Alt+N": "Inline Variable",
    "Ctrl+Alt+M": "Extract Method",
    "Ctrl+Alt+V": "Extract Variable",
    "Ctrl+Alt+C": "Extract Constant",
    "Ctrl+Alt+P": "Extract Parameter",
  },
};

export default app;
