const app = {
  id: "windows",
  name: "Windows",
  icon: "/app-icons/windows.png",
  homepage: "https://www.microsoft.com/windows",
  description:
    "Windows is the most popular desktop operating system in the world",
  globals: {
    "win+Tab": "Open Task view",
    "win+Ctrl+D": "Add a virtual desktop",
    "win+Ctrl+Right":
      "Switch between virtual desktops you’ve created on the right",
    "win+Ctrl+Left":
      "Switch between virtual desktops you’ve created on the left",
    "win+Ctrl+F4": "Close the virtual desktop you're using",
    win: "Open or close Start",
    "win+A": "Open Quick Settings",
    "win+B": "Set focus to the first icon in the Taskbar corner",
    "win+C": "Open Windows Copilot",
    "win+Shift+C": "Open the charms menu",
    "win+Ctrl+C": "Turn on color filters",
    "win+D": "Display and hide the desktop",
    "win+E": "Open File Explorer",
    "win+F": "Open Feedback Hub and take a screenshot",
    "win+G": "Open Xbox Game Bar when a game is open",
    "win+Alt+B": "Turn HDR on or off",
    "win+H": "Launch voice typing",
    "win+I": "Open Settings",
    "win+J": "Set focus to a Windows tip when one is available",
    "win+K": "Open Cast from Quick Settings. Updated in Windows 11",
    "win+Alt+K":
      "Toggle microphone mute in apps that support Call Mute. Available starting in Windows 11, version 22H2",
    "win+L": "Lock your PC or switch accounts",
    "win+M": "Minimize all windows",
    "win+Shift+M": "Restore minimized windows on the desktop",
    "win+N": "Open notification center and calendar. Updated in Windows 11",
    "win+O": "Lock device orientation",
    "win+P": "Choose a presentation display mode",
    "win+Ctrl+Q": "Open Quick Assist",
    "win+R": "Open the Run dialog box",
    "win+Alt+R": "Record video of game window in focus (using Xbox Game Bar)",
    "win+S": "Open search",
    "win+Shift+S": "Take a screenshot of part of your screen",
    "win+T": "Cycle through apps on the taskbar",
    "win+U": "Open Accessibility Settings",
    "win+V": "Open the clipboard history",
    "win+Shift+V": "Set focus to a notification",
    "win+W": "Open Widgets. Updated in Windows 11",
    "win+X": "Open the Quick Link menu",
    "win+Y": "Switch input between Windows Mixed Reality and your desktop",
    "win+Z": "Open the snap layouts. Updated in Windows 11",
    "win+.": "Open emoji panel",
    "win+;": "Open emoji panel",
    "win+,": "Temporarily peek at the desktop",
    "win+Ctrl+F": "Search for PCs (if you're on a network)",
    "win+Up": "Maximize the window",
    "win+Alt+Up":
      "Snap window in focus to top half of screen. New with Windows 11",
    "win+Down": "Remove current app from screen or minimize the desktop window",
    "win+Alt+Down":
      "Snap window in focus to bottom half of screen. New with Windows 11",
    "win+Left":
      "Maximize the app or desktop window to the left side of the screen",
    "win+Right":
      "Maximize the app or desktop window to the right side of the screen",
    "win+Home":
      "Minimize all except the active desktop window (restores all windows on second stroke)",
    "win+Shift+Up":
      "Stretch the desktop window to the top and bottom of the screen",
    "win+Shift+Down":
      "Restore/minimize active desktop windows vertically, maintaining width",
    "win+Shift+Left":
      "Move an app or window in the desktop from one monitor to another",
    "win+Shift+Right":
      "Move an app or window in the desktop from one monitor to another",
    "win+Shift+Space": "Cycle backwards through language and keyboard layout",
    "win+Space": "Switch input language and keyboard layout",
    "win+Ctrl+Space": "Change to a previously selected input",
    "win+Ctrl+Enter": "Turn on Narrator",
    "win+Plus": "Open Magnifier and zoom in",
    "win+Minus": "Zoom out in Magnifier",
    "win+Esc": "Close Magnifier",
    "win+/": "Begin IME reconversion",
    "win+Ctrl+Shift+B": "Wake PC from blank or black screen",
    "win+Alt+Enter": "Open taskbar settings",
  },
  shortcuts: {
    "Ctrl+X": "Cut the selected item",
    "Ctrl+C": "Copy the selected item",
    "Ctrl+V": "Paste the selected item",
    "shift+Ctrl+V": "Paste as plain text",
    "Ctrl+Z": "Undo an action",
    "Alt+Tab": "Switch between open apps",
    "Alt+F4": "Close the active item, or exit the active app",
    "win+ D": "Display and hide the desktop",
    F2: "Rename the selected item",
    F3: "Search for a file or folder in File Explorer",
    F4: "Display the address bar list in File Explorer",
    F5: "Refresh the active window",
    F6: "Cycle through screen elements in a window or on the desktop",
    F10: "Activate the Menu bar in the active app",
    "Alt+A": "Set focus to the first icon in the Suggested actions menu",
    "Alt+F8": "Show your password on the sign-in screen",
    "Alt+Esc": "Cycle through items in the order in which they were opened",
    "Alt+Enter": "Display properties for the selected item",
    "Alt+Space": "Open the shortcut menu for the active window",
    "Alt+Left": "Go back",
    "Alt+Right": "Go forward",
    "Alt+pgup": "Move up one screen",
    "Alt+pgdn": "Move down one screen",
    "Ctrl+F4":
      "Close the active document (in apps that are full-screen and let you have multiple documents open at the same time)",
    "Ctrl+A": "Select all items in a document or window",
    "Ctrl+D": "Delete the selected item and move it to the Recycle Bin",
    "Ctrl+E": "Open Search (in most apps)",
    "Ctrl+R": "Refresh the active window",
    "Ctrl+Y": "Redo an action",
    "Ctrl+Right": "Move the cursor to the beginning of the next word",
    "Ctrl+Left": "Move the cursor to the beginning of the previous word",
    "Ctrl+Down": "Move the cursor to the beginning of the next paragraph",
    "Ctrl+Up": "Move the cursor to the beginning of the previous paragraph",
    "Ctrl+Alt+Tab": "Use the arrow keys to switch between all open apps",
    "Ctrl+Esc": "Open Start",
    "Ctrl+Shift+Esc": "Open Task Manager",
    "Ctrl+Shift":
      "Switch the keyboard layout when multiple keyboard layouts are available",
    "Ctrl+Space": "Turn the Chinese input method editor (IME) on or off",
    "Shift+F10": "Display the shortcut menu for the selected item",
    "Shift+Delete":
      "Delete the selected item without moving it to the Recycle Bin first",
    Right: "Open the next menu to the right, or open a submenu",
    Left: "Open the next menu to the left, or close a submenu",
    Esc: "Stop or leave the current task",
  },
};

export default app;
