const app = {
  id: "windows",
  name: "Windows",
  icon: "/app-icons/windows.png",
  homepage: "https://microsoft.com/windows",
  globals: {
    "Ctrl+X": "Cut the selected item",
    "Ctrl+C": "Copy the selected item",
    "Ctrl+V": "Paste the selected item",
    "Ctrl+Z": "Undo an action",
    "Alt+Tab": "Switch between open apps",
    "Alt+F4": "Close the active item, or exit the active app",
    "win+L": "Lock your PC",
    "win+D": "Display and hide the desktop",
    F2: "Rename the selected item",
    F3: "Search for a file or folder in File Explorer",
    F4: "Display the address bar list in File Explorer",
    F5: "Refresh the active window",
    F6: "Cycle through screen elements in a window or on the desktop",
    F10: "Activate the Menu bar in the active app",
    "Alt+F8": "Show your password on the sign-in screen",
    "Alt+Esc": "Cycle through items in the order in which they were opened",
    "Alt+Enter": "Display properties for the selected item",
    "Alt+space": "Open the shortcut menu for the active window",
    "Alt+arrowLeft": "Go back",
    "Alt+arrowRight": "Go forward",
    "Alt+pgUp": "Move up one screen",
    "Alt+pgDown": "Move down one screen",
    "Ctrl+F4": "Close the active document ",
    "Ctrl+A": "Select all items in a document or window",
    "Ctrl+D": "Delete the selected item and move it to the Recycle Bin",
    "Ctrl+R": "Refresh the active window",
    "Ctrl+Y": "Redo an action",
    "Ctrl+arrowRight": "Move the cursor to the beginning of the next word",
    "Ctrl+arrowLeft": "Move the cursor to the beginning of the previous word",
    "Ctrl+arrowDown": "Move the cursor to the beginning of the next paragraph",
    "Ctrl+arrowUp":
      "Move the cursor to the beginning of the previous paragraph",
    "Ctrl+Alt+Tab": "Use the arrow keys to switch between all open apps",
    "Ctrl+Esc": "Open Start",
    "Ctrl+Shift+Esc": "Open Task Manager",
    "Ctrl+Shift": "Switch the keyboard layout",
    "Ctrl+Space": "Turn the Chinese input method editor (IME) on or off",
    "Shift+F10": "Display the shortcut menu for the selected item",
    "Shift+arrow":
      "Select more than one item in a window or on the desktop, or select text in a document",
    "Shift+Delete":
      "Delete the selected item without moving it to the Recycle Bin first",
    arrowRight: "Open the next menu to the right, or open a submenu",
    arrowLeft: "Open the next menu to the left, or close a submenu",
    Esc: "Stop or leave the current task",
    win: "Open or close Start",
    "win+A": "Open Action center",
    "win+B": "Set focus in the notification area",
    "win+C": "Open Cortana in listening mode",
    "win+Shift+C": "Open the charms menu",
    "win+E": "Open File Explorer",
    "win+F": "Open Feedback Hub and take a screenshot",
    "win+G": "Open Game bar when a game is open",
    "win+H": "Start dictation",
    "win+I": "Open Settings",
    "win+J": "Set focus to a Windows tip when one is available.",
    "win+K": "Open the Connect quick action",
    "win+M": "Minimize all windows",
    "win+O": "Lock device orientation",
    "win+P": "Choose a presentation display mode",
    "win+R": "Open the Run dialog box",
    "win+S": "Open search",
    "win+T": "Cycle through apps on the taskbar",
    "win+U": "Open Ease of Access Center",
    "win+V": "Cycle through notifications",
    "win+Shift+V": "Cycle through notifications in reverse order",
    "win+X": "Open the Quick Link menu",
    "win+Y": "Switch input between Windows Mixed Reality and your desktop",
    "win+Z": "Show the commands available in an app in full-screen mode",
    "win+period (.) or semicolon (;)": "Open emoji panel",
    "win+comma (,)": "Temporarily peek at the desktop",
    "win+Pause": "Display the System Properties dialog box",
    "win+Ctrl+F": "Search for PCs (if you're on a network)",
    "win+Shift+M": "Restore minimized windows on the desktop",
    "win+number":
      "Open the desktop and start the app pinned to the taskbar in the position indicated by the number. If the app is already running, switch to that app.",
    "win+Shift+number":
      "Open the desktop and start a new instance of the app pinned to the taskbar in the position indicated by the number",
    "win+Ctrl+number":
      "Open the desktop and switch to the last active window of the app pinned to the taskbar in the position indicated by the number",
    "win+Alt+number":
      "Open the desktop and open the Jump List for the app pinned to the taskbar in the position indicated by the number",
    "win+Ctrl+Shift+number":
      "Open the desktop and open a new instance of the app located at the given position on the taskbar as an administrator",
    "win+Tab": "Open Task view",
    "win+arrowUp": "Maximize the window",
    "win+arrowDown":
      "Remove current app from screen or minimize the desktop window",
    "win+arrowLeft":
      "Maximize the app or desktop window to the left side of the screen",
    "win+arrowRight":
      "Maximize the app or desktop window to the right side of the screen",
    "win+Home":
      "Minimize all except the active desktop window (restores all windows on second stroke)",
    "win+Shift+arrowUp":
      "Stretch the desktop window to the top and bottom of the screen",
    "win+Shift+arrowDown":
      "Restore/minimize active desktop windows vertically, maintaining width",
    "win+Shift+arrowLeft or Right arrow":
      "Move an app or window in the desktop from one monitor to another",
    "win+space": "Switch input language and keyboard layout",
    "win+Ctrl+space": "Change to a previously selected input",
    "win+Ctrl+Enter": "Open Narrator",
    "win+forward slash (/)": "Begin IME reconversion",
    "win+Ctrl+V": "Open shoulder taps",
    "Ctrl+M": "Enter Mark mode",
    "Alt+selection key": "Begin selection in block mode",
    "Arrow keys": "Move the cursor in the direction specified",
    "Page up": "Move the cursor by one page up",
    "Page down": "Move the cursor by one page down",
    "Ctrl+Home (Mark mode)": "Move the cursor to the beginning of the buffer",
    "Ctrl+End (Mark mode)": "Move the cursor to the end of the buffer",
    "Ctrl+Home (History navigation)":
      "If the command line is empty, move the viewport to the top of the buffer. Otherwise, delete all the characters to the left of the cursor in the command line.",
    "Ctrl+End (History navigation)":
      "If the command line is empty, move the viewport to the command line. Otherwise, delete all the characters to the right of the cursor in the command line.",
    "Ctrl+Tab": "Move forward through tabs",
    "Ctrl+Shift+Tab": "Move back through tabs",
    "Ctrl+number": "Move to nth tab",
    Tab: "Move forward through options",
    "Shift+Tab": "Move back through options",
    "Alt+underlined letter":
      "Perform the command (or select the option) that is used with that letter",
    space: "Select or clear the check box if the active option is a check box",
    Backspace:
      "Open a folder one level up if a folder is selected in the Save As or Open dialog box",
    "Alt+D": "Select the address bar",
    "Ctrl+E": "Select the search box",
    "Ctrl+F": "Select the search box",
    "Ctrl+N": "Open a new window",
    "Ctrl+W": "Close the active window",
    "Ctrl+mouse scroll wheel":
      "Change the size and appearance of file and folder icons",
    "Ctrl+Shift+E": "Display all folders above the selected folder",
    "Ctrl+Shift+N": "Create a new folder",
    "Num Lock+asterisk (*)": "Display all subfolders under the selected folder",
    "Num Lock+plus (+)": "Display the contents of the selected folder",
    "Num Lock+minus (-)": "Collapse the selected folder",
    "Alt+P": "Display the preview panel",
    "Alt+arrowUp": "View the folder that the folder was in",
    End: "Display the bottom of the active window",
    Home: "Display the top of the active window",
    F11: "Maximize or minimize the active window",
    "win+Ctrl+D": "Add a virtual desktop",
    "win+Ctrl+arrowRight":
      "Switch between virtual desktops you’ve created on the right",
    "win+Ctrl+arrowLeft":
      "Switch between virtual desktops you’ve created on the left",
    "win+Ctrl+F4": "Close the virtual desktop you're using",
  },
  shortcuts: {},
};

export { app };
