const app = {
  id: "xcode",
  name: "Xcode",
  icon: "/app-icons/xcode.png",
  homepage: "https://developer.apple.com/xcode/",
  description:
    "Xcode is an integrated development environment for macOS containing a suite of software development tools developed by Apple for developing software for macOS, iOS, iPadOS, watchOS, and tvOS.",
  globals: {},
  shortcuts: {
    "cmd+0": "show/hide navigator pane",
    "cmd+1": "project / physical size in simulator",
    "cmd+2": "source control / point accurate in simulator",
    "cmd+3": "symbols / pixel accurate in simulator",
    "cmd+4": "find / fit screen in simulator",
    "cmd+5": "issues",
    "cmd+6": "tests",
    "cmd+7": "debug",
    "cmd+8": "breakpoints",
    "cmd+9": "reports",
    "alt+cmd+0": "show/hide inspector pane",
    "alt+cmd+1": "file",
    "alt+cmd+2": "history",
    "alt+cmd+3": "help",
    "alt+cmd+4": "attributes",
    "ctrl+1": "related items",
    "ctrl+2": "previous",
    "ctrl+3": "next",
    "ctrl+4": "top level items",
    "ctrl+5": "group files",
    "ctrl+6": "document items",
    "cmd+n": "new file",
    "alt+cmd+n": "new folder",
    "cmd+o": "open file",
    "shift+cmd+o": "open quickly",
    "cmd+s": "save / save screen in simulator",
    "alt+cmd+s": "save all",
    "shift+cmd+j": "reveal in project navigator",
    "ctrl+cmd+j": "jump to definition",
    "cmd+l": "jump to line",
    "cmd+'": "jump to next issue",
    "shift+cmd+0": "developer documentation",
    "shift+cmd+2": "devices and simulators",
    "shift+cmd+h": "apple hig / home in simulator",
    "cmd+return": "show editor only",
    "alt+cmd+return": "show swiftui canvas",
    "ctrl+alt+cmd+return": "show assistant editor",
    "alt+cmd+p": "resume swiftui preview",
    "ctrl+i": "reindent",
    "cmd+[": "shift left",
    "cmd+]": "shift right",
    "cmd+/": "comment selection",
    "alt+cmd+/": "add documentation",
    "shift+cmd+a": "show code actions",
    "ctrl+cmd+e": "edit all in scope",
    "ctrl+alt+cmd+f": "fix all issues",
    "cmd+b": "build",
    "cmd+r": "run / record screen in simulator",
    "cmd+u": "test",
    "cmd+i": "profile",
    "cmd+.": "stop",
    "shift+cmd+k": "clean / connect keyboard in simulator",
    "shift+cmd+y": "show debug",
    "cmd+y": "activate breakpoints",
    "cmd+\\": "breakpoint at current line",
    "cmd+k": "clear console",
    "cmd+left": "rotate left in simulator",
    "cmd+right": "rotate right in simulator",
    "alt+cmd+plus": "increase preferred text size in simulator",
    "alt+cmd+minus": "decrease preferred text size in simulator",
  },
};

export default app;
