const app = {
  id: "zoom",
  name: "Zoom",
  icon: "/app-icons/zoom.png",
  homepage: "https://zoom.us/",
  description:
    "Zoom, also called Zoom Meetings, is a videotelephony software program. The free plan allows up to 100 concurrent participants, with a 40-minute time restriction.",
  globals: {},
  shortcuts: {
    "cmdorctrl+j": "join meeting",
    "cmdorctrl+ctrl+v": "start meeting",
    "cmdorctrl+ctrl+s": "screen share via direct share",
    "cmdorctrl+shift+a": "mute or unmute audio",
    "cmdorctrl+ctrl+u": "mute audio for everyone except the host (host only)",
    space: "push to talk",
    "cmdorctrl+shift+v": "start or stop video",
    "cmdorctrl+shift+n": "switch camera",
    "cmdorctrl+shift+s": "start or stop screen share",
    "cmdorctrl+shift+t": "pause or resume screen share",
    "cmdorctrl+shift+r": "start local recording",
    "cmdorctrl+shift+c": "start cloud recording",
    "cmdorctrl+shift+p": "pause or resume recording",
    "cmdorctrl+shift+w": "switch to active speaker view or gallery view",
    "ctrl+p": "view previous 25 participants in gallery view",
    "ctrl+n": "view next 25 participants in gallery view",
    "cmdorctrl+u": "display or hide participants panel",
    "cmdorctrl+shift+h": "show or hide in-meeting chat panel",
    "cmdorctrl+i": "open invite window",
    "alt+y": "raise hand or lower hand",
    "ctrl+shift+r": "gain remote control",
    "ctrl+shift+g": "stop remote control",
    "cmdorctrl+shift+f": "enter or exit full screen",
    "cmdorctrl+shift+m": "switch to minimal window",
    "shift+alt+cmdorctrl+h": "show or hide meeting controls",
    "cmdorctrl+w": "prompt to end or leave meeting",
    "cmdorctrl+k": "jump to chat with someone",
    "cmdorctrl+t": "screenshot",
    "cmdorctrl+l": "switch to portrait or landscape view",
    "ctrl+t": "switch from one tab to the next",
    f6: "navigate among zoom popup windows",
    "ctrl+alt+shift": "move focus to zoom's meeting controls",
    pgup: "view previous 25 video stream in gallery view",
    pgdn: "view next 25 video stream in gallery view",
    "alt+f1": "switch to active speaker view in video meeting",
    "alt+f2": "switch to gallery video view in video meeting",
    "alt+f4": "close the current window",
    "alt+v": "start or stop video",
    "alt+a": "mute or unmute audio",
    "alt+m": "mute or unmute audio for everyone except host (host only)",
    "alt+s": "launch share screen window and stop screen share",
    "alt+shift+s": "start or stop new screen share",
    "alt+t": "pause or resume screen share",
    "alt+r": "start or stop local recording",
    "alt+c": "start or stop cloud recording",
    "alt+p": "pause or resume recording",
    "alt+n": "switch camera",
    "alt+h": "display or hide in-meeting chat panel",
    "alt+u": "display or hide participants panel",
    "alt+i": "open invite window",
    "alt+shift+r": "gain remote control",
    "alt+shift+g": "stop remote control",
    "ctrl+2": "read active speaker name",
    "alt+shift+t": "screenshot",
    "alt+l": "switch to portrait or landscape view",
    "ctrl+up": "go to previous chat",
    "ctrl+down": "go to next chat",
    "ctrl+f": "search",
    "ctrl+tab": "move to the next tab",
  },
};

export default app;
